// @generated by tools/generate-trnm-world-boundary.py; DO NOT EDIT.

pub const DIAGNOSTIC_MAX_UTF8_BYTES: usize = 256;
pub const DIAGNOSTIC_FALLBACK: &str = "request rejected";
pub const FORBIDDEN_AUTHORITY_KEYS: &[&str] = &[
    "authority_private_key",
    "canonical_archive_root",
    "chain_app_hash",
    "chain_finality",
    "command_idempotency_key",
    "completion_signature",
    "global_event_cursor",
    "global_event_sequence",
    "match_authority_private_key",
    "match_completed_v1",
    "match_version",
    "nakama_private_key",
    "nakama_session_token",
    "participant_admission_receipt",
    "participant_role",
    "participant_roster",
    "participant_sequence",
    "settlement",
    "wallet",
];

pub fn is_forbidden_authority_key(value: &str) -> bool {
    FORBIDDEN_AUTHORITY_KEYS
        .iter()
        .any(|candidate| candidate.eq_ignore_ascii_case(value))
}

pub fn bound_diagnostic_utf8(value: &str) -> String {
    let mut output = String::with_capacity(value.len().min(DIAGNOSTIC_MAX_UTF8_BYTES));
    for character in value.chars() {
        let normalized = if character < '\u{20}' || character == '\u{7f}' {
            ' '
        } else {
            character
        };
        if output.len() + normalized.len_utf8() > DIAGNOSTIC_MAX_UTF8_BYTES {
            break;
        }
        output.push(normalized);
    }
    let bounded = output.trim();
    if bounded.is_empty() {
        DIAGNOSTIC_FALLBACK.to_owned()
    } else {
        bounded.to_owned()
    }
}
