-- Audited operator controls for terminal settlement recovery.
--
-- This migration deliberately does not add a generic queue reset. A replay
-- request must bind every immutable settlement identity, may authorize only one
-- additional remote attempt, and is retained as append-only evidence.

create table if not exists public.trnm_online_settlement_operator_policy_revisions (
    policy_revision bigint generated by default as identity primary key,
    contract_version text not null
        check (contract_version = 'trnm_settlement_operator_policy_v1'),
    retention_days integer not null
        check (retention_days between 365 and 36500),
    dead_letter_alert_threshold bigint not null
        check (dead_letter_alert_threshold between 1 and 1000000),
    expired_lease_alert_threshold bigint not null
        check (expired_lease_alert_threshold between 1 and 1000000),
    oldest_eligible_alert_seconds bigint not null
        check (oldest_eligible_alert_seconds between 30 and 86400),
    oldest_pending_apply_alert_seconds bigint not null
        check (oldest_pending_apply_alert_seconds between 30 and 86400),
    replay_24h_alert_threshold bigint not null
        check (replay_24h_alert_threshold between 1 and 1000000),
    approved_by text not null
        check (btrim(approved_by) <> '' and length(approved_by) <= 256),
    change_ticket text not null
        check (change_ticket ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$'),
    reason text not null
        check (length(btrim(reason)) between 8 and 1024),
    created_at timestamptz not null default pg_catalog.clock_timestamp()
);

insert into public.trnm_online_settlement_operator_policy_revisions (
    policy_revision,
    contract_version,
    retention_days,
    dead_letter_alert_threshold,
    expired_lease_alert_threshold,
    oldest_eligible_alert_seconds,
    oldest_pending_apply_alert_seconds,
    replay_24h_alert_threshold,
    approved_by,
    change_ticket,
    reason
) values (
    1,
    'trnm_settlement_operator_policy_v1',
    2555,
    1,
    1,
    300,
    300,
    3,
    'migration-default-candidate',
    'WORLD-P0-001',
    'Candidate fail-closed defaults pending production operations approval'
)
on conflict (policy_revision) do nothing;

create table if not exists public.trnm_online_settlement_operator_replay_requests (
    request_id text primary key
        check (request_id ~ '^trnm-settlement-replay-v1:[0-9a-f]{64}$'),
    contract_version text not null
        check (contract_version = 'trnm_settlement_operator_replay_v1'),
    job_id text not null
        references public.trnm_online_settlement_jobs(job_id) on delete restrict,
    capture_id text not null
        references public.trnm_online_settlement_captures(capture_id) on delete restrict,
    intent_id text not null check (btrim(intent_id) <> ''),
    intent_hash text not null check (intent_hash ~ '^[0-9a-f]{64}$'),
    remote_request_id text not null
        check (remote_request_id ~ '^trnm-settlement-remote-v1:[0-9a-f]{64}$'),
    replay_generation bigint not null check (replay_generation > 0),
    operator_id text not null
        check (btrim(operator_id) <> '' and length(operator_id) <= 256),
    change_ticket text not null
        check (change_ticket ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$'),
    reason text not null
        check (length(btrim(reason)) between 8 and 1024),
    prior_state text not null check (prior_state = 'dead_letter'),
    prior_attempts integer not null check (prior_attempts between 0 and 16),
    prior_remote_attempts integer not null check (prior_remote_attempts between 0 and 16),
    prior_last_error text check (prior_last_error is null or length(prior_last_error) <= 1024),
    policy_revision bigint not null
        references public.trnm_online_settlement_operator_policy_revisions(policy_revision)
        on delete restrict,
    authorized_at timestamptz not null default pg_catalog.clock_timestamp(),
    retain_until timestamptz not null,
    unique (job_id, replay_generation),
    check (retain_until >= authorized_at + interval '365 days')
);

create index if not exists idx_trnm_online_settlement_operator_replay_job_v1
    on public.trnm_online_settlement_operator_replay_requests(job_id, replay_generation);

create index if not exists idx_trnm_online_settlement_operator_replay_retention_v1
    on public.trnm_online_settlement_operator_replay_requests(retain_until, authorized_at);

create or replace function public.trnm_online_reject_settlement_operator_evidence_mutation_v1()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $function$
begin
    raise exception using
        errcode = '55000',
        message = 'settlement operator evidence is append-only';
end;
$function$;

drop trigger if exists trnm_online_settlement_operator_policy_no_update_delete_v1
    on public.trnm_online_settlement_operator_policy_revisions;
create trigger trnm_online_settlement_operator_policy_no_update_delete_v1
before update or delete on public.trnm_online_settlement_operator_policy_revisions
for each statement
execute function public.trnm_online_reject_settlement_operator_evidence_mutation_v1();

drop trigger if exists trnm_online_settlement_operator_policy_no_truncate_v1
    on public.trnm_online_settlement_operator_policy_revisions;
create trigger trnm_online_settlement_operator_policy_no_truncate_v1
before truncate on public.trnm_online_settlement_operator_policy_revisions
for each statement
execute function public.trnm_online_reject_settlement_operator_evidence_mutation_v1();

drop trigger if exists trnm_online_settlement_operator_replay_no_update_delete_v1
    on public.trnm_online_settlement_operator_replay_requests;
create trigger trnm_online_settlement_operator_replay_no_update_delete_v1
before update or delete on public.trnm_online_settlement_operator_replay_requests
for each statement
execute function public.trnm_online_reject_settlement_operator_evidence_mutation_v1();

drop trigger if exists trnm_online_settlement_operator_replay_no_truncate_v1
    on public.trnm_online_settlement_operator_replay_requests;
create trigger trnm_online_settlement_operator_replay_no_truncate_v1
before truncate on public.trnm_online_settlement_operator_replay_requests
for each statement
execute function public.trnm_online_reject_settlement_operator_evidence_mutation_v1();

create or replace function public.trnm_online_append_settlement_operator_policy_v1(
    p_retention_days integer,
    p_dead_letter_alert_threshold bigint,
    p_expired_lease_alert_threshold bigint,
    p_oldest_eligible_alert_seconds bigint,
    p_oldest_pending_apply_alert_seconds bigint,
    p_replay_24h_alert_threshold bigint,
    p_approved_by text,
    p_change_ticket text,
    p_reason text
)
returns bigint
language plpgsql
security invoker
set search_path = pg_catalog, public
as $function$
declare
    revision bigint;
begin
    if p_retention_days < 365 or p_retention_days > 36500
       or p_dead_letter_alert_threshold < 1
       or p_expired_lease_alert_threshold < 1
       or p_oldest_eligible_alert_seconds < 30
       or p_oldest_pending_apply_alert_seconds < 30
       or p_replay_24h_alert_threshold < 1
       or p_approved_by is null
       or btrim(p_approved_by) = ''
       or length(p_approved_by) > 256
       or p_change_ticket is null
       or p_change_ticket !~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$'
       or p_reason is null
       or length(btrim(p_reason)) < 8
       or length(p_reason) > 1024 then
        raise exception using
            errcode = '22023',
            message = 'invalid settlement operator policy revision';
    end if;

    insert into public.trnm_online_settlement_operator_policy_revisions (
        contract_version,
        retention_days,
        dead_letter_alert_threshold,
        expired_lease_alert_threshold,
        oldest_eligible_alert_seconds,
        oldest_pending_apply_alert_seconds,
        replay_24h_alert_threshold,
        approved_by,
        change_ticket,
        reason
    ) values (
        'trnm_settlement_operator_policy_v1',
        p_retention_days,
        p_dead_letter_alert_threshold,
        p_expired_lease_alert_threshold,
        p_oldest_eligible_alert_seconds,
        p_oldest_pending_apply_alert_seconds,
        p_replay_24h_alert_threshold,
        p_approved_by,
        p_change_ticket,
        p_reason
    )
    returning policy_revision into revision;
    return revision;
end;
$function$;

create or replace function public.trnm_online_authorize_settlement_replay_v1(
    p_request_id text,
    p_job_id text,
    p_capture_id text,
    p_intent_id text,
    p_intent_hash text,
    p_remote_request_id text,
    p_operator_id text,
    p_change_ticket text,
    p_reason text
)
returns boolean
language plpgsql
security invoker
set search_path = pg_catalog, public
as $function$
declare
    existing public.trnm_online_settlement_operator_replay_requests%rowtype;
    job public.trnm_online_settlement_jobs%rowtype;
    capture_state text;
    next_generation bigint;
    policy public.trnm_online_settlement_operator_policy_revisions%rowtype;
    now_at timestamptz := pg_catalog.clock_timestamp();
begin
    if p_request_id is null
       or p_request_id !~ '^trnm-settlement-replay-v1:[0-9a-f]{64}$'
       or p_job_id is null
       or btrim(p_job_id) = ''
       or p_capture_id is null
       or btrim(p_capture_id) = ''
       or p_intent_id is null
       or btrim(p_intent_id) = ''
       or p_intent_hash is null
       or p_intent_hash !~ '^[0-9a-f]{64}$'
       or p_remote_request_id is null
       or p_remote_request_id !~ '^trnm-settlement-remote-v1:[0-9a-f]{64}$'
       or p_operator_id is null
       or btrim(p_operator_id) = ''
       or length(p_operator_id) > 256
       or p_change_ticket is null
       or p_change_ticket !~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$'
       or p_reason is null
       or length(btrim(p_reason)) < 8
       or length(p_reason) > 1024 then
        raise exception using
            errcode = '22023',
            message = 'invalid settlement operator replay request';
    end if;

    select * into existing
      from public.trnm_online_settlement_operator_replay_requests
     where request_id = p_request_id;
    if found then
        if existing.job_id = p_job_id
           and existing.capture_id = p_capture_id
           and existing.intent_id = p_intent_id
           and existing.intent_hash = p_intent_hash
           and existing.remote_request_id = p_remote_request_id
           and existing.operator_id = p_operator_id
           and existing.change_ticket = p_change_ticket
           and existing.reason = p_reason then
            return true;
        end if;
        raise exception using
            errcode = '23514',
            message = 'settlement replay request identity was reused with different material';
    end if;

    select job_row.*
      into job
      from public.trnm_online_settlement_jobs job_row
      join public.trnm_online_settlement_captures capture
        on capture.capture_id = job_row.capture_id
     where job_row.job_id = p_job_id
     for update of job_row, capture;
    if not found then
        raise exception using
            errcode = 'P0002',
            message = 'settlement replay target does not exist';
    end if;

    select capture.state
      into capture_state
      from public.trnm_online_settlement_captures capture
     where capture.capture_id = job.capture_id;
    if not found then
        raise exception using
            errcode = '55000',
            message = 'settlement replay capture disappeared after lock';
    end if;

    if job.capture_id <> p_capture_id
       or job.intent_id <> p_intent_id
       or job.intent_hash <> p_intent_hash
       or job.remote_request_id <> p_remote_request_id then
        raise exception using
            errcode = '23514',
            message = 'settlement replay request failed immutable identity binding';
    end if;

    if job.state <> 'dead_letter'
       or capture_state <> 'dead_letter'
       or job.campaign_applied_at is not null
       or job.remote_completed_at is not null
       or job.receipt_id is not null
       or job.receipt_hash is not null
       or job.receipt_json is not null then
        raise exception using
            errcode = '55000',
            message = 'settlement replay is allowed only for receipt-free dead-letter work';
    end if;

    select * into policy
      from public.trnm_online_settlement_operator_policy_revisions
     order by policy_revision desc
     limit 1;
    if not found then
        raise exception using
            errcode = '55000',
            message = 'settlement operator policy is missing';
    end if;

    select coalesce(max(replay_generation), 0) + 1
      into next_generation
      from public.trnm_online_settlement_operator_replay_requests
     where job_id = p_job_id;

    insert into public.trnm_online_settlement_operator_replay_requests (
        request_id,
        contract_version,
        job_id,
        capture_id,
        intent_id,
        intent_hash,
        remote_request_id,
        replay_generation,
        operator_id,
        change_ticket,
        reason,
        prior_state,
        prior_attempts,
        prior_remote_attempts,
        prior_last_error,
        policy_revision,
        authorized_at,
        retain_until
    ) values (
        p_request_id,
        'trnm_settlement_operator_replay_v1',
        job.job_id,
        job.capture_id,
        job.intent_id,
        job.intent_hash,
        job.remote_request_id,
        next_generation,
        p_operator_id,
        p_change_ticket,
        p_reason,
        job.state,
        job.attempts,
        job.remote_attempts,
        job.last_error,
        policy.policy_revision,
        now_at,
        now_at + pg_catalog.make_interval(days => policy.retention_days)
    );

    update public.trnm_online_settlement_jobs
       set state = 'retryable',
           remote_attempts = 15,
           lease_owner = null,
           lease_expires_at = null,
           next_attempt_at = now_at,
           completed_at = null,
           failure_class = null,
           last_error = left(
               'operator replay authorized by ' || p_operator_id ||
               ' under ' || p_change_ticket,
               1024
           ),
           updated_at = now_at
     where job_id = job.job_id
       and state = 'dead_letter'
       and capture_id = job.capture_id
       and intent_id = job.intent_id
       and intent_hash = job.intent_hash
       and remote_request_id = job.remote_request_id
       and campaign_applied_at is null
       and remote_completed_at is null
       and receipt_json is null;
    if not found then
        raise exception using
            errcode = '55000',
            message = 'settlement replay lost its dead-letter fence';
    end if;

    update public.trnm_online_settlement_captures
       set state = 'active',
           last_error = null,
           applied_at = null,
           updated_at = now_at
     where capture_id = job.capture_id
       and state = 'dead_letter';
    if not found then
        raise exception using
            errcode = '55000',
            message = 'settlement replay lost its capture fence';
    end if;

    return true;
end;
$function$;

revoke all on function public.trnm_online_append_settlement_operator_policy_v1(
    integer, bigint, bigint, bigint, bigint, bigint, text, text, text
) from public;
revoke all on function public.trnm_online_authorize_settlement_replay_v1(
    text, text, text, text, text, text, text, text, text
) from public;

create or replace view public.trnm_online_settlement_operator_policy_current_v1 as
select *
  from public.trnm_online_settlement_operator_policy_revisions
 order by policy_revision desc
 limit 1;

create or replace view public.trnm_online_settlement_operator_alerts_v1 as
with policy as (
    select *
      from public.trnm_online_settlement_operator_policy_revisions
     order by policy_revision desc
     limit 1
),
replays as (
    select
        count(*) as replay_total,
        count(*) filter (
            where authorized_at >= pg_catalog.clock_timestamp() - interval '24 hours'
        ) as replay_last_24h,
        min(retain_until) as earliest_retain_until
      from public.trnm_online_settlement_operator_replay_requests
)
select
    policy.policy_revision,
    metrics.remote_dead_letter,
    metrics.expired_leases,
    metrics.remote_pending,
    metrics.remote_retryable,
    metrics.pending_apply,
    metrics.oldest_eligible_age,
    metrics.oldest_pending_apply_age,
    replays.replay_total,
    replays.replay_last_24h,
    replays.earliest_retain_until,
    policy.dead_letter_alert_threshold,
    policy.expired_lease_alert_threshold,
    policy.oldest_eligible_alert_seconds,
    policy.oldest_pending_apply_alert_seconds,
    policy.replay_24h_alert_threshold,
    metrics.remote_dead_letter >= policy.dead_letter_alert_threshold
        as dead_letter_alert,
    metrics.expired_leases >= policy.expired_lease_alert_threshold
        as expired_lease_alert,
    coalesce(
        extract(epoch from metrics.oldest_eligible_age) >=
            policy.oldest_eligible_alert_seconds,
        false
    ) as oldest_eligible_alert,
    coalesce(
        extract(epoch from metrics.oldest_pending_apply_age) >=
            policy.oldest_pending_apply_alert_seconds,
        false
    ) as pending_apply_age_alert,
    replays.replay_last_24h >= policy.replay_24h_alert_threshold
        as replay_volume_alert
from public.trnm_online_settlement_metrics_v1 metrics
cross join policy
cross join replays;

comment on function public.trnm_online_authorize_settlement_replay_v1(
    text, text, text, text, text, text, text, text, text
) is
    'Audited exact-identity replay authorization for one additional remote attempt';
comment on table public.trnm_online_settlement_operator_replay_requests is
    'Append-only operator settlement replay evidence retained under the exact policy revision';
