-- Poison-work isolation and bounded retry for the transaction-free settlement worker.
--
-- A malformed match, capture, or leased job must fail closed without blocking
-- unrelated accounts. Quarantine is durable, bounded, operator-visible, and
-- never grants remote or campaign-application success.

create unique index if not exists idx_trnm_online_settlement_job_one_campaign_per_capture_v1
    on public.trnm_online_settlement_jobs(capture_id, campaign_id)
    where capture_id is not null;

create table if not exists public.trnm_online_settlement_quarantine_v1 (
    quarantine_id bigint generated by default as identity primary key,
    contract_version text not null
        check (contract_version = 'trnm_settlement_quarantine_v1'),
    scope_kind text not null
        check (scope_kind in ('match', 'capture', 'job')),
    scope_id text not null
        check (length(btrim(scope_id)) between 1 and 256),
    phase text not null
        check (phase in ('capture', 'claim_decode', 'remote', 'apply', 'operator')),
    error_hash text not null check (error_hash ~ '^[0-9a-f]{64}$'),
    last_error text not null check (length(last_error) between 1 and 1024),
    occurrences bigint not null default 1 check (occurrences > 0),
    first_seen_at timestamptz not null default pg_catalog.clock_timestamp(),
    last_seen_at timestamptz not null default pg_catalog.clock_timestamp(),
    next_retry_at timestamptz not null,
    resolved_at timestamptz,
    resolved_by text check (
        resolved_by is null or length(btrim(resolved_by)) between 1 and 256
    ),
    change_ticket text check (
        change_ticket is null
        or change_ticket ~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$'
    ),
    resolution text check (
        resolution is null or length(btrim(resolution)) between 8 and 1024
    ),
    check (
        (resolved_at is null and resolved_by is null and change_ticket is null and resolution is null)
        or
        (resolved_at is not null and resolved_by is not null and change_ticket is not null and resolution is not null)
    )
);

create unique index if not exists idx_trnm_online_settlement_quarantine_active_v1
    on public.trnm_online_settlement_quarantine_v1(scope_kind, scope_id, phase)
    where resolved_at is null;

create index if not exists idx_trnm_online_settlement_quarantine_retry_v1
    on public.trnm_online_settlement_quarantine_v1(next_retry_at, scope_kind, scope_id)
    where resolved_at is null;

create or replace function public.trnm_online_settlement_scope_quarantined_v1(
    p_scope_kind text,
    p_scope_id text,
    p_phase text
)
returns boolean
language sql
stable
strict
security invoker
set search_path = pg_catalog, public
as $function$
    select exists (
        select 1
          from public.trnm_online_settlement_quarantine_v1 quarantine
         where quarantine.scope_kind = p_scope_kind
           and quarantine.scope_id = p_scope_id
           and quarantine.phase = p_phase
           and quarantine.resolved_at is null
           and quarantine.next_retry_at > pg_catalog.clock_timestamp()
    )
$function$;

create or replace function public.trnm_online_record_settlement_quarantine_v1(
    p_scope_kind text,
    p_scope_id text,
    p_phase text,
    p_error text,
    p_retry_after_seconds bigint
)
returns bigint
language plpgsql
security invoker
set search_path = pg_catalog, public
as $function$
declare
    now_at timestamptz := pg_catalog.clock_timestamp();
    bounded_error text;
    digest text;
    result_id bigint;
begin
    if p_scope_kind not in ('match', 'capture', 'job')
       or p_scope_id is null
       or length(btrim(p_scope_id)) not between 1 and 256
       or p_phase not in ('capture', 'claim_decode', 'remote', 'apply', 'operator')
       or p_error is null
       or btrim(p_error) = ''
       or p_retry_after_seconds < 1
       or p_retry_after_seconds > 86400 then
        raise exception using
            errcode = '22023',
            message = 'invalid settlement quarantine record';
    end if;

    bounded_error := left(p_error, 1024);
    digest := pg_catalog.encode(
        pg_catalog.sha256(pg_catalog.convert_to(bounded_error, 'UTF8')),
        'hex'
    );

    insert into public.trnm_online_settlement_quarantine_v1 (
        contract_version,
        scope_kind,
        scope_id,
        phase,
        error_hash,
        last_error,
        occurrences,
        first_seen_at,
        last_seen_at,
        next_retry_at
    ) values (
        'trnm_settlement_quarantine_v1',
        p_scope_kind,
        p_scope_id,
        p_phase,
        digest,
        bounded_error,
        1,
        now_at,
        now_at,
        now_at + pg_catalog.make_interval(secs => p_retry_after_seconds)
    )
    on conflict (scope_kind, scope_id, phase) where resolved_at is null
    do update set
        error_hash = excluded.error_hash,
        last_error = excluded.last_error,
        occurrences = public.trnm_online_settlement_quarantine_v1.occurrences + 1,
        last_seen_at = excluded.last_seen_at,
        next_retry_at = excluded.next_retry_at
    returning quarantine_id into result_id;

    return result_id;
end;
$function$;

create or replace function public.trnm_online_quarantine_claimed_settlement_job_v1(
    p_job_id text,
    p_owner text,
    p_lease_generation bigint,
    p_error text
)
returns boolean
language plpgsql
security invoker
set search_path = pg_catalog, public
as $function$
declare
    changed bigint;
    capture_identity text;
    now_at timestamptz := pg_catalog.clock_timestamp();
begin
    if p_job_id is null
       or btrim(p_job_id) = ''
       or p_owner is null
       or btrim(p_owner) = ''
       or p_lease_generation <= 0
       or p_error is null
       or btrim(p_error) = '' then
        raise exception using
            errcode = '22023',
            message = 'invalid claimed settlement quarantine request';
    end if;

    update public.trnm_online_settlement_jobs
       set state = 'dead_letter',
           failure_class = 'permanent',
           last_error = left(p_error, 1024),
           next_attempt_at = null,
           completed_at = now_at,
           lease_owner = null,
           lease_expires_at = null,
           updated_at = now_at
     where job_id = p_job_id
       and state = 'leased'
       and lease_owner = p_owner
       and lease_generation = p_lease_generation
       and lease_expires_at > now_at
     returning capture_id into capture_identity;
    get diagnostics changed = row_count;
    if changed <> 1 then
        return false;
    end if;

    perform public.trnm_online_record_settlement_quarantine_v1(
        'job',
        p_job_id,
        'claim_decode',
        p_error,
        86400
    );

    if capture_identity is not null then
        update public.trnm_online_settlement_captures
           set state = 'dead_letter',
               last_error = left(p_error, 1024),
               updated_at = now_at
         where capture_id = capture_identity
           and state = 'active';
    end if;
    return true;
end;
$function$;

create or replace function public.trnm_online_resolve_settlement_quarantine_v1(
    p_scope_kind text,
    p_scope_id text,
    p_phase text,
    p_operator_id text,
    p_change_ticket text,
    p_resolution text
)
returns boolean
language plpgsql
security invoker
set search_path = pg_catalog, public
as $function$
declare
    changed bigint;
begin
    if p_scope_kind not in ('match', 'capture', 'job')
       or p_scope_id is null
       or length(btrim(p_scope_id)) not between 1 and 256
       or p_phase not in ('capture', 'claim_decode', 'remote', 'apply', 'operator')
       or p_operator_id is null
       or length(btrim(p_operator_id)) not between 1 and 256
       or p_change_ticket is null
       or p_change_ticket !~ '^[A-Za-z0-9][A-Za-z0-9._:/-]{2,127}$'
       or p_resolution is null
       or length(btrim(p_resolution)) not between 8 and 1024 then
        raise exception using
            errcode = '22023',
            message = 'invalid settlement quarantine resolution';
    end if;

    update public.trnm_online_settlement_quarantine_v1
       set resolved_at = pg_catalog.clock_timestamp(),
           resolved_by = p_operator_id,
           change_ticket = p_change_ticket,
           resolution = p_resolution
     where scope_kind = p_scope_kind
       and scope_id = p_scope_id
       and phase = p_phase
       and resolved_at is null;
    get diagnostics changed = row_count;
    return changed = 1;
end;
$function$;

revoke all on function public.trnm_online_resolve_settlement_quarantine_v1(
    text, text, text, text, text, text
) from public;

create or replace view public.trnm_online_settlement_quarantine_status_v1 as
select
    quarantine.quarantine_id,
    quarantine.scope_kind,
    quarantine.scope_id,
    quarantine.phase,
    quarantine.error_hash,
    quarantine.last_error,
    quarantine.occurrences,
    quarantine.first_seen_at,
    quarantine.last_seen_at,
    quarantine.next_retry_at,
    quarantine.resolved_at,
    quarantine.resolved_by,
    quarantine.change_ticket,
    quarantine.resolution,
    case
        when quarantine.resolved_at is not null then 'resolved'
        when quarantine.next_retry_at > pg_catalog.clock_timestamp() then 'quarantined'
        else 'retry_eligible'
    end as status
from public.trnm_online_settlement_quarantine_v1 quarantine;
