[package]
name = "trnm-rts-bevy-runtime"
version = "0.1.0"
edition = "2021"
license = "LicenseRef-Trillionnium-Internal"
authors = ["Trillionnium Contributors"]

[dependencies]
serde = { version = "1", features = ["derive"] }
trnm-rts-core = { path = "../trnm-rts-core" }
trnm-rts-data = { path = "../trnm-rts-data" }
