// Code generated by tools/generate-trnm-world-boundary.py; DO NOT EDIT.

package fixture

const (
	DiagnosticMaxUTF8Bytes = 256
	DiagnosticFallback     = "request rejected"
)

var generatedForbiddenAuthorityKeys = map[string]struct{}{
	"authority_private_key":         {},
	"canonical_archive_root":        {},
	"chain_app_hash":                {},
	"chain_finality":                {},
	"command_idempotency_key":       {},
	"completion_signature":          {},
	"global_event_cursor":           {},
	"global_event_sequence":         {},
	"match_authority_private_key":   {},
	"match_completed_v1":            {},
	"match_version":                 {},
	"nakama_private_key":            {},
	"nakama_session_token":          {},
	"participant_admission_receipt": {},
	"participant_role":              {},
	"participant_roster":            {},
	"participant_sequence":          {},
	"settlement":                    {},
	"wallet":                        {},
}
