package fixture

import (
	"strings"
	"testing"
)

func TestGeneratedAuthorityBoundaryMatchesRuntime(t *testing.T) {
	if len(forbiddenAuthorityKeys) != len(generatedForbiddenAuthorityKeys) {
		t.Fatalf(
			"authority key count drift: runtime=%d generated=%d",
			len(forbiddenAuthorityKeys),
			len(generatedForbiddenAuthorityKeys),
		)
	}
	for key := range generatedForbiddenAuthorityKeys {
		if _, ok := forbiddenAuthorityKeys[key]; !ok {
			t.Fatalf("generated forbidden authority key is not enforced: %s", key)
		}
	}
	for key := range forbiddenAuthorityKeys {
		if _, ok := generatedForbiddenAuthorityKeys[key]; !ok {
			t.Fatalf("runtime forbidden authority key is absent from registry: %s", key)
		}
	}
}

func TestGeneratedDiagnosticBoundaryMatchesRuntime(t *testing.T) {
	value := strings.Repeat("a", DiagnosticMaxUTF8Bytes-1) + "界"
	detail := boundedDetail(value)
	if len(detail) > DiagnosticMaxUTF8Bytes || !strings.HasSuffix(detail, "a") {
		t.Fatalf(
			"bounded detail differs from generated byte ceiling: bytes=%d maximum=%d",
			len(detail),
			DiagnosticMaxUTF8Bytes,
		)
	}
	if boundedDetail("\n\r\t") != DiagnosticFallback {
		t.Fatalf("empty normalized diagnostic differs from generated fallback")
	}
}
