use super::*;

pub(crate) struct RuntimeState {
    pub(crate) cfg: NodeConfig,
    pub(crate) wal_dir: PathBuf,
    pub(crate) restored_lock: Option<String>,
    pub(crate) height: u64,
    pub(crate) state: StateStore,
    pub(crate) mempool: VecDeque<MockTx>,
    pub(crate) known_task_ids: HashSet<u64>,
    pub(crate) wal_entries: Vec<WalMeta>,
    pub(crate) checkpoints: Vec<CheckpointMeta>,
    pub(crate) bft_jitter: BftJitterControl,
}

pub(crate) struct RuntimeMetrics {
    pub(crate) finality_samples_ms: Vec<u128>,
    pub(crate) scheduler_samples_ms: Vec<u128>,
    pub(crate) preexec_samples_ms: Vec<u128>,
    pub(crate) commit_samples_ms: Vec<u128>,
    pub(crate) state_root_total_samples_ms: Vec<u128>,
    pub(crate) critical_wait_blocks_samples: Vec<u128>,
    pub(crate) critical_wait_active_heights: u64,
    pub(crate) critical_wait_total: u64,
    pub(crate) block_txs_samples: Vec<u128>,
    pub(crate) block_groups_samples: Vec<u128>,
    pub(crate) rollback_samples: Vec<u128>,
    pub(crate) avg_group_size_samples: Vec<u128>,
    pub(crate) hot_object_share_samples_ppm: Vec<u128>,
    pub(crate) hot_object_top_label_share_samples_ppm: Vec<u128>,
    pub(crate) hot_object_tail_share_samples_ppm: Vec<u128>,
    pub(crate) hot_object_active_heights: u64,
    pub(crate) hot_object_active_top_label_share_total_ppm: u128,
    pub(crate) hot_object_active_tail_share_total_ppm: u128,
    pub(crate) preexec_reject_total: u64,
    pub(crate) preexec_reject_active_heights: u64,
    pub(crate) apply_error_total: u64,
    pub(crate) apply_error_preexec_conflict_miss_total: u64,
    pub(crate) apply_error_version_conflict_total: u64,
    pub(crate) apply_error_invalid_transition_total: u64,
    pub(crate) apply_error_deadline_exceeded_total: u64,
    pub(crate) apply_error_semantic_fail_total: u64,
    pub(crate) rollback_total: u64,
    pub(crate) rollback_block_total: u64,
    pub(crate) timeout_migrated_total: u64,
    pub(crate) bft_observed_heights: u64,
    pub(crate) bft_committed_heights: u64,
    pub(crate) bft_round_change_total: u64,
    pub(crate) bft_round_change_active_heights: u64,
    pub(crate) bft_round_change_backoff_active_heights: u64,
    pub(crate) bft_double_vote_total: u64,
    pub(crate) bft_auth_reject_bad_sig_total: u64,
    pub(crate) bft_auth_reject_replay_total: u64,
    pub(crate) bft_auth_reject_stale_nonce_total: u64,
    pub(crate) bft_round_change_backoff_total_ms: u64,
    pub(crate) bft_round_change_backoff_max_ms: u64,
    pub(crate) bft_leader_missed_active_heights: u64,
    pub(crate) bft_leader_missed_previous_snapshot: Vec<u64>,
}

impl RuntimeMetrics {
    pub(crate) fn new(validators: usize) -> Self {
        Self {
            finality_samples_ms: Vec::new(),
            scheduler_samples_ms: Vec::new(),
            preexec_samples_ms: Vec::new(),
            commit_samples_ms: Vec::new(),
            state_root_total_samples_ms: Vec::new(),
            critical_wait_blocks_samples: Vec::new(),
            critical_wait_active_heights: 0,
            critical_wait_total: 0,
            block_txs_samples: Vec::new(),
            block_groups_samples: Vec::new(),
            rollback_samples: Vec::new(),
            avg_group_size_samples: Vec::new(),
            hot_object_share_samples_ppm: Vec::new(),
            hot_object_top_label_share_samples_ppm: Vec::new(),
            hot_object_tail_share_samples_ppm: Vec::new(),
            hot_object_active_heights: 0,
            hot_object_active_top_label_share_total_ppm: 0,
            hot_object_active_tail_share_total_ppm: 0,
            preexec_reject_total: 0,
            preexec_reject_active_heights: 0,
            apply_error_total: 0,
            apply_error_preexec_conflict_miss_total: 0,
            apply_error_version_conflict_total: 0,
            apply_error_invalid_transition_total: 0,
            apply_error_deadline_exceeded_total: 0,
            apply_error_semantic_fail_total: 0,
            rollback_total: 0,
            rollback_block_total: 0,
            timeout_migrated_total: 0,
            bft_observed_heights: 0,
            bft_committed_heights: 0,
            bft_round_change_total: 0,
            bft_round_change_active_heights: 0,
            bft_round_change_backoff_active_heights: 0,
            bft_double_vote_total: 0,
            bft_auth_reject_bad_sig_total: 0,
            bft_auth_reject_replay_total: 0,
            bft_auth_reject_stale_nonce_total: 0,
            bft_round_change_backoff_total_ms: 0,
            bft_round_change_backoff_max_ms: 0,
            bft_leader_missed_active_heights: 0,
            bft_leader_missed_previous_snapshot: vec![0; validators.max(1)],
        }
    }
}
