use super::*;

#[test]
fn fairness_deferral_does_not_evict_older_retries_from_bounded_memory() {
    let mut gate = AdmissionGate::new(2);
    assert_eq!(gate.admit(1), AdmitOutcome::Accepted);
    assert_eq!(gate.admit(2), AdmitOutcome::Accepted);
    assert_eq!(gate.admit(9), AdmitOutcome::Backpressured);
    assert_eq!(gate.admit(10), AdmitOutcome::Backpressured);

    assert_eq!(gate.pop_ready(), Some(1));
    assert_eq!(gate.admit(3), AdmitOutcome::Backpressured);

    // Deferring fresh ingress should not evict long-waiting retries from fairness tracking.
    assert!(gate.backpressured_ids.contains(&9));
    assert!(gate.backpressured_ids.contains(&10));
    assert!(!gate.backpressured_ids.contains(&3));
}

#[test]
fn repeated_fairness_deferral_of_same_fresh_id_is_idempotent() {
    let mut gate = AdmissionGate::new(4);
    for tx_id in 1..=4 {
        assert_eq!(gate.admit(tx_id), AdmitOutcome::Accepted);
    }
    // Fill bounded retry memory to capacity.
    assert_eq!(gate.admit(9), AdmitOutcome::Backpressured);
    assert_eq!(gate.admit(10), AdmitOutcome::Backpressured);
    assert_eq!(gate.admit(11), AdmitOutcome::Backpressured);
    assert_eq!(gate.admit(12), AdmitOutcome::Backpressured);

    // Open two slots to create a multi-step fairness reservation window.
    assert_eq!(gate.pop_ready(), Some(1));
    assert_eq!(gate.pop_ready(), Some(2));

    // Fresh id=20 is deferred while retry memory is full, so it cannot be
    // remembered in backpressured_ids and should dedupe via last_fairness_deferred.
    assert_eq!(gate.admit(20), AdmitOutcome::Backpressured);
    assert_eq!(gate.admit(20), AdmitOutcome::Duplicate);

    let m = gate.metrics();
    assert_eq!(m.backpressured, 5);
    assert_eq!(m.fairness_deferrals, 1);
    assert_eq!(m.duplicates, 1);
}

#[test]
fn repeated_single_slot_fairness_deferral_stays_idempotent() {
    let mut gate = AdmissionGate::new(2);
    assert_eq!(gate.admit(1), AdmitOutcome::Accepted);
    assert_eq!(gate.admit(2), AdmitOutcome::Accepted);

    // One known retry + one freed slot => a single fairness reservation.
    assert_eq!(gate.admit(9), AdmitOutcome::Backpressured);
    assert_eq!(gate.pop_ready(), Some(1));

    // First fresh ingress is deferred; immediate repeat must dedupe instead of
    // being accepted and stealing the reserved slot from retry traffic.
    assert_eq!(gate.admit(10), AdmitOutcome::Backpressured);
    assert_eq!(gate.admit(10), AdmitOutcome::Duplicate);

    // The reserved slot remains available for known retry.
    assert_eq!(gate.admit(9), AdmitOutcome::Accepted);

    let m = gate.metrics();
    assert_eq!(m.fairness_deferrals, 1);
    assert_eq!(m.duplicates, 1);
}

#[test]
fn fairness_deferral_duplicate_increments_backpressure_duplicate_metric() {
    let mut gate = AdmissionGate::new(2);
    assert_eq!(gate.admit(1), AdmitOutcome::Accepted);
    assert_eq!(gate.admit(2), AdmitOutcome::Accepted);

    // Seed one known retry so fresh ingress is fairness-deferred after a pop.
    assert_eq!(gate.admit(9), AdmitOutcome::Backpressured);
    assert_eq!(gate.pop_ready(), Some(1));

    assert_eq!(gate.admit(10), AdmitOutcome::Backpressured);
    assert_eq!(gate.admit(10), AdmitOutcome::Duplicate);

    // Duplicate generated by fairness-idempotency is still a backpressure-
    // induced retry signal and should be reflected in backpressure telemetry.
    let m = gate.metrics();
    assert_eq!(m.fairness_deferrals, 1);
    assert_eq!(m.duplicates, 1);
    assert_eq!(m.backpressure_duplicates, 1);
}

#[test]
fn fairness_deferred_repeat_stays_duplicate_after_queue_resaturates() {
    let mut gate = AdmissionGate::new(2);
    assert_eq!(gate.admit(1), AdmitOutcome::Accepted);
    assert_eq!(gate.admit(2), AdmitOutcome::Accepted);

    // One known retry => one fairness reservation after a pop.
    assert_eq!(gate.admit(9), AdmitOutcome::Backpressured);
    assert_eq!(gate.pop_ready(), Some(1));

    // Fresh id is fairness-deferred.
    assert_eq!(gate.admit(10), AdmitOutcome::Backpressured);
    // Queue re-saturates before sender retries deferred id.
    assert_eq!(gate.admit(1), AdmitOutcome::Accepted);
    // Immediate repeat should still dedupe instead of churning retry cache.
    assert_eq!(gate.admit(10), AdmitOutcome::Duplicate);

    let m = gate.metrics();
    assert_eq!(m.fairness_deferrals, 1);
    assert_eq!(m.duplicates, 1);
    assert_eq!(m.backpressure_duplicates, 1);
}
