use super::*;

#[path = "summary_stats/distributions.rs"]
mod distributions;
use distributions::fill_distribution_stats;

#[path = "summary_stats/ratios.rs"]
mod ratios;
use ratios::fill_ratio_stats;

#[path = "summary_stats/bft.rs"]
mod bft;
use bft::fill_bft_stats;

pub(crate) struct RuntimeSummaryStats {
    pub(crate) finality_p50: u128,
    pub(crate) finality_p95: u128,
    pub(crate) scheduler_p50: u128,
    pub(crate) scheduler_p95: u128,
    pub(crate) preexec_p50: u128,
    pub(crate) preexec_p95: u128,
    pub(crate) commit_p50: u128,
    pub(crate) commit_p95: u128,
    pub(crate) state_root_total_p50: u128,
    pub(crate) state_root_total_p95: u128,
    pub(crate) critical_wait_blocks_p50: u128,
    pub(crate) critical_wait_blocks_p95: u128,
    pub(crate) block_txs_p50: u128,
    pub(crate) block_txs_p95: u128,
    pub(crate) block_groups_p50: u128,
    pub(crate) block_groups_p95: u128,
    pub(crate) rollback_p50: u128,
    pub(crate) rollback_p95: u128,
    pub(crate) avg_group_size_p50: u128,
    pub(crate) avg_group_size_p95: u128,
    pub(crate) hot_object_share_p50_ppm: u128,
    pub(crate) hot_object_share_p95_ppm: u128,
    pub(crate) hot_object_top_label_share_p50_ppm: u128,
    pub(crate) hot_object_top_label_share_p95_ppm: u128,
    pub(crate) hot_object_tail_share_p50_ppm: u128,
    pub(crate) hot_object_tail_share_p95_ppm: u128,
    pub(crate) finality_max: u128,
    pub(crate) scheduler_max: u128,
    pub(crate) preexec_max: u128,
    pub(crate) commit_max: u128,
    pub(crate) state_root_total_max: u128,
    pub(crate) critical_wait_blocks_max: u128,
    pub(crate) block_txs_max: u128,
    pub(crate) block_groups_max: u128,
    pub(crate) rollback_max: u128,
    pub(crate) avg_group_size_max: u128,
    pub(crate) hot_object_share_max_ppm: u128,
    pub(crate) hot_object_top_label_share_max_ppm: u128,
    pub(crate) hot_object_tail_share_max_ppm: u128,
    pub(crate) finality_avg: u128,
    pub(crate) scheduler_avg: u128,
    pub(crate) preexec_avg: u128,
    pub(crate) commit_avg: u128,
    pub(crate) state_root_total_avg: u128,
    pub(crate) critical_wait_blocks_avg: u128,
    pub(crate) rollback_avg: u128,
    pub(crate) avg_group_size_avg: u128,
    pub(crate) hot_object_share_avg_ppm: u128,
    pub(crate) hot_object_top_label_share_avg_ppm: u128,
    pub(crate) hot_object_tail_share_avg_ppm: u128,
    pub(crate) hot_object_active_top_label_share_avg_ppm: u128,
    pub(crate) hot_object_active_tail_share_avg_ppm: u128,
    pub(crate) hot_object_active_height_rate_ppm: u128,
    pub(crate) hot_object_active_observed_height_rate_ppm: u128,
    pub(crate) hot_object_active_height_share_ppm: u128,
    pub(crate) scheduler_share_avg_ppm: u128,
    pub(crate) scheduler_peak_share_ppm: u128,
    pub(crate) preexec_share_avg_ppm: u128,
    pub(crate) commit_share_avg_ppm: u128,
    pub(crate) commit_peak_share_ppm: u128,
    pub(crate) state_root_total_share_avg_ppm: u128,
    pub(crate) state_root_total_peak_share_ppm: u128,
    pub(crate) rollback_share_avg_ppm: u128,
    pub(crate) rollback_peak_share_ppm: u128,
    pub(crate) preexec_peak_share_ppm: u128,
    pub(crate) rollback_block_rate_ppm: u128,
    pub(crate) rollback_active_heights: u64,
    pub(crate) rollback_active_height_rate_ppm: u128,
    pub(crate) rollback_active_observed_height_rate_ppm: u128,
    pub(crate) rollback_density_avg: u64,
    pub(crate) rollback_density_avg_milli: u128,
    pub(crate) rollback_active_height_share_ppm: u128,
    pub(crate) preexec_conflict_miss_share_bps: u128,
    pub(crate) preexec_reject_density_avg: u64,
    pub(crate) preexec_reject_density_avg_milli: u128,
    pub(crate) preexec_reject_active_height_rate_ppm: u128,
    pub(crate) preexec_reject_active_observed_height_rate_ppm: u128,
    pub(crate) preexec_reject_active_height_share_ppm: u128,
    pub(crate) apply_error_rollback_share_bps: u128,
    pub(crate) rollback_block_rate: f64,
    pub(crate) critical_wait_density_ppm: u128,
    pub(crate) critical_wait_peak_density_ppm: u128,
    pub(crate) critical_wait_active_height_rate_ppm: u128,
    pub(crate) critical_wait_active_observed_height_rate_ppm: u128,
    pub(crate) critical_wait_density_avg: u64,
    pub(crate) critical_wait_density_avg_milli: u128,
    pub(crate) critical_wait_active_height_share_ppm: u128,
    pub(crate) preexec_reject_share_bps: u128,
    pub(crate) unprofiled_finality_share_bps: u128,
    pub(crate) bft_round_change_per_height_ppm: u128,
    pub(crate) bft_round_change_active_height_rate_ppm: u128,
    pub(crate) bft_round_change_active_observed_height_rate_ppm: u128,
    pub(crate) bft_round_change_density_avg: u64,
    pub(crate) bft_round_change_density_avg_milli: u128,
    pub(crate) bft_round_change_active_height_share_ppm: u128,
    pub(crate) bft_round_change_backoff_avg_ms: u64,
    pub(crate) bft_round_change_backoff_active_height_rate_ppm: u128,
    pub(crate) bft_round_change_backoff_active_observed_height_rate_ppm: u128,
    pub(crate) bft_round_change_backoff_density_avg_ms: u64,
    pub(crate) bft_round_change_backoff_density_avg_milli: u128,
    pub(crate) bft_round_change_backoff_active_height_share_ppm: u128,
    pub(crate) bft_round_change_backoff_wall_share_ppm: u128,
    pub(crate) bft_round_change_backoff_share_ppm: u128,
    pub(crate) bft_commit_observed_height_rate_ppm: u128,
    pub(crate) bft_skipped_height_total: u64,
    pub(crate) bft_skipped_observed_height_rate_ppm: u128,
    pub(crate) recovery_error_rate: f64,
    pub(crate) leader_missed_final: Vec<u64>,
    pub(crate) bft_leader_missed_total: u64,
    pub(crate) bft_leader_missed_max: u64,
    pub(crate) bft_leader_missed_top_share_ppm: u128,
    pub(crate) bft_leader_missed_active_validators: u64,
    pub(crate) bft_leader_missed_active_validator_share_ppm: u128,
    pub(crate) bft_leader_missed_active_height_rate_ppm: u128,
    pub(crate) bft_leader_missed_active_observed_height_rate_ppm: u128,
    pub(crate) bft_leader_missed_density_avg: u64,
    pub(crate) bft_leader_missed_density_avg_milli: u128,
    pub(crate) bft_leader_missed_active_height_share_ppm: u128,
}

impl RuntimeSummaryStats {
    fn zeroed() -> Self {
        Self {
            finality_p50: 0,
            finality_p95: 0,
            scheduler_p50: 0,
            scheduler_p95: 0,
            preexec_p50: 0,
            preexec_p95: 0,
            commit_p50: 0,
            commit_p95: 0,
            state_root_total_p50: 0,
            state_root_total_p95: 0,
            critical_wait_blocks_p50: 0,
            critical_wait_blocks_p95: 0,
            block_txs_p50: 0,
            block_txs_p95: 0,
            block_groups_p50: 0,
            block_groups_p95: 0,
            rollback_p50: 0,
            rollback_p95: 0,
            avg_group_size_p50: 0,
            avg_group_size_p95: 0,
            hot_object_share_p50_ppm: 0,
            hot_object_share_p95_ppm: 0,
            hot_object_top_label_share_p50_ppm: 0,
            hot_object_top_label_share_p95_ppm: 0,
            hot_object_tail_share_p50_ppm: 0,
            hot_object_tail_share_p95_ppm: 0,
            finality_max: 0,
            scheduler_max: 0,
            preexec_max: 0,
            commit_max: 0,
            state_root_total_max: 0,
            critical_wait_blocks_max: 0,
            block_txs_max: 0,
            block_groups_max: 0,
            rollback_max: 0,
            avg_group_size_max: 0,
            hot_object_share_max_ppm: 0,
            hot_object_top_label_share_max_ppm: 0,
            hot_object_tail_share_max_ppm: 0,
            finality_avg: 0,
            scheduler_avg: 0,
            preexec_avg: 0,
            commit_avg: 0,
            state_root_total_avg: 0,
            critical_wait_blocks_avg: 0,
            rollback_avg: 0,
            avg_group_size_avg: 0,
            hot_object_share_avg_ppm: 0,
            hot_object_top_label_share_avg_ppm: 0,
            hot_object_tail_share_avg_ppm: 0,
            hot_object_active_top_label_share_avg_ppm: 0,
            hot_object_active_tail_share_avg_ppm: 0,
            hot_object_active_height_rate_ppm: 0,
            hot_object_active_observed_height_rate_ppm: 0,
            hot_object_active_height_share_ppm: 0,
            scheduler_share_avg_ppm: 0,
            scheduler_peak_share_ppm: 0,
            preexec_share_avg_ppm: 0,
            commit_share_avg_ppm: 0,
            commit_peak_share_ppm: 0,
            state_root_total_share_avg_ppm: 0,
            state_root_total_peak_share_ppm: 0,
            rollback_share_avg_ppm: 0,
            rollback_peak_share_ppm: 0,
            preexec_peak_share_ppm: 0,
            rollback_block_rate_ppm: 0,
            rollback_active_heights: 0,
            rollback_active_height_rate_ppm: 0,
            rollback_active_observed_height_rate_ppm: 0,
            rollback_density_avg: 0,
            rollback_density_avg_milli: 0,
            rollback_active_height_share_ppm: 0,
            preexec_conflict_miss_share_bps: 0,
            preexec_reject_density_avg: 0,
            preexec_reject_density_avg_milli: 0,
            preexec_reject_active_height_rate_ppm: 0,
            preexec_reject_active_observed_height_rate_ppm: 0,
            preexec_reject_active_height_share_ppm: 0,
            apply_error_rollback_share_bps: 0,
            rollback_block_rate: 0.0,
            critical_wait_density_ppm: 0,
            critical_wait_peak_density_ppm: 0,
            critical_wait_active_height_rate_ppm: 0,
            critical_wait_active_observed_height_rate_ppm: 0,
            critical_wait_density_avg: 0,
            critical_wait_density_avg_milli: 0,
            critical_wait_active_height_share_ppm: 0,
            preexec_reject_share_bps: 0,
            unprofiled_finality_share_bps: 0,
            bft_round_change_per_height_ppm: 0,
            bft_round_change_active_height_rate_ppm: 0,
            bft_round_change_active_observed_height_rate_ppm: 0,
            bft_round_change_density_avg: 0,
            bft_round_change_density_avg_milli: 0,
            bft_round_change_active_height_share_ppm: 0,
            bft_round_change_backoff_avg_ms: 0,
            bft_round_change_backoff_active_height_rate_ppm: 0,
            bft_round_change_backoff_active_observed_height_rate_ppm: 0,
            bft_round_change_backoff_density_avg_ms: 0,
            bft_round_change_backoff_density_avg_milli: 0,
            bft_round_change_backoff_active_height_share_ppm: 0,
            bft_round_change_backoff_wall_share_ppm: 0,
            bft_round_change_backoff_share_ppm: 0,
            bft_commit_observed_height_rate_ppm: 0,
            bft_skipped_height_total: 0,
            bft_skipped_observed_height_rate_ppm: 0,
            recovery_error_rate: 0.0,
            leader_missed_final: Vec::new(),
            bft_leader_missed_total: 0,
            bft_leader_missed_max: 0,
            bft_leader_missed_top_share_ppm: 0,
            bft_leader_missed_active_validators: 0,
            bft_leader_missed_active_validator_share_ppm: 0,
            bft_leader_missed_active_height_rate_ppm: 0,
            bft_leader_missed_active_observed_height_rate_ppm: 0,
            bft_leader_missed_density_avg: 0,
            bft_leader_missed_density_avg_milli: 0,
            bft_leader_missed_active_height_share_ppm: 0,
        }
    }
}

pub(crate) fn collect_runtime_summary_stats(
    runtime: &RuntimeState,
    metrics: &RuntimeMetrics,
) -> RuntimeSummaryStats {
    let mut stats = RuntimeSummaryStats::zeroed();
    fill_distribution_stats(&mut stats, metrics);
    fill_ratio_stats(&mut stats, metrics);
    fill_bft_stats(&mut stats, runtime, metrics);
    stats
}
