#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_bevy_classic_rts_live_input_sequence.sh"
SOURCE="$ROOT/trillionnium/crates/trnm-world-bevy/src/lib.rs"
MAIN="$ROOT/trillionnium/crates/trnm-world-bevy/src/main.rs"
READINESS="$ROOT/scripts/check_trillionnium_world_bevy_classic_playtest_readiness.sh"

required_script_lines=(
  'trillionnium_world_bevy_classic_rts_live_input_sequence_v1'
  'bevy-classic-rts-live-input-sequence.json'
  'bevy-classic-rts-live-input-sequence.ppm'
  'classic-rts-live-input-sequence'
  'input_path == "apply_live_native_action_with_source(classic_rts_live_input)"'
  'accepted_input_count == 10'
  'RTS:SELECT:1'
  'RTS:QUEUE:train:guard'
  'RTS:MOVE:7,4:diamond'
  'RTS:MOVE:9,4:shift_waypoint'
  'RTS:MOVE:6,5:hold'
  'RTS:MOVE:9,4:patrol'
  'RTS:MOVE:10,3:attack_move'
  'RTS:MOVE:10,3:stop'
  'RTS:ATTACK:arena_creep_attack'
  'RTS:ABILITY:focus_fire'
  'queue_path_preview_stage == "shift_waypoints"'
  'queue_path_preview_stage == "queue_stack"'
  'queue_path_preview_stage == "rally_chain"'
  'queue_path_preview_stage == "attack_focus"'
  'queue_path_preview_stage == "cancel_repath"'
  'queue_path_preview_renderer_path == "classic_draw_scene+classic_draw_rts_command_queue_path_preview_overlay"'
  'live_command_queue_path_preview_slot_pixel_count > 1200'
  'live_command_queue_path_preview_path_pixel_count > 400'
  'live_command_queue_path_preview_waypoint_pixel_count > 200'
  'live_command_queue_path_preview_target_pixel_count > 80'
  'live_command_queue_path_preview_cancel_pixel_count > 80'
  'live_command_queue_path_preview_shift_waypoints_gate == true'
  'live_command_queue_path_preview_queue_stack_gate == true'
  'live_command_queue_path_preview_rally_chain_gate == true'
  'live_command_queue_path_preview_attack_focus_gate == true'
  'live_command_queue_path_preview_cancel_repath_gate == true'
  'live_command_queue_path_preview_gate == true'
  'feedback:train_queued:guard'
  'feedback:waypoint_queued@9,4'
  'feedback:hold_position@6,5'
  'feedback:patrol_route@9,4'
  'feedback:attack_move@10,3:'
  'feedback:stop_hold@10,3'
  'hover_preview_pixel_count > 40'
  'context_cursor_pixel_count > 80'
  'viewport_world_input_sample.shifted_tile_id == "21,19"'
  'viewport_world_input_gate == true'
  'drag_select_preview_pixel_count > 80'
  'command_stamp_pixel_count > 120'
  'MAP MOVE SENT 7,4'
  'MAP ATTACK SENT ARENA CREEP ATTACK'
  'COMMAND ABILITY SENT FOCUS FIRE'
  'final_command_stamp_player_label == "COMMAND ABILITY SENT FOCUS FIRE"'
  '.drag_select_preview_samples | length == 1'
  'classic_rts_mouse_drag'
  'DRAG SELECT 2 UNITS 2,2->6,4'
  'drag_select_commit_selection_marker_pixel_count > 250'
  'drag_select_commit_stamp_pixel_count > 80'
  'DRAG SELECT SENT 2 UNITS'
  'drag_select_filter_selection_marker_pixel_count > 400'
  'drag_select_filter_stamp_pixel_count > 80'
  'RTS:SELECT:drag:2,2->10,5'
  'DRAG SELECT 5 UNITS 2,2->10,5'
  'square_creep_wander'
  'DRAG SELECT SENT 5 UNITS'
  'drag_select_filter_gate == true'
  'unit_click_select_marker_pixel_count > 80'
  'unit_click_select_stamp_pixel_count > 80'
  'RTS:SELECT:unit:player'
  'unit_selected:player@5,4'
  'unit_select:player@5,4'
  'MAP SELECT SENT 1 UNIT'
  'selection_clear_stamp_pixel_count > 80'
  'selection_clear_command_disabled_pixel_count > 500'
  'selection_clear_residual_marker_pixel_count < 80'
  'RTS:SELECT:clear:empty@4,3'
  'selection_cleared:empty@4,3'
  'selection_clear:empty@4,3'
  'MAP SELECTION CLEARED'
  'RTS:SELECT:clear:hostile:square_creep_wander@9,4'
  'selection_cleared:hostile:square_creep_wander@9,4'
  'selection_clear:hostile:square_creep_wander@9,4'
  'MAP SELECTION CLEARED HOSTILE'
  'selection_clear_gate == true'
  'right_click_target_attack_marker_pixel_count > 20'
  'right_click_target_stamp_pixel_count > 80'
  'right_click_target_selection_marker_pixel_count > 120'
  'right_click_target_hover_sample.action_label == "RTS:ATTACK:square_creep_wander"'
  'right_click_target_hover_sample.target_preview_kind == "attack"'
  'right_click_target_hover_sample.target_preview_attack_pixel_count > 80'
  'right_click_target_hover_sample.target_preview_path_pixel_count > 80'
  'MAP ATTACK READY SQUARE CREEP WANDER'
  'MAP CURSOR ATTACK READY'
  'right_click_target_sample.stage == "drag_filter_then_right_click_hostile"'
  'right_click_target_sample.action_label == "RTS:ATTACK:square_creep_wander"'
  'right_click_target_sample.command_destination_tile == "9,4"'
  'target_acquired:square_creep_wander'
  'attack:square_creep_wander'
  'MAP ATTACK SENT SQUARE CREEP WANDER'
  'right_click_target_attack_gate == true'
  'right_click_target_samples | length == 4'
  'right_click_target_hover_samples | length == 4'
  'right_click_target_preview_path_pixel_count > 300'
  'right_click_target_preview_attack_pixel_count > 80'
  'right_click_target_preview_follow_pixel_count > 80'
  'right_click_target_preview_harvest_pixel_count > 80'
  'right_click_target_preview_gate == true'
  'right_click_execution_feedback_frame_pixel_count > 800'
  'right_click_execution_feedback_path_pixel_count > 300'
  'right_click_execution_feedback_target_pixel_count > 80'
  'right_click_execution_feedback_follow_pixel_count > 80'
  'right_click_execution_feedback_harvest_pixel_count > 80'
  'right_click_execution_feedback_viewport_marker_pixel_count > 500'
  'right_click_execution_feedback_label_pixel_count > 700'
  'right_click_execution_feedback_player_label_gate == true'
  'execution_feedback_player_label == "MOVE EXECUTING 4,3"'
  'execution_feedback_player_label == "ATTACK FOCUS SQUARE CREEP WANDER"'
  'execution_feedback_player_label == "FOLLOWING PLAYER"'
  'execution_feedback_player_label == "HARVEST GOLD VEIN TO TOWN HALL"'
  'execution_feedback_label_pixel_count > 160'
  'execution_feedback_kind == "move"'
  'execution_feedback_kind == "attack"'
  'execution_feedback_kind == "follow"'
  'execution_feedback_kind == "harvest"'
  'execution_feedback_renderer_path == "classic_draw_scene+classic_draw_rts_command_execution_feedback_overlay"'
  'execution_feedback_dropoff_structure_id == "town_hall"'
  'right_click_execution_feedback_gate == true'
  'RTS:MOVE:4,3:line'
  'MAP MOVE SENT 4,3'
  'RTS:MOVE:5,4:follow:player'
  'MAP FOLLOW READY PLAYER'
  'follow:player@5,4'
  'feedback:follow@5,4:player'
  'MAP FOLLOW SENT PLAYER'
  'RTS:QUEUE:harvest:gold_vein'
  'MAP HARVEST READY GOLD VEIN'
  'harvest:gold_vein->town_hall'
  'feedback:harvest_assigned:gold_vein'
  'MAP HARVEST SENT GOLD VEIN 3,3'
  'right_click_target_move_gate == true'
  'right_click_target_follow_gate == true'
  'right_click_target_harvest_gate == true'
  'right_click_target_preview_gate == true'
  'right_click_target_semantics_gate == true'
  'unit_shift_select_marker_pixel_count > 80'
  'unit_shift_select_stamp_pixel_count > 80'
  'RTS:SELECT:shift:unit:square_guard_patrol'
  'unit_shift_added:square_guard_patrol@7,5:count:2'
  'unit_shift_add:square_guard_patrol@7,5'
  'MAP SHIFT SELECT SENT 2 UNITS'
  'RTS:SELECT:shift:unit:player'
  'unit_shift_removed:player@5,4:count:1'
  'unit_shift_remove:player@5,4'
  'MAP SHIFT SELECT SENT 1 UNIT'
  'unit_double_click_select_marker_pixel_count > 80'
  'unit_double_click_select_stamp_pixel_count > 80'
  'RTS:SELECT:double:unit:player'
  'unit_double_selected:guard:count:3'
  'unit_double_select:guard:player|square_guard_front|square_guard_patrol'
  'MAP DOUBLE SELECT SENT 3 UNITS'
  'control_group_hotkey_marker_pixel_count > 80'
  'control_group_hotkey_stamp_pixel_count > 80'
  'control_group_slot_pixel_count > 20'
  'control_group_slot_visual_gate == true'
  'RTS:SELECT:assign:5'
  'group_5_assigned:2units'
  'control_group_assign:5:player|square_guard_patrol'
  '.control_group_slot_summaries | length == 10'
  'HOTKEY GROUP 5 ASSIGNED 2 UNITS'
  'RTS:SELECT:recall:5'
  'group_5_recalled:2units'
  'control_group_recall:5:player|square_guard_patrol'
  'HOTKEY GROUP 5 RECALLED 2 UNITS'
  'RTS:SELECT:camera:5'
  'camera_snap:group_5'
  'control_group_camera:5@5,4'
  'HOTKEY GROUP 5 CAMERA SNAP'
  'drag_select_preview_gate == true'
  'drag_select_commit_gate == true'
  'unit_click_select_gate == true'
  'unit_shift_select_gate == true'
  'control_group_hotkey_gate == true'
  'control_group_slot_visual_gate == true'
  '.hover_samples | length == 4'
  'MAP MOVE READY 4,3'
  'SIDEBAR QUEUE READY WATCH TOWER'
  'COMMAND BAR ABILITY READY'
  'MINIMAP RALLY READY 5,2'
  'MAP CURSOR MOVE READY'
  'SIDEBAR CURSOR BUILD READY'
  'COMMAND BAR CURSOR ABILITY READY'
  'MINIMAP CURSOR RALLY READY'
  'final_hover_source == "classic_rts_mouse_minimap"'
  'final_context_cursor_player_label == "MINIMAP CURSOR RALLY READY"'
  'hover_preview_gate == true'
  'context_cursor_gate == true'
  'viewport_world_input_gate == true'
  'command_stamp_gate == true'
  'live_input_gate == true'
  'selection_live_gate == true'
  'production_live_gate == true'
  'production_feedback_chip_gate == true'
  'move_live_gate == true'
  'waypoint_live_gate == true'
  'hold_live_gate == true'
  'patrol_live_gate == true'
  'attack_move_live_gate == true'
  'stop_live_gate == true'
  'attack_live_gate == true'
  'ability_live_gate == true'
  'command_feedback_chip_gate == true'
)

for line in "${required_script_lines[@]}"; do
  if ! grep -Fq "$line" "$SCRIPT"; then
    echo "[FAIL] missing classic RTS live input script line: $line" >&2
    exit 1
  fi
done

required_source_lines=(
  'TRILLIONNIUM_WORLD_BEVY_CLASSIC_RTS_LIVE_INPUT_SEQUENCE_CONTRACT'
  'native_classic_rts_live_input_sequence_evidence_json'
  'classic-rts-live-input-sequence'
  'RtsSelectControlGroup'
  'RtsQueueProduction'
  'RtsMoveCommand'
  'RtsAttackCommand'
  'RtsAbilityCommand'
  'apply_live_native_action_with_source'
  'classic_rts_live_input'
  'apply_classic_rts_select_group_runtime'
  'apply_classic_rts_queue_runtime'
  'apply_classic_rts_move_runtime'
  'apply_classic_rts_attack_runtime'
  'apply_classic_rts_ability_runtime'
  'selection_live_gate'
  'production_live_gate'
  'production_feedback_chip_gate'
  'move_live_gate'
  'waypoint_live_gate'
  'hold_live_gate'
  'patrol_live_gate'
  'attack_move_live_gate'
  'stop_live_gate'
  'attack_live_gate'
  'ability_live_gate'
  'command_feedback_chip_gate'
  'command_feedback_chip_count'
  'classic_rts_command_queue_path_preview_stage'
  'classic_draw_rts_command_queue_path_preview_overlay'
  'CLASSIC_RTS_QUEUE_PREVIEW_SLOT_COLOR'
  'CLASSIC_RTS_QUEUE_PREVIEW_PATH_COLOR'
  'CLASSIC_RTS_QUEUE_PREVIEW_WAYPOINT_COLOR'
  'CLASSIC_RTS_QUEUE_PREVIEW_TARGET_COLOR'
  'CLASSIC_RTS_QUEUE_PREVIEW_CANCEL_COLOR'
  'queue_path_preview_renderer_path'
  'live_command_queue_path_preview_gate'
  'live_command_queue_path_preview_shift_waypoints_gate'
  'live_command_queue_path_preview_queue_stack_gate'
  'live_command_queue_path_preview_rally_chain_gate'
  'live_command_queue_path_preview_attack_focus_gate'
  'live_command_queue_path_preview_cancel_repath_gate'
  'ClassicRtsHoverPreview'
  'ClassicRtsDragSelectPreview'
  'ClassicRtsCommandStamp'
  'rts_cursor_player_label'
  'classic_rts_drag_select_preview_from_points'
  'apply_classic_rts_drag_select_preview_runtime'
  'classic_draw_rts_drag_select_preview_overlay'
  'drag_select_commit_gate'
  'drag_select_commit_sample'
  'drag_select_filter_gate'
  'drag_select_filter_sample'
  'classic_rts_selectable_unit_entries'
  'classic_rts_unit_is_player_owned'
  'classic_rts_unit_selection_priority'
  'classic_rts_drag_rejected_unit_ids'
  'classic_rts_selectable_unit_at_tile'
  'classic_rts_selectable_unit_tile'
  'classic_rts_selection_tiles_for_units'
  'classic_rts_mouse_action_with_source_from_point_with_shift'
  'classic_rts_mouse_action_with_source_from_point_with_modifiers'
  'classic_rts_same_class_units'
  'unit_click_select_gate'
  'unit_click_select_sample'
  'classic_rts_selection_clear_parts'
  'selection_clear_gate'
  'selection_clear_samples'
  'CLASSIC_RTS_COMMAND_DISABLED_COLOR'
  'classic_rts_command_slot_available'
  'selection_clear_command_disabled_pixel_count'
  'clear:empty@'
  'clear:hostile:'
  'classic_rts_attack_target_at_tile'
  'classic_rts_harvest_node_at_tile'
  'classic_rts_viewport_context_action_for_tile'
  'classic_rts_viewport_context_affordance'
  'classic_rts_viewport_tile_center'
  'classic_rts_hover_target_preview_kind'
  'classic_rts_hover_target_preview_color'
  'classic_rts_primary_selected_tile'
  'CLASSIC_RTS_TARGET_PREVIEW_PATH_COLOR'
  'CLASSIC_RTS_TARGET_PREVIEW_ATTACK_COLOR'
  'CLASSIC_RTS_TARGET_PREVIEW_FOLLOW_COLOR'
  'CLASSIC_RTS_TARGET_PREVIEW_HARVEST_COLOR'
  'CLASSIC_RTS_COMMAND_EXECUTION_FRAME_COLOR'
  'CLASSIC_RTS_COMMAND_EXECUTION_PATH_COLOR'
  'CLASSIC_RTS_COMMAND_EXECUTION_TARGET_COLOR'
  'CLASSIC_RTS_COMMAND_EXECUTION_FOLLOW_COLOR'
  'CLASSIC_RTS_COMMAND_EXECUTION_HARVEST_COLOR'
  'CLASSIC_RTS_COMMAND_EXECUTION_VIEWPORT_MARKER_COLOR'
  'CLASSIC_RTS_COMMAND_EXECUTION_LABEL_COLOR'
  'classic_rts_command_execution_feedback_kind'
  'classic_rts_command_execution_player_label'
  'classic_draw_rts_command_execution_viewport_markers'
  'classic_draw_rts_command_execution_feedback_overlay'
  'classic_rts_move_follow_target'
  'classic_rts_move_formation_kind'
  'right_click_target_attack_gate'
  'right_click_target_semantics_gate'
  'right_click_target_sample'
  'right_click_target_samples'
  'right_click_target_hover_sample'
  'right_click_target_hover_samples'
  'right_click_target_preview_gate'
  'right_click_target_preview_path_pixel_count'
  'right_click_target_preview_attack_pixel_count'
  'right_click_target_preview_follow_pixel_count'
  'right_click_target_preview_harvest_pixel_count'
  'right_click_execution_feedback_gate'
  'right_click_execution_feedback_frame_pixel_count'
  'right_click_execution_feedback_path_pixel_count'
  'right_click_execution_feedback_target_pixel_count'
  'right_click_execution_feedback_follow_pixel_count'
  'right_click_execution_feedback_harvest_pixel_count'
  'right_click_execution_feedback_viewport_marker_pixel_count'
  'target_preview_kind'
  'target_preview_source_tile_id'
  'right_click_target_attack_marker_pixel_count'
  'unit_shift_select_gate'
  'unit_shift_select_samples'
  'unit_double_click_select_gate'
  'unit_double_click_select_sample'
  'classic_poll_control_group_hotkey'
  'classic_rts_control_group_hotkey_slot'
  'replace_classic_rts_control_group_assignment'
  'replace_classic_rts_control_group_assignment_tagged'
  'classic_rts_merged_unit_ids'
  'classic_rts_control_group_slot_summaries'
  'classic_draw_rts_control_group_slot_strip'
  'classic_draw_rts_control_group_slot_strip_for_scene'
  'CLASSIC_RTS_CONTROL_GROUP_SLOT_OCCUPIED_COLOR'
  'CLASSIC_RTS_CONTROL_GROUP_SLOT_COUNT_COLOR'
  'append:'
  'recall_add:'
  'control_group_hotkey_gate'
  'control_group_hotkey_samples'
  'control_group_slot_visual_gate'
  'control_group_slot_pixel_count'
  'classic_rts_hover_preview_from_point'
  'apply_classic_rts_hover_preview_runtime'
  'classic_mouse_viewport_world_tile'
  'classic_draw_rts_hover_preview_overlay'
  'apply_classic_rts_context_cursor_runtime'
  'classic_draw_rts_context_cursor_overlay'
  'classic_rts_command_stamp_for_action'
  'apply_classic_rts_command_stamp_for_action'
  'classic_draw_rts_command_stamp_overlay'
  'classic_rts_hover_player_label'
  'hover_preview_gate'
  'hover_preview_pixel_count'
  'context_cursor_gate'
  'context_cursor_pixel_count'
  'viewport_world_input_gate'
  'drag_select_preview_gate'
  'drag_select_preview_pixel_count'
  'command_stamp_gate'
  'command_stamp_pixel_count'
)

for line in "${required_source_lines[@]}"; do
  if ! grep -Fq "$line" "$SOURCE" "$MAIN"; then
    echo "[FAIL] missing classic RTS live input source line: $line" >&2
    exit 1
  fi
done

required_readiness_lines=(
  'check_trillionnium_world_bevy_classic_rts_live_input_sequence.sh'
  'bevy-classic-rts-live-input-sequence.json'
  'classic_rts_live_input_sequence_green'
  'rts_live_input_live_input_gate'
  'rts_live_input_waypoint_live_gate'
  'rts_live_input_production_feedback_chip_gate'
  'rts_live_input_attack_move_live_gate'
  'rts_live_input_stop_live_gate'
  'rts_live_input_ability_live_gate'
  'rts_live_input_command_feedback_chip_gate'
  'rts_live_input_command_queue_path_preview_gate'
  'rts_live_input_command_queue_path_preview_shift_waypoints_gate'
  'rts_live_input_command_queue_path_preview_queue_stack_gate'
  'rts_live_input_command_queue_path_preview_rally_chain_gate'
  'rts_live_input_command_queue_path_preview_attack_focus_gate'
  'rts_live_input_command_queue_path_preview_cancel_repath_gate'
  '$rts_live[0].context_cursor_gate == true'
  '$rts_live[0].viewport_world_input_gate == true'
  'rts_live_input_hover_preview_gate'
  'rts_live_input_context_cursor_gate'
  'rts_live_input_viewport_world_input_gate'
  'rts_live_input_viewport_world_shifted_tile_id'
  'rts_live_input_drag_select_preview_gate'
  'rts_live_input_drag_select_commit_gate'
  'rts_live_input_drag_select_filter_gate'
  'rts_live_input_command_stamp_gate'
  'rts_live_input_hover_preview_pixel_count'
  'rts_live_input_final_hover_player_label'
  'rts_live_input_context_cursor_pixel_count'
  'rts_live_input_final_context_cursor_label'
  'rts_live_input_drag_select_preview_pixel_count'
  'rts_live_input_drag_select_preview_label'
  'rts_live_input_drag_select_commit_selected_unit_count'
  'rts_live_input_drag_select_commit_label'
  'rts_live_input_drag_select_commit_selection_marker_pixel_count'
  'rts_live_input_drag_select_filter_selected_unit_count'
  'rts_live_input_drag_select_filter_rejected_unit_count'
  'rts_live_input_drag_select_filter_label'
  'rts_live_input_drag_select_filter_selection_marker_pixel_count'
  'rts_live_input_unit_click_select_marker_pixel_count'
  'rts_live_input_unit_click_select_stamp_pixel_count'
  'rts_live_input_unit_click_select_unit_count'
  'rts_live_input_unit_click_select_label'
  'rts_live_input_unit_click_select_gate'
  'rts_live_input_selection_clear_stamp_pixel_count'
  'rts_live_input_selection_clear_command_disabled_pixel_count'
  'rts_live_input_selection_clear_residual_marker_pixel_count'
  'rts_live_input_selection_clear_empty_label'
  'rts_live_input_selection_clear_hostile_label'
  'rts_live_input_selection_clear_gate'
  'rts_live_input_right_click_target_label'
  'rts_live_input_right_click_target_hover_label'
  'rts_live_input_right_click_target_selected_unit_count'
  'rts_live_input_right_click_target_attack_marker_pixel_count'
  'rts_live_input_right_click_target_sample_count'
  'rts_live_input_right_click_target_move_label'
  'rts_live_input_right_click_target_follow_label'
  'rts_live_input_right_click_target_harvest_label'
  'rts_live_input_right_click_target_follow_stamp_pixel_count'
  'rts_live_input_right_click_target_harvest_stamp_pixel_count'
  'rts_live_input_right_click_target_preview_path_pixel_count'
  'rts_live_input_right_click_target_preview_attack_pixel_count'
  'rts_live_input_right_click_target_preview_follow_pixel_count'
  'rts_live_input_right_click_target_preview_harvest_pixel_count'
  'rts_live_input_right_click_target_preview_gate'
  'rts_live_input_right_click_execution_feedback_frame_pixel_count'
  'rts_live_input_right_click_execution_feedback_path_pixel_count'
  'rts_live_input_right_click_execution_feedback_target_pixel_count'
  'rts_live_input_right_click_execution_feedback_follow_pixel_count'
  'rts_live_input_right_click_execution_feedback_harvest_pixel_count'
  'rts_live_input_right_click_execution_feedback_viewport_marker_pixel_count'
  'rts_live_input_right_click_execution_feedback_label_pixel_count'
  'rts_live_input_right_click_execution_feedback_move_label'
  'rts_live_input_right_click_execution_feedback_attack_label'
  'rts_live_input_right_click_execution_feedback_follow_label'
  'rts_live_input_right_click_execution_feedback_harvest_label'
  'rts_live_input_right_click_execution_feedback_player_label_gate'
  'rts_live_input_right_click_execution_feedback_gate'
  'rts_live_input_right_click_target_gate'
  'rts_live_input_unit_shift_select_marker_pixel_count'
  'rts_live_input_unit_shift_select_stamp_pixel_count'
  'rts_live_input_unit_shift_select_add_unit_count'
  'rts_live_input_unit_shift_select_remove_unit_count'
  'rts_live_input_unit_shift_select_add_label'
  'rts_live_input_unit_shift_select_remove_label'
  'rts_live_input_unit_shift_select_gate'
  'rts_live_input_unit_double_click_select_marker_pixel_count'
  'rts_live_input_unit_double_click_select_stamp_pixel_count'
  'rts_live_input_unit_double_click_select_unit_count'
  'rts_live_input_unit_double_click_select_label'
  'rts_live_input_unit_double_click_select_gate'
  'rts_live_input_control_group_hotkey_marker_pixel_count'
  'rts_live_input_control_group_hotkey_stamp_pixel_count'
  'rts_live_input_control_group_hotkey_assign_label'
  'rts_live_input_control_group_hotkey_recall_label'
  'rts_live_input_control_group_hotkey_camera_label'
  'rts_live_input_control_group_hotkey_append_label'
  'rts_live_input_control_group_hotkey_recall_add_label'
  'rts_live_input_control_group_hotkey_append_unit_count'
  'rts_live_input_control_group_hotkey_recall_add_unit_count'
  'rts_live_input_control_group_hotkey_gate'
  'rts_live_input_control_group_slot_pixel_count'
  'rts_live_input_control_group_slot_5_member_count'
  'rts_live_input_control_group_slot_0_key_label'
  'rts_live_input_control_group_slot_visual_gate'
  'rts_live_input_command_stamp_pixel_count'
  'rts_live_input_final_command_stamp_player_label'
  'rts_live_input_command_feedback_chip_count'
  'rts_live_input_command_queue_path_preview_slot_pixel_count'
  'rts_live_input_command_queue_path_preview_path_pixel_count'
  'rts_live_input_command_queue_path_preview_waypoint_pixel_count'
  'rts_live_input_command_queue_path_preview_target_pixel_count'
  'rts_live_input_command_queue_path_preview_cancel_pixel_count'
  'rts_live_input_accepted_input_count'
)

for line in "${required_readiness_lines[@]}"; do
  if ! grep -Fq "$line" "$READINESS"; then
    echo "[FAIL] missing classic RTS live input readiness line: $line" >&2
    exit 1
  fi
done

echo "[PASS] classic RTS live input sequence remains connected to native action input, evidence, and readiness"
