#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_bevy_classic_art_pack.sh"
RUNNER="$ROOT/scripts/run_trillionnium_world_bevy_client.sh"
RUNNER_STATUS="$ROOT/scripts/check_trillionnium_world_bevy_classic_playtest_runner_status.sh"
SOURCE="$ROOT/trillionnium/crates/trnm-world-bevy/src/lib.rs"
MAIN="$ROOT/trillionnium/crates/trnm-world-bevy/src/main.rs"

required_script_lines=(
  'trillionnium_world_bevy_classic_art_pack_v1'
  'bevy-classic-art-pack.json'
  'bevy-classic-art-pack.ppm'
  'assets/trnm-world/classic/art-pack-v1'
  'classic-art-pack'
  'model_town_hall'
  'model_waygate'
  'model_training_hall'
  'model_coliseum_stands'
  'model_tree_cluster_large'
  'doodad_rock_cluster'
  'doodad_barrel_stack'
  'doodad_torch'
  'doodad_crystal_cluster'
  'tile_grass_a'
  'tile_grass_b'
  'tile_road'
  'tile_water'
  'tile_wall'
  'tile_roof'
  'tile_arena'
  'actor_mentor_talk'
  'actor_vendor_idle'
  'prop_training_dummy'
  'prop_reward'
  'prop_arena_gate'
  'prop_market_stall'
  'prop_banner'
  'marker_objective'
  'marker_interaction'
  'rts_command_destination_marker'
  'combat_attack_arc'
  'combat_hit_flash'
  'rts_unit_selection_ring'
  'unit_health_bar'
  'rts_foundation_shadow'
  'actor_player_idle_south'
  'actor_player_walk_north_1'
  'actor_player_walk_east_1'
  'actor_player_walk_west_1'
  'actor_enemy'
  'actor_enemy_attack'
  'asset_count >= 62'
  'override_frame_count >= 62'
  'preview_height >= 1680'
  'group_counts.doodad >= 8'
  'group_counts.terrain >= 11'
  'group_counts.world_prop >= 9'
  'group_counts.vfx >= 6'
  'group_counts.player >= 13'
  'group_counts.enemy >= 4'
  'group_counts.neutral_unit >= 6'
  'required_model_gate == true'
  'player_art_gate == true'
  'enemy_art_gate == true'
  'neutral_unit_art_gate == true'
  'doodad_art_gate == true'
  'terrain_art_gate == true'
  'world_prop_art_gate == true'
  'vfx_art_gate == true'
  'preview_non_background_pixels > 35000'
  'model_detail_gate == true'
  'model_detail_asset_count >= 5'
  'model_unique_color_total >= 45'
  'model_shadow_pixel_count > 300'
  'model_highlight_pixel_count > 120'
  'unit_detail_gate == true'
  'player_unit_detail_asset_count >= 13'
  'enemy_unit_detail_asset_count >= 4'
  'unit_unique_color_total >= 100'
  'unit_shadow_pixel_count > 130'
  'unit_highlight_pixel_count > 100'
  'neutral_unit_detail_gate == true'
  'neutral_unit_detail_asset_count >= 6'
  'neutral_unit_unique_color_total >= 42'
  'neutral_unit_shadow_pixel_count > 48'
  'neutral_unit_highlight_pixel_count > 24'
  'neutral_unit_detail_pixel_count > 360'
  'doodad_detail_gate == true'
  'doodad_detail_asset_count >= 8'
  'doodad_unique_color_total >= 24'
  'doodad_shadow_pixel_count > 40'
  'doodad_detail_pixel_count > 420'
  'terrain_detail_gate == true'
  'terrain_detail_asset_count >= 11'
  'terrain_unique_color_total >= 44'
  'terrain_detail_pixel_count > 1350'
  'world_prop_detail_gate == true'
  'world_prop_detail_asset_count >= 9'
  'world_prop_unique_color_total >= 31'
  'world_prop_detail_pixel_count > 800'
  'vfx_detail_gate == true'
  'vfx_detail_asset_count >= 6'
  'vfx_unique_color_total >= 18'
  'vfx_detail_pixel_count > 700'
  'replacement_boundary_gate == true'
  'cex_runtime_player_client_allowed == false'
  'wgpu_required == false'
)

for line in "${required_script_lines[@]}"; do
  if ! grep -Fq "$line" "$SCRIPT"; then
    echo "[FAIL] missing classic art pack script line: $line" >&2
    exit 1
  fi
done

required_source_lines=(
  'TRILLIONNIUM_WORLD_BEVY_CLASSIC_ART_PACK_CONTRACT'
  'native_classic_art_pack_evidence_json'
  'classic-art-pack'
  'classic-artpack'
  'classic_art_pack_override_specs'
  'classic_art_pack_synthetic_override_specs'
  'classic_art_pack_pixels'
  'classic_draw_art_pack_preview'
  'model_town_hall'
  'model_waygate'
  'model_training_hall'
  'model_coliseum_stands'
  'model_tree_cluster_large'
  'actor_player_idle_south'
  'actor_player_walk_north_1'
  'actor_player_walk_east_1'
  'actor_player_walk_west_1'
  'actor_enemy'
  'actor_enemy_attack'
  'doodad_rock_cluster'
  'doodad_barrel_stack'
  'doodad_torch'
  'doodad_crystal_cluster'
  'tile_grass_a'
  'tile_grass_b'
  'tile_road'
  'tile_water'
  'tile_wall'
  'tile_roof'
  'tile_arena'
  'actor_mentor_talk'
  'actor_vendor_idle'
  'prop_training_dummy'
  'prop_reward'
  'prop_arena_gate'
  'prop_market_stall'
  'prop_banner'
  'marker_objective'
  'marker_interaction'
  'rts_command_destination_marker'
  'combat_attack_arc'
  'combat_hit_flash'
  'rts_unit_selection_ring'
  'unit_health_bar'
  'rts_foundation_shadow'
  'town_hall'
  'waygate'
  'training_hall'
  'coliseum'
  'tree_cluster'
  'player_art_gate'
  'enemy_art_gate'
  'model_detail_gate'
  'classic_art_pack_highlight_color'
  'model_detail_asset_gate'
  'unit_detail_gate'
  'unit_detail_asset_gate'
  'player_unit_detail_asset_count'
  'enemy_unit_detail_asset_count'
  'doodad_detail_gate'
  'doodad_detail_asset_gate'
  'classic_art_pack_doodad_detail_color'
  'terrain_art_gate'
  'terrain_detail_gate'
  'terrain_detail_asset_gate'
  'classic_art_pack_terrain_frame'
  'classic_art_pack_terrain_detail_color'
  'world_prop_art_gate'
  'world_prop_detail_gate'
  'world_prop_detail_asset_gate'
  'classic_art_pack_world_prop_frame'
  'classic_art_pack_world_prop_detail_color'
  'vfx_detail_gate'
  'vfx_detail_asset_gate'
  'classic_art_pack_vfx_frame'
  'classic_art_pack_vfx_detail_color'
  'classic_blit_frame_override_bottom_center'
  'first real 2.5D override sprites'
)

for line in "${required_source_lines[@]}"; do
  if ! grep -Fq "$line" "$SOURCE" "$MAIN"; then
    echo "[FAIL] missing classic art pack source line: $line" >&2
    exit 1
  fi
done

if ! grep -Fq 'TRNM_WORLD_BEVY_CLASSIC_ASSET_OVERRIDE_DIR' "$RUNNER" "$RUNNER_STATUS"; then
  echo "[FAIL] runner does not expose the classic art pack override env" >&2
  exit 1
fi

if ! grep -Fq 'art-pack-v1' "$RUNNER" "$RUNNER_STATUS"; then
  echo "[FAIL] runner does not target art-pack-v1" >&2
  exit 1
fi

echo "[PASS] classic art pack keeps the first real Bevy 2.5D assets wired to the runner"
