#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_bevy_classic_rts_live_input_sequence.sh"
SOURCE="$ROOT/trillionnium/crates/trnm-world-bevy/src/lib.rs"
MAIN="$ROOT/trillionnium/crates/trnm-world-bevy/src/main.rs"
READINESS="$ROOT/scripts/check_trillionnium_world_bevy_classic_playtest_readiness.sh"

required_script_lines=(
  'trillionnium_world_bevy_classic_rts_live_input_sequence_v1'
  'bevy-classic-rts-live-input-sequence.json'
  'bevy-classic-rts-live-input-sequence.ppm'
  'classic-rts-live-input-sequence'
  'input_path == "apply_live_native_action_with_source(classic_rts_live_input)"'
  'accepted_input_count == 10'
  'RTS:SELECT:1'
  'RTS:QUEUE:train:guard'
  'RTS:MOVE:7,4:diamond'
  'RTS:MOVE:9,4:shift_waypoint'
  'RTS:MOVE:6,5:hold'
  'RTS:MOVE:9,4:patrol'
  'RTS:MOVE:10,3:attack_move'
  'RTS:MOVE:10,3:stop'
  'RTS:ATTACK:arena_creep_attack'
  'RTS:ABILITY:focus_fire'
  'feedback:train_queued:guard'
  'feedback:waypoint_queued@9,4'
  'feedback:hold_position@6,5'
  'feedback:patrol_route@9,4'
  'feedback:attack_move@10,3:'
  'feedback:stop_hold@10,3'
  'hover_preview_pixel_count > 40'
  'context_cursor_pixel_count > 80'
  'drag_select_preview_pixel_count > 80'
  'command_stamp_pixel_count > 120'
  'MAP MOVE SENT 7,4'
  'MAP ATTACK SENT ARENA CREEP ATTACK'
  'COMMAND ABILITY SENT FOCUS FIRE'
  'final_command_stamp_player_label == "COMMAND ABILITY SENT FOCUS FIRE"'
  '.drag_select_preview_samples | length == 1'
  'classic_rts_mouse_drag'
  'DRAG SELECT 2 UNITS 2,2->6,4'
  'drag_select_commit_selection_marker_pixel_count > 250'
  'drag_select_commit_stamp_pixel_count > 80'
  'DRAG SELECT SENT 2 UNITS'
  'unit_click_select_marker_pixel_count > 80'
  'unit_click_select_stamp_pixel_count > 80'
  'RTS:SELECT:unit:player'
  'unit_selected:player@5,4'
  'unit_select:player@5,4'
  'MAP SELECT SENT 1 UNIT'
  'unit_shift_select_marker_pixel_count > 80'
  'unit_shift_select_stamp_pixel_count > 80'
  'RTS:SELECT:shift:unit:square_guard_patrol'
  'unit_shift_added:square_guard_patrol@7,5:count:2'
  'unit_shift_add:square_guard_patrol@7,5'
  'MAP SHIFT SELECT SENT 2 UNITS'
  'RTS:SELECT:shift:unit:player'
  'unit_shift_removed:player@5,4:count:1'
  'unit_shift_remove:player@5,4'
  'MAP SHIFT SELECT SENT 1 UNIT'
  'unit_double_click_select_marker_pixel_count > 80'
  'unit_double_click_select_stamp_pixel_count > 80'
  'RTS:SELECT:double:unit:player'
  'unit_double_selected:guard:count:3'
  'unit_double_select:guard:player|square_guard_front|square_guard_patrol'
  'MAP DOUBLE SELECT SENT 3 UNITS'
  'control_group_hotkey_marker_pixel_count > 80'
  'control_group_hotkey_stamp_pixel_count > 80'
  'RTS:SELECT:assign:5'
  'group_5_assigned:2units'
  'control_group_assign:5:player|square_guard_patrol'
  'HOTKEY GROUP 5 ASSIGNED 2 UNITS'
  'RTS:SELECT:recall:5'
  'group_5_recalled:2units'
  'control_group_recall:5:player|square_guard_patrol'
  'HOTKEY GROUP 5 RECALLED 2 UNITS'
  'RTS:SELECT:camera:5'
  'camera_snap:group_5'
  'control_group_camera:5@5,4'
  'HOTKEY GROUP 5 CAMERA SNAP'
  'drag_select_preview_gate == true'
  'drag_select_commit_gate == true'
  'unit_click_select_gate == true'
  'unit_shift_select_gate == true'
  'control_group_hotkey_gate == true'
  '.hover_samples | length == 4'
  'MAP MOVE READY 4,3'
  'SIDEBAR QUEUE READY WATCH TOWER'
  'COMMAND BAR ABILITY READY'
  'MINIMAP RALLY READY 5,2'
  'MAP CURSOR MOVE READY'
  'SIDEBAR CURSOR BUILD READY'
  'COMMAND BAR CURSOR ABILITY READY'
  'MINIMAP CURSOR RALLY READY'
  'final_hover_source == "classic_rts_mouse_minimap"'
  'final_context_cursor_player_label == "MINIMAP CURSOR RALLY READY"'
  'hover_preview_gate == true'
  'context_cursor_gate == true'
  'command_stamp_gate == true'
  'live_input_gate == true'
  'selection_live_gate == true'
  'production_live_gate == true'
  'production_feedback_chip_gate == true'
  'move_live_gate == true'
  'waypoint_live_gate == true'
  'hold_live_gate == true'
  'patrol_live_gate == true'
  'attack_move_live_gate == true'
  'stop_live_gate == true'
  'attack_live_gate == true'
  'ability_live_gate == true'
  'command_feedback_chip_gate == true'
)

for line in "${required_script_lines[@]}"; do
  if ! grep -Fq "$line" "$SCRIPT"; then
    echo "[FAIL] missing classic RTS live input script line: $line" >&2
    exit 1
  fi
done

required_source_lines=(
  'TRILLIONNIUM_WORLD_BEVY_CLASSIC_RTS_LIVE_INPUT_SEQUENCE_CONTRACT'
  'native_classic_rts_live_input_sequence_evidence_json'
  'classic-rts-live-input-sequence'
  'RtsSelectControlGroup'
  'RtsQueueProduction'
  'RtsMoveCommand'
  'RtsAttackCommand'
  'RtsAbilityCommand'
  'apply_live_native_action_with_source'
  'classic_rts_live_input'
  'apply_classic_rts_select_group_runtime'
  'apply_classic_rts_queue_runtime'
  'apply_classic_rts_move_runtime'
  'apply_classic_rts_attack_runtime'
  'apply_classic_rts_ability_runtime'
  'selection_live_gate'
  'production_live_gate'
  'production_feedback_chip_gate'
  'move_live_gate'
  'waypoint_live_gate'
  'hold_live_gate'
  'patrol_live_gate'
  'attack_move_live_gate'
  'stop_live_gate'
  'attack_live_gate'
  'ability_live_gate'
  'command_feedback_chip_gate'
  'command_feedback_chip_count'
  'ClassicRtsHoverPreview'
  'ClassicRtsDragSelectPreview'
  'ClassicRtsCommandStamp'
  'rts_cursor_player_label'
  'classic_rts_drag_select_preview_from_points'
  'apply_classic_rts_drag_select_preview_runtime'
  'classic_draw_rts_drag_select_preview_overlay'
  'drag_select_commit_gate'
  'drag_select_commit_sample'
  'classic_rts_selectable_unit_at_tile'
  'classic_rts_selectable_unit_tile'
  'classic_rts_selection_tiles_for_units'
  'classic_rts_mouse_action_with_source_from_point_with_shift'
  'classic_rts_mouse_action_with_source_from_point_with_modifiers'
  'classic_rts_same_class_units'
  'unit_click_select_gate'
  'unit_click_select_sample'
  'unit_shift_select_gate'
  'unit_shift_select_samples'
  'unit_double_click_select_gate'
  'unit_double_click_select_sample'
  'classic_poll_control_group_hotkey'
  'classic_rts_control_group_hotkey_slot'
  'replace_classic_rts_control_group_assignment'
  'control_group_hotkey_gate'
  'control_group_hotkey_samples'
  'classic_rts_hover_preview_from_point'
  'apply_classic_rts_hover_preview_runtime'
  'classic_draw_rts_hover_preview_overlay'
  'apply_classic_rts_context_cursor_runtime'
  'classic_draw_rts_context_cursor_overlay'
  'classic_rts_command_stamp_for_action'
  'apply_classic_rts_command_stamp_for_action'
  'classic_draw_rts_command_stamp_overlay'
  'classic_rts_hover_player_label'
  'hover_preview_gate'
  'hover_preview_pixel_count'
  'context_cursor_gate'
  'context_cursor_pixel_count'
  'drag_select_preview_gate'
  'drag_select_preview_pixel_count'
  'command_stamp_gate'
  'command_stamp_pixel_count'
)

for line in "${required_source_lines[@]}"; do
  if ! grep -Fq "$line" "$SOURCE" "$MAIN"; then
    echo "[FAIL] missing classic RTS live input source line: $line" >&2
    exit 1
  fi
done

required_readiness_lines=(
  'check_trillionnium_world_bevy_classic_rts_live_input_sequence.sh'
  'bevy-classic-rts-live-input-sequence.json'
  'classic_rts_live_input_sequence_green'
  'rts_live_input_live_input_gate'
  'rts_live_input_waypoint_live_gate'
  'rts_live_input_production_feedback_chip_gate'
  'rts_live_input_attack_move_live_gate'
  'rts_live_input_stop_live_gate'
  'rts_live_input_ability_live_gate'
  'rts_live_input_command_feedback_chip_gate'
  '$rts_live[0].context_cursor_gate == true'
  'rts_live_input_hover_preview_gate'
  'rts_live_input_context_cursor_gate'
  'rts_live_input_drag_select_preview_gate'
  'rts_live_input_drag_select_commit_gate'
  'rts_live_input_command_stamp_gate'
  'rts_live_input_hover_preview_pixel_count'
  'rts_live_input_final_hover_player_label'
  'rts_live_input_context_cursor_pixel_count'
  'rts_live_input_final_context_cursor_label'
  'rts_live_input_drag_select_preview_pixel_count'
  'rts_live_input_drag_select_preview_label'
  'rts_live_input_drag_select_commit_selected_unit_count'
  'rts_live_input_drag_select_commit_label'
  'rts_live_input_drag_select_commit_selection_marker_pixel_count'
  'rts_live_input_unit_click_select_marker_pixel_count'
  'rts_live_input_unit_click_select_stamp_pixel_count'
  'rts_live_input_unit_click_select_unit_count'
  'rts_live_input_unit_click_select_label'
  'rts_live_input_unit_click_select_gate'
  'rts_live_input_unit_shift_select_marker_pixel_count'
  'rts_live_input_unit_shift_select_stamp_pixel_count'
  'rts_live_input_unit_shift_select_add_unit_count'
  'rts_live_input_unit_shift_select_remove_unit_count'
  'rts_live_input_unit_shift_select_add_label'
  'rts_live_input_unit_shift_select_remove_label'
  'rts_live_input_unit_shift_select_gate'
  'rts_live_input_unit_double_click_select_marker_pixel_count'
  'rts_live_input_unit_double_click_select_stamp_pixel_count'
  'rts_live_input_unit_double_click_select_unit_count'
  'rts_live_input_unit_double_click_select_label'
  'rts_live_input_unit_double_click_select_gate'
  'rts_live_input_control_group_hotkey_marker_pixel_count'
  'rts_live_input_control_group_hotkey_stamp_pixel_count'
  'rts_live_input_control_group_hotkey_assign_label'
  'rts_live_input_control_group_hotkey_recall_label'
  'rts_live_input_control_group_hotkey_camera_label'
  'rts_live_input_control_group_hotkey_gate'
  'rts_live_input_command_stamp_pixel_count'
  'rts_live_input_final_command_stamp_player_label'
  'rts_live_input_command_feedback_chip_count'
  'rts_live_input_accepted_input_count'
)

for line in "${required_readiness_lines[@]}"; do
  if ! grep -Fq "$line" "$READINESS"; then
    echo "[FAIL] missing classic RTS live input readiness line: $line" >&2
    exit 1
  fi
done

echo "[PASS] classic RTS live input sequence remains connected to native action input, evidence, and readiness"
