#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_bevy_classic_playtest_runner_status.sh"

required_lines=(
  'trillionnium_world_bevy_classic_playtest_runner_status_v1'
  'bevy-classic-playtest-runner-status.json'
  'trillionnium-bevy-playtest.service'
  'target/release/trnm-world-bevy'
  'TRNM_WORLD_BEVY_LOW_SPEC'
  'TRNM_WORLD_BEVY_CLASSIC_RENDERER'
  'TRNM_WORLD_BEVY_CLASSIC_FPS'
  'TRNM_WORLD_BEVY_CLASSIC_PLAYER_SCREEN'
  'WINIT_UNIX_BACKEND'
  'TRNM_WORLD_BEVY_CLASSIC_ASSET_MANIFEST'
  'CPUQuotaPerSecUSec'
  'CPUWeight'
  'service_process_gate'
  'release_binary_gate'
  'classic_env_gate'
  'player_screen_env_gate'
  'cpu_budget_gate'
  'trillionnium_world_bevy_classic_player_screen_runner_visual_v1'
  'bevy-classic-player-screen-runner-status.png'
  'player_screen_window_gate'
  'player_screen_title_gate'
  'player_screen_proof_debug_absent_gate'
  'player_screen_title_concise_gate'
  'player_screen_screenshot_gate'
  'player_screen_region_gate'
  'player_screen_dead_panel_gate'
  'player_screen_clipped_label_gate'
  'player_screen_gameplay_scene_gate'
  'player_screen_debug_title_absent_gate'
  'player_screen_visual_gate'
  'ready_for_release_review'
  'public_launch_ready'
  'android_s5_real_device_claimed'
  'runtime_cmdline_arg_count'
  'selected_environment_count'
  'live_player_screen_evidence_path_count'
  'live_player_screen_pixel_count'
  'gate_count'
  'passed_gate_count'
  'failed_gate_count'
  'dead_panel_gate'
  'clipped_label_edge_gate'
  'gameplay_scene_gate'
  'debug_title_text_absent_gate'
  'build_blueprint_exact_cyan'
  'exact_blueprint_micro_component_gate'
  'relay_scaffold_exact_tan'
  'exact_scaffold_thin_component_gate'
  'harvest_tool_swing_exact_orange'
  'exact_harvest_swing_micro_component_gate'
  'active_beacon_capture_exact_yellow'
  'exact_beacon_capture_micro_component_gate'
  'main_map_objective_exact_green'
  'exact_main_map_objective_micro_component_gate'
  'beacon_animation_range_exact_green'
  'exact_beacon_animation_range_micro_component_gate'
  'product_map_density_exact_green'
  'exact_product_map_density_micro_component_gate'
  'selection_feedback_confirm_exact_cyan'
  'exact_selection_confirm_micro_component_gate'
  'unit_status_health_exact_green'
  'exact_unit_status_health_micro_component_gate'
  'unit_status_role_badge_exact_purple'
  'exact_unit_status_role_badge_micro_component_gate'
  'owner_identity_exact_player_muted'
  'owner_identity_exact_enemy_muted'
  'exact_owner_identity_micro_component_gate'
  'unit_model_identity_exact_light'
  'exact_unit_identity_micro_component_gate'
  'edge_safety_samples'
  'room=first-contact-basin'
  'owned-assets-v1'
  'window_title_chars'
  'bounded CPUQuota/CPUWeight budget'
  'map/HUD/command pixels'
  'non-dead HUD panels'
  'clipped-label edge safety'
  'bottom_command_bottom_quiet_band'
  'bottom-edge HUD strip'
  'gameplay-scene balance'
  'proof/debug/shortcut-manual default title strings are explicitly rejected'
  'x11_backend_gate'
  'cex_path_gate'
  'CEX paths are explicitly rejected'
)

for line in "${required_lines[@]}"; do
  if ! grep -Fq "$line" "$SCRIPT"; then
    echo "[FAIL] missing runner status contract line: $line" >&2
    exit 1
  fi
done

echo "[PASS] classic playtest runner status script keeps the live Bevy runner contract"
