#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BASIN_SCRIPT="$ROOT/scripts/check_trillionnium_world_bevy_classic_rts_first_contact_basin_spec.sh"
READINESS_SCRIPT="$ROOT/scripts/check_trillionnium_world_bevy_classic_playtest_readiness.sh"
INTEGRITY_SCRIPT="$ROOT/scripts/check_trillionnium_world_release_review_packet_integrity.sh"
FIXTURE_LIB="$ROOT/scripts/v2/release_review_packet_integrity_visual_foundation_fixture_lib.sh"

require_line() {
  local file="$1"
  local line="$2"
  if ! grep -Fq -- "$line" "$file"; then
    echo "[FAIL] $(basename "$file") missing contract line: $line" >&2
    exit 1
  fi
}

basin_lines=(
  'ART_RENDERER_SOURCE="$ROOT/trillionnium/crates/trnm-world-bevy/src/first_contact_art_renderer.rs"'
  'SILHOUETTE_RENDERER_SOURCE="$ROOT/trillionnium/crates/trnm-world-bevy/src/first_contact_silhouette_renderer.rs"'
  'FOCUS_RENDERER_SOURCE="$ROOT/trillionnium/crates/trnm-world-bevy/src/first_contact_focus_renderer.rs"'
  'RADAR_RENDERER_SOURCE="$ROOT/trillionnium/crates/trnm-world-bevy/src/first_contact_radar_renderer.rs"'
  'RAW_OUT="$OUT.raw.$$"'
  'TMP_OUT="$OUT.tmp.$$"'
  'trap '\''rm -f "$RAW_OUT" "$TMP_OUT" "$JQ_FILTER"'\'' EXIT'
  'classic-rts-first-contact-basin-spec >"$RAW_OUT"'
  'mv "$TMP_OUT" "$OUT"'
  'required_art_renderer_source_lines=('
  'fn terrain_samples'
  'fn building_samples'
  'fn landmark_samples'
  'fn draw_terrain_material_depth_detail'
  'fn draw_terrain_detail'
  'fn draw_building_detail'
  'fn draw_landmark_detail'
  'pub(super) fn draw_readability_layer'
  'required_silhouette_renderer_source_lines=('
  'fn unit_samples'
  'fn structure_samples'
  'fn terrain_samples'
  'fn draw_unit'
  'fn draw_structure'
  'fn draw_terrain_marker'
  'pub(super) fn draw_readability_layer'
  'required_focus_renderer_source_lines=('
  'fn selection_combat_focus_route_tiles'
  'fn route_clearance_tiles'
  'fn draw_route_clearance_corner_cues'
  'fn draw_focus_corner_brackets'
  'fn draw_target_callout'
  'pub(super) fn draw_selection_combat_focus_layer'
  'required_radar_renderer_source_lines=('
  'fn lane_sample_tiles'
  'fn structure_tiles'
  'fn pressure_tiles'
  'fn objective_tiles'
  'pub(super) fn draw_context'
  'fn classic_first_contact_non_focus_owner_identity_color'
  'fn classic_first_contact_owner_identity_color'
  'fn classic_first_contact_base_owner_identity_tiles'
  'fn classic_first_contact_player_visible_tactical_tracks'
  'fn classic_first_contact_player_screen_suppresses_hover_route_path'
  'fn classic_rts_hover_target_preview_path_marker_count'
  'CLASSIC_FIRST_CONTACT_RUNTIME_CORE_VISIBLE_TILE_Y_MAX'
  'fn classic_first_contact_runtime_core_actor_candidate'
  'fn classic_first_contact_runtime_core_semantic_fixture_actor'
  'fn classic_first_contact_runtime_core_actor_player_visible'
  'fn classic_first_contact_runtime_actor_selection_ring_candidate'
  'fn classic_first_contact_runtime_actor_selection_ring_visible'
  'fn classic_first_contact_runtime_actor_unit_role_accent_candidate'
  'fn classic_first_contact_runtime_actor_unit_role_accent_visible'
  'fn classic_first_contact_runtime_core_visibility'
  'let first_contact_runtime_core_visibility_gate'
  'contract_field_count = ([keys[] | select(endswith("_contract"))] | length)'
  'guard_object_count = ([to_entries[] | select((.key | test("^first_contact_.*_guard$")) and (.value | type == "object"))] | length)'
  'top_level_gate_count = ([to_entries[] | select((.key | endswith("_gate")) and (.value | type == "boolean"))] | length)'
  'rts_data_map_model_actor_count = ((.rts_data_map_model.actors // []) | length)'
  'runtime_player_screen_command_queue_count = ((.rts_bevy_runtime_player_screen_application.command_queue // []) | length)'
  'offline_lobby_ready_label_count = ((.rts_online_offline_adapter_lobby_ready.ready_state_labels // []) | length)'
  '.guard_object_count == 16'
  '.top_level_gate_count == 46'
  'first_contact_runtime_core_visibility.runtime_core_hidden_fixture_actor_count == 69'
  'first_contact_runtime_core_visibility.runtime_core_hidden_control_fixture_actor_count == 48'
  'first_contact_runtime_core_visibility.runtime_core_hidden_semantic_fixture_actor_count == 20'
  'first_contact_runtime_core_visibility.runtime_core_inline_health_bar_actor_count == 4'
  'first_contact_runtime_core_visibility.runtime_core_suppressed_inline_health_bar_actor_count == 10'
  'first_contact_runtime_core_visibility.runtime_core_progress_bar_actor_count == 2'
  'first_contact_runtime_core_visibility.runtime_core_selection_ring_candidate_actor_count == 14'
  'first_contact_runtime_core_visibility.runtime_core_selection_ring_visible_actor_count == 0'
  'first_contact_runtime_core_visibility.runtime_core_suppressed_selection_ring_actor_count == 14'
  'first_contact_runtime_core_visibility.runtime_core_unit_role_accent_candidate_actor_count == 9'
  'first_contact_runtime_core_visibility.runtime_core_unit_role_accent_visible_actor_count == 0'
  'first_contact_runtime_core_visibility.runtime_core_suppressed_unit_role_accent_actor_count == 9'
  'first_contact_runtime_core_visibility.runtime_core_required_visible_actor_ids == ["multi0.command.core","multi0.worker.0","multi0.flux.relay","map.actor15"]'
  'first_contact_runtime_core_visibility.runtime_core_inline_health_bar_actor_ids | index("multi0.damaged.relay")'
  'first_contact_runtime_core_visibility.runtime_core_inline_health_bar_actor_ids | index("multi0.command.core") == null'
  'first_contact_runtime_core_visibility.runtime_core_progress_bar_actor_ids | index("map.actor15")'
  'first_contact_runtime_core_visibility.runtime_core_selection_ring_candidate_actor_ids | index("multi0.worker.0")'
  'first_contact_runtime_core_visibility.runtime_core_selection_ring_visible_actor_ids | length == 0'
  'first_contact_runtime_core_visibility.runtime_core_unit_role_accent_candidate_actor_ids | index("multi0.worker.0")'
  'first_contact_runtime_core_visibility.runtime_core_unit_role_accent_visible_actor_ids | length == 0'
  'first_contact_runtime_core_visibility.runtime_core_hidden_control_fixture_actor_ids | index("multi0.append.seed")'
  'first_contact_runtime_core_visibility.runtime_core_hidden_semantic_fixture_actor_ids | index("multi0.obstruction.leader")'
  'first_contact_runtime_core_visibility.runtime_core_hidden_semantic_fixture_actor_ids | index("multi0.reservation.lead")'
  'first_contact_runtime_core_visibility.runtime_core_hidden_semantic_fixture_actor_ids | index("multi0.traffic.stuck.runner")'
  'first_contact_runtime_core_visibility.runtime_core_hidden_semantic_fixture_actor_ids | index("multi0.focus.warden.a")'
  'first_contact_runtime_core_visibility.runtime_core_hidden_semantic_fixture_actor_ids | index("multi0.priority.guard")'
  'first_contact_runtime_core_visibility.runtime_core_hidden_semantic_fixture_actor_ids | index("multi0.attackmove.warden")'
  'first_contact_runtime_core_visibility.runtime_core_control_fixture_gate == true'
  'first_contact_runtime_core_visibility.runtime_core_semantic_fixture_gate == true'
  'first_contact_runtime_core_visibility.runtime_core_bottom_fixture_gate == true'
  'first_contact_runtime_core_visibility.runtime_core_inline_health_bar_gate == true'
  'first_contact_runtime_core_visibility.runtime_core_selection_ring_gate == true'
  'first_contact_runtime_core_visibility.runtime_core_unit_role_accent_gate == true'
  'first_contact_runtime_core_visibility_gate == true'
  'first_contact_motion_readability_guard.opening_action_motion_signatures | index("opening_action_path_micro_dots")'
  'first_contact_motion_readability_guard.opening_action_path_count == 3'
  'first_contact_motion_readability_guard.opening_action_path_step_count == 24'
  'first_contact_motion_readability_guard.opening_action_path_dot_width_px == 2'
  'first_contact_motion_readability_guard.opening_action_path_dot_height_px == 2'
  'first_contact_motion_readability_guard.opening_action_path_pixel_budget <= 96'
  'first_contact_motion_readability_guard.opening_action_path_gate == true'
  'first_contact_motion_readability_guard.unit_state_motion_signatures | index("player_screen_production_training_micro_sparks")'
  'first_contact_motion_readability_guard.production_training_spark_count == 3'
  'first_contact_motion_readability_guard.production_training_spark_width_px == 4'
  'first_contact_motion_readability_guard.production_training_spark_height_px == 2'
  'first_contact_motion_readability_guard.production_training_spark_pixel_budget <= 24'
  'first_contact_motion_readability_guard.production_training_spark_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_animation_training_lane_micro_ticks")'
  'first_contact_motion_readability_guard.animation_training_tick_count == 3'
  'first_contact_motion_readability_guard.animation_training_tick_width_px == 4'
  'first_contact_motion_readability_guard.animation_training_tick_height_px == 2'
  'first_contact_motion_readability_guard.animation_training_tick_pixel_budget <= 24'
  'first_contact_motion_readability_guard.animation_training_tick_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_harvest_tool_swing_micro_sparks")'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_count == 6'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_width_px == 6'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_height_px == 2'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_pixel_budget <= 72'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_spawn_door_micro_shutters")'
  'first_contact_motion_readability_guard.spawn_door_shutter_count == 7'
  'first_contact_motion_readability_guard.spawn_door_shutter_width_px == 4'
  'first_contact_motion_readability_guard.spawn_door_shutter_height_px == 2'
  'first_contact_motion_readability_guard.spawn_door_shutter_pixel_budget <= 56'
  'first_contact_motion_readability_guard.spawn_door_shutter_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_rally_flag_micro_pennants")'
  'first_contact_motion_readability_guard.rally_flag_pennant_count == 5'
  'first_contact_motion_readability_guard.rally_flag_pennant_width_px == 6'
  'first_contact_motion_readability_guard.rally_flag_pennant_height_px == 2'
  'first_contact_motion_readability_guard.rally_flag_pennant_pixel_budget <= 60'
  'first_contact_motion_readability_guard.rally_flag_pennant_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_formation_join_micro_pips")'
  'first_contact_motion_readability_guard.formation_join_pip_count == 3'
  'first_contact_motion_readability_guard.formation_join_pip_width_px == 4'
  'first_contact_motion_readability_guard.formation_join_pip_height_px == 2'
  'first_contact_motion_readability_guard.formation_join_pip_pixel_budget <= 24'
  'first_contact_motion_readability_guard.formation_join_pip_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_shield_charge_micro_arcs")'
  'first_contact_motion_readability_guard.shield_charge_arc_count == 3'
  'first_contact_motion_readability_guard.shield_charge_arc_width_px == 10'
  'first_contact_motion_readability_guard.shield_charge_arc_height_px == 2'
  'first_contact_motion_readability_guard.shield_charge_arc_pixel_budget <= 60'
  'first_contact_motion_readability_guard.shield_charge_arc_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_sensor_sweep_micro_ticks")'
  'first_contact_motion_readability_guard.sensor_sweep_tick_count == 3'
  'first_contact_motion_readability_guard.sensor_sweep_tick_width_px == 8'
  'first_contact_motion_readability_guard.sensor_sweep_tick_height_px == 2'
  'first_contact_motion_readability_guard.sensor_sweep_tick_pixel_budget <= 48'
  'first_contact_motion_readability_guard.sensor_sweep_tick_gate == true'
  'first_contact_motion_readability_guard.combat_phase_motion_signatures | index("player_screen_combat_hit_micro_sparks")'
  'first_contact_motion_readability_guard.combat_hit_flash_site_count == 4'
  'first_contact_motion_readability_guard.combat_hit_flash_sparks_per_site == 2'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_count == 8'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_width_px == 6'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_height_px == 2'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_pixel_budget <= 96'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_gate == true'
  'first_contact_motion_readability_guard.command_feedback_motion_signatures | index("command_feedback_panel_micro_cues")'
  'first_contact_motion_readability_guard.feedback_panel_cue_count == 8'
  'first_contact_motion_readability_guard.feedback_panel_cue_width_px == 6'
  'first_contact_motion_readability_guard.feedback_panel_cue_height_px == 2'
  'first_contact_motion_readability_guard.feedback_panel_cue_pixel_budget <= 96'
  'first_contact_motion_readability_guard.command_feedback_motion_signatures | index("command_feedback_progress_micro_pips")'
  'first_contact_motion_readability_guard.feedback_progress_pip_slot_count == 7'
  'first_contact_motion_readability_guard.feedback_ack_progress_pip_count == 6'
  'first_contact_motion_readability_guard.feedback_cooldown_pip_count == 2'
  'first_contact_motion_readability_guard.feedback_progress_pip_count == 8'
  'first_contact_motion_readability_guard.feedback_progress_pip_width_px == 6'
  'first_contact_motion_readability_guard.feedback_progress_pip_height_px == 2'
  'first_contact_motion_readability_guard.feedback_progress_pip_pixel_budget <= 96'
  'first_contact_motion_readability_guard.feedback_panel_micro_cue_gate == true'
  'first_contact_motion_readability_guard.feedback_progress_micro_pip_gate == true'
  'first_contact_terminal_legibility_guard.terminal_quiet_cue_width_px == 6'
  'first_contact_terminal_legibility_guard.terminal_quiet_cue_height_px == 2'
  'first_contact_terminal_legibility_guard.terminal_quiet_cues_per_tile == 2'
  'first_contact_terminal_legibility_guard.target_quiet_fill_pixel_budget == 0'
  'first_contact_terminal_legibility_guard.blocked_quiet_fill_pixel_budget == 0'
  'first_contact_terminal_legibility_guard.target_quiet_pixel_budget <= 120'
  'first_contact_terminal_legibility_guard.blocked_quiet_pixel_budget <= 192'
  'first_contact_terminal_legibility_guard.terminal_signatures | index("target_terminal_micro_edge_cues")'
  'first_contact_terminal_legibility_guard.terminal_signatures | index("blocked_terminal_micro_edge_cues")'
  '.rts_data_map_model_rule_count == 19'
  '.runtime_player_screen_visible_tile_count == 64'
  '.offline_lobby_ready_label_count == 4'
)

readiness_lines=(
  'rts_first_contact_basin_spec_contract_field_count: $rts_first_contact_basin_spec[0].contract_field_count'
  'rts_first_contact_basin_spec_guard_object_count: $rts_first_contact_basin_spec[0].guard_object_count'
  'rts_first_contact_basin_spec_map_model_rule_count: $rts_first_contact_basin_spec[0].rts_data_map_model_rule_count'
  'rts_first_contact_basin_spec_runtime_command_queue_count: $rts_first_contact_basin_spec[0].runtime_player_screen_command_queue_count'
  'rts_first_contact_basin_spec_offline_ready_label_count: $rts_first_contact_basin_spec[0].offline_lobby_ready_label_count'
  '.headline.rts_first_contact_basin_spec_contract_field_count == 32'
  '.headline.rts_first_contact_basin_spec_top_level_gate_count == 46'
  '.headline.rts_first_contact_basin_spec_runtime_visible_tile_count == 64'
  '.headline.rts_first_contact_basin_spec_offline_ready_label_count == 4'
)

integrity_lines=(
  'first_contact_basin_spec_count_semantics'
  'runtime_player_screen_command_queue_count == ((.rts_bevy_runtime_player_screen_application.command_queue // []) | length)'
  'offline_lobby_ready_label_count == ((.rts_online_offline_adapter_lobby_ready.ready_state_labels // []) | length)'
  'first_contact_marker_budget_guard.non_focus_owner_identity_colors == ["457953","6a5e4b"]'
  'first_contact_marker_budget_guard.non_focus_owner_identity_gate == true'
  'first_contact_marker_budget_guard.player_screen_relay_identity_rail_count == 6'
  'first_contact_marker_budget_guard.player_screen_relay_identity_rail_width_px == 16'
  'first_contact_marker_budget_guard.player_screen_relay_identity_rail_height_px == 2'
  'first_contact_marker_budget_guard.player_screen_relay_identity_rail_gate == true'
  'first_contact_marker_budget_guard.player_screen_legacy_midfield_status_bar_pixel_budget == 0'
  'first_contact_marker_budget_guard.player_screen_legacy_midfield_status_bar_gate == true'
  'first_contact_marker_budget_guard.player_screen_tactical_track_count == 1'
  'first_contact_marker_budget_guard.player_screen_secondary_tactical_track_count == 0'
  'first_contact_marker_budget_guard.player_screen_tactical_track_gate == true'
  'first_contact_marker_budget_guard.hover_route_path_marker_count == 8'
  'first_contact_marker_budget_guard.player_screen_hover_route_path_marker_count == 0'
  'first_contact_marker_budget_guard.player_screen_hover_route_path_gate == true'
  'first_contact_motion_readability_guard.opening_action_motion_signatures | index("opening_action_path_micro_dots")'
  'first_contact_motion_readability_guard.opening_action_path_count == 3'
  'first_contact_motion_readability_guard.opening_action_path_step_count == 24'
  'first_contact_motion_readability_guard.opening_action_path_dot_width_px == 2'
  'first_contact_motion_readability_guard.opening_action_path_dot_height_px == 2'
  'first_contact_motion_readability_guard.opening_action_path_pixel_budget <= 96'
  'first_contact_motion_readability_guard.opening_action_path_gate == true'
  'first_contact_motion_readability_guard.unit_state_motion_signatures | index("player_screen_production_training_micro_sparks")'
  'first_contact_motion_readability_guard.production_training_spark_count == 3'
  'first_contact_motion_readability_guard.production_training_spark_width_px == 4'
  'first_contact_motion_readability_guard.production_training_spark_height_px == 2'
  'first_contact_motion_readability_guard.production_training_spark_pixel_budget <= 24'
  'first_contact_motion_readability_guard.production_training_spark_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_animation_training_lane_micro_ticks")'
  'first_contact_motion_readability_guard.animation_training_tick_count == 3'
  'first_contact_motion_readability_guard.animation_training_tick_width_px == 4'
  'first_contact_motion_readability_guard.animation_training_tick_height_px == 2'
  'first_contact_motion_readability_guard.animation_training_tick_pixel_budget <= 24'
  'first_contact_motion_readability_guard.animation_training_tick_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_harvest_tool_swing_micro_sparks")'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_count == 6'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_width_px == 6'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_height_px == 2'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_pixel_budget <= 72'
  'first_contact_motion_readability_guard.harvest_tool_swing_spark_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_spawn_door_micro_shutters")'
  'first_contact_motion_readability_guard.spawn_door_shutter_count == 7'
  'first_contact_motion_readability_guard.spawn_door_shutter_width_px == 4'
  'first_contact_motion_readability_guard.spawn_door_shutter_height_px == 2'
  'first_contact_motion_readability_guard.spawn_door_shutter_pixel_budget <= 56'
  'first_contact_motion_readability_guard.spawn_door_shutter_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_rally_flag_micro_pennants")'
  'first_contact_motion_readability_guard.rally_flag_pennant_count == 5'
  'first_contact_motion_readability_guard.rally_flag_pennant_width_px == 6'
  'first_contact_motion_readability_guard.rally_flag_pennant_height_px == 2'
  'first_contact_motion_readability_guard.rally_flag_pennant_pixel_budget <= 60'
  'first_contact_motion_readability_guard.rally_flag_pennant_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_formation_join_micro_pips")'
  'first_contact_motion_readability_guard.formation_join_pip_count == 3'
  'first_contact_motion_readability_guard.formation_join_pip_width_px == 4'
  'first_contact_motion_readability_guard.formation_join_pip_height_px == 2'
  'first_contact_motion_readability_guard.formation_join_pip_pixel_budget <= 24'
  'first_contact_motion_readability_guard.formation_join_pip_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_shield_charge_micro_arcs")'
  'first_contact_motion_readability_guard.shield_charge_arc_count == 3'
  'first_contact_motion_readability_guard.shield_charge_arc_width_px == 10'
  'first_contact_motion_readability_guard.shield_charge_arc_height_px == 2'
  'first_contact_motion_readability_guard.shield_charge_arc_pixel_budget <= 60'
  'first_contact_motion_readability_guard.shield_charge_arc_gate == true'
  'first_contact_motion_readability_guard.player_screen_animation_signatures | index("player_screen_sensor_sweep_micro_ticks")'
  'first_contact_motion_readability_guard.sensor_sweep_tick_count == 3'
  'first_contact_motion_readability_guard.sensor_sweep_tick_width_px == 8'
  'first_contact_motion_readability_guard.sensor_sweep_tick_height_px == 2'
  'first_contact_motion_readability_guard.sensor_sweep_tick_pixel_budget <= 48'
  'first_contact_motion_readability_guard.sensor_sweep_tick_gate == true'
  'first_contact_motion_readability_guard.combat_phase_motion_signatures | index("player_screen_combat_hit_micro_sparks")'
  'first_contact_motion_readability_guard.combat_hit_flash_site_count == 4'
  'first_contact_motion_readability_guard.combat_hit_flash_sparks_per_site == 2'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_count == 8'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_width_px == 6'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_height_px == 2'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_pixel_budget <= 96'
  'first_contact_motion_readability_guard.combat_hit_flash_spark_gate == true'
  'first_contact_motion_readability_guard.command_feedback_motion_signatures | index("command_feedback_panel_micro_cues")'
  'first_contact_motion_readability_guard.feedback_panel_cue_count == 8'
  'first_contact_motion_readability_guard.feedback_panel_cue_width_px == 6'
  'first_contact_motion_readability_guard.feedback_panel_cue_height_px == 2'
  'first_contact_motion_readability_guard.feedback_panel_cue_pixel_budget <= 96'
  'first_contact_motion_readability_guard.command_feedback_motion_signatures | index("command_feedback_progress_micro_pips")'
  'first_contact_motion_readability_guard.feedback_progress_pip_slot_count == 7'
  'first_contact_motion_readability_guard.feedback_ack_progress_pip_count == 6'
  'first_contact_motion_readability_guard.feedback_cooldown_pip_count == 2'
  'first_contact_motion_readability_guard.feedback_progress_pip_count == 8'
  'first_contact_motion_readability_guard.feedback_progress_pip_width_px == 6'
  'first_contact_motion_readability_guard.feedback_progress_pip_height_px == 2'
  'first_contact_motion_readability_guard.feedback_progress_pip_pixel_budget <= 96'
  'first_contact_motion_readability_guard.feedback_panel_micro_cue_gate == true'
  'first_contact_motion_readability_guard.feedback_progress_micro_pip_gate == true'
  'first_contact_terminal_legibility_guard.terminal_quiet_cue_width_px == 6'
  'first_contact_terminal_legibility_guard.terminal_quiet_cue_height_px == 2'
  'first_contact_terminal_legibility_guard.terminal_quiet_cues_per_tile == 2'
  'first_contact_terminal_legibility_guard.target_quiet_fill_pixel_budget == 0'
  'first_contact_terminal_legibility_guard.blocked_quiet_fill_pixel_budget == 0'
  'first_contact_terminal_legibility_guard.target_quiet_pixel_budget <= 120'
  'first_contact_terminal_legibility_guard.blocked_quiet_pixel_budget <= 192'
  'first_contact_terminal_legibility_guard.terminal_signatures | index("target_terminal_micro_edge_cues")'
  'first_contact_terminal_legibility_guard.terminal_signatures | index("blocked_terminal_micro_edge_cues")'
  'First Contact Basin packet artifact exposes top-level contract, guard, map-model, runtime, online/offline adapter counts bound to nested structures'
  'first_contact_basin_spec_semantics_first_contact_basin_spec_count_semantics'
)

fixture_lines=(
  'contract_field_count = ([keys[] | select(endswith("_contract"))] | length)'
  'runtime_player_screen_command_queue_count = ((.rts_bevy_runtime_player_screen_application.command_queue // []) | length)'
  'offline_lobby_ready_label_count = ((.rts_online_offline_adapter_lobby_ready.ready_state_labels // []) | length)'
  'non_focus_owner_identity_colors: ["457953", "6a5e4b"]'
  'non_focus_owner_identity_gate: true'
  'player_screen_relay_identity_rail_count: 6'
  'player_screen_relay_identity_rail_width_px: 16'
  'player_screen_relay_identity_rail_height_px: 2'
  'player_screen_relay_identity_rail_gate: true'
  'player_screen_legacy_midfield_status_bar_pixel_budget: 0'
  'player_screen_legacy_midfield_status_bar_gate: true'
  'player_screen_tactical_track_count: 1'
  'player_screen_secondary_tactical_track_count: 0'
  'player_screen_tactical_track_gate: true'
  'hover_route_path_marker_count: 8'
  'player_screen_hover_route_path_marker_count: 0'
  'player_screen_hover_route_path_gate: true'
  'opening_action_path_micro_dots'
  'opening_action_path_count: 3'
  'opening_action_path_step_count: 24'
  'opening_action_path_dot_width_px: 2'
  'opening_action_path_dot_height_px: 2'
  'opening_action_path_pixel_budget: 96'
  'opening_action_path_gate: true'
  'player_screen_production_training_micro_sparks'
  'production_training_spark_count: 3'
  'production_training_spark_width_px: 4'
  'production_training_spark_height_px: 2'
  'production_training_spark_pixel_budget: 24'
  'production_training_spark_gate: true'
  'player_screen_animation_training_lane_micro_ticks'
  'animation_training_tick_count: 3'
  'animation_training_tick_width_px: 4'
  'animation_training_tick_height_px: 2'
  'animation_training_tick_pixel_budget: 24'
  'animation_training_tick_gate: true'
  'player_screen_harvest_tool_swing_micro_sparks'
  'harvest_tool_swing_spark_count: 6'
  'harvest_tool_swing_spark_width_px: 6'
  'harvest_tool_swing_spark_height_px: 2'
  'harvest_tool_swing_spark_pixel_budget: 72'
  'harvest_tool_swing_spark_gate: true'
  'player_screen_spawn_door_micro_shutters'
  'spawn_door_shutter_count: 7'
  'spawn_door_shutter_width_px: 4'
  'spawn_door_shutter_height_px: 2'
  'spawn_door_shutter_pixel_budget: 56'
  'spawn_door_shutter_gate: true'
  'player_screen_rally_flag_micro_pennants'
  'rally_flag_pennant_count: 5'
  'rally_flag_pennant_width_px: 6'
  'rally_flag_pennant_height_px: 2'
  'rally_flag_pennant_pixel_budget: 60'
  'rally_flag_pennant_gate: true'
  'player_screen_formation_join_micro_pips'
  'formation_join_pip_count: 3'
  'formation_join_pip_width_px: 4'
  'formation_join_pip_height_px: 2'
  'formation_join_pip_pixel_budget: 24'
  'formation_join_pip_gate: true'
  'player_screen_shield_charge_micro_arcs'
  'shield_charge_arc_count: 3'
  'shield_charge_arc_width_px: 10'
  'shield_charge_arc_height_px: 2'
  'shield_charge_arc_pixel_budget: 60'
  'shield_charge_arc_gate: true'
  'player_screen_sensor_sweep_micro_ticks'
  'sensor_sweep_tick_count: 3'
  'sensor_sweep_tick_width_px: 8'
  'sensor_sweep_tick_height_px: 2'
  'sensor_sweep_tick_pixel_budget: 48'
  'sensor_sweep_tick_gate: true'
  'player_screen_combat_hit_micro_sparks'
  'combat_hit_flash_site_count: 4'
  'combat_hit_flash_sparks_per_site: 2'
  'combat_hit_flash_spark_count: 8'
  'combat_hit_flash_spark_width_px: 6'
  'combat_hit_flash_spark_height_px: 2'
  'combat_hit_flash_spark_pixel_budget: 96'
  'combat_hit_flash_spark_gate: true'
  'command_feedback_panel_micro_cues'
  'feedback_panel_cue_count: 8'
  'feedback_panel_cue_width_px: 6'
  'feedback_panel_cue_height_px: 2'
  'feedback_panel_cue_pixel_budget: 96'
  'feedback_panel_micro_cue_gate: true'
  'command_feedback_progress_micro_pips'
  'feedback_progress_pip_slot_count: 7'
  'feedback_ack_progress_pip_count: 6'
  'feedback_cooldown_pip_count: 2'
  'feedback_progress_pip_count: 8'
  'feedback_progress_pip_width_px: 6'
  'feedback_progress_pip_height_px: 2'
  'feedback_progress_pip_pixel_budget: 96'
  'feedback_progress_micro_pip_gate: true'
  'terminal_quiet_cue_width_px: 6'
  'terminal_quiet_cue_height_px: 2'
  'terminal_quiet_cues_per_tile: 2'
  'target_quiet_fill_pixel_budget: 0'
  'blocked_quiet_fill_pixel_budget: 0'
  'target_quiet_pixel_budget: 120'
  'blocked_quiet_pixel_budget: 192'
  'target_terminal_micro_edge_cues'
  'blocked_terminal_micro_edge_cues'
)

for line in "${basin_lines[@]}"; do
  require_line "$BASIN_SCRIPT" "$line"
done

for line in "${readiness_lines[@]}"; do
  require_line "$READINESS_SCRIPT" "$line"
done

for line in "${integrity_lines[@]}"; do
  require_line "$INTEGRITY_SCRIPT" "$line"
done

for line in "${fixture_lines[@]}"; do
  require_line "$FIXTURE_LIB" "$line"
done

echo "[PASS] classic RTS First Contact Basin spec script keeps atomic refresh, top-level basin counts, readiness headline, packet-integrity semantics, and semantic fixtures"
