#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_bevy_player_ui_rescue.sh"
RUST="$ROOT/trillionnium/crates/trnm-world-bevy/src/lib.rs"
MAIN="$ROOT/trillionnium/crates/trnm-world-bevy/src/main.rs"

required_lines=(
  'trillionnium_world_bevy_player_ui_rescue_v1'
  'bevy-player-ui-rescue.json'
  'player_ui_rescue_green'
  'player-ui-rescue'
  'PLAYER ROUTE |'
  'NEXT STEP:'
  'PROGRESS:'
  'PLAYER ACTIONS | READY:'
  'DEV INPUT |'
  'button_wall_deprioritized_gate'
  'event_log_separation_gate'
  'contextual_deck_layout_gate'
  'right_rail_summary_gate'
  'top_hud_density_gate'
  'toast_lane_gate'
  'visual_hierarchy_gate'
  'art_direction_gate'
  'scene_readability_gate'
  'sprite_asset_quality_gate'
  'map_model_visual_gate'
  'map_occlusion_gate'
  'ui_polish_gate'
  'tileset_polish_gate'
  'authored_art_pack_gate'
  'hidden_button_count >= 24'
  'deprioritized_button_count'
  'player_deck_visible_count <= 32'
  'visible_quest_summary_text'
  'visible_stats_summary_text'
  'visible_bag_summary_text'
  'visible_event_summary_text'
  'primary_cta_text'
  'movement_hint_text'
  'active_action_row_count'
  'art_direction_policy'
  'map_focus_glow'
  'primary_cta_gold_glow'
  'action_deck_depth_shadow'
  'warm_gold'
  'cyan_focus'
  'scene_readability_policy'
  'player_selection_ring'
  'npc_interaction_ring'
  'enemy_threat_ring'
  'objective_route_arrow'
  'loot_pickup_sparkle'
  'combat_hit_splash'
  'player_identity'
  'combat_feedback'
  'sprite_asset_policy'
  'player_body_layer'
  'actor_shadow'
  'actor_body'
  'npc_dialogue_badge'
  'enemy_hp_badge'
  'loot_pickup_badge'
  'combat_hit_feedback_marker'
  'map_model_visual_policy'
  'building_mass'
  'walkable_road_path'
  'greenery_cluster'
  'terrain_zone_surface'
  'map_pack modeling gate'
  'map_occlusion_policy'
  'weighted_ratio <= 0.10'
  'max_panel_alpha <= 0.38'
  'edge_dialogue_hint'
  'edge_scene_hint'
  'edge_step_hint'
  'edge_combat_hint'
  'bottom_story_summary'
  'ui_polish_policy'
  'top_hud'
  'right_rail'
  'action_deck'
  'movement_cluster'
  'primary_cta'
  'hud_compact'
  'summary_card'
  'action_deck_container'
  'visual_priorities'
  'tileset_polish_policy'
  'authored_art_pack_policy'
  'city_ground_tileset_v1'
  'road_tileset_v1'
  'building_tileset_v1'
  'greenery_tileset_v1'
  'water_tileset_v1'
  'hud_icon_tileset_v1'
  'trnm_world_authored_art_pack_v1'
  'terrain_tile'
  'road_tile'
  'building_tile'
  'foliage_sprite'
  'water_tile'
  'hud_icon'
  'hud_glyph'
  'actor_sprite'
  'feedback_glyph'
  'tile_sprite_slot'
  'local_authored_primitive_manifest_v1'
  'project_owned_internal_placeholder'
  'road_edge_highlight'
  'building_roof_cap'
  'greenery_canopy_cluster'
  'water_edge_shimmer'
  'primary_cta_glyph'
  'cta_arrow_marker'
  'feedback_banner_font_size <= 9'
  'feedback_banner_y > -100'
  'CHECKLIST") | not'
  'android_s5_real_device_claimed == false'
  'external_evidence_ignored_for_current_player_ui_rescue_pass == true'
  'public_launch_ready == false'
  'production_ready_ui_claimed == false'
  'screen_for_screen_openra_ui_claimed == false'
  'openra_engine_port_claimed == false'
  'warcraft_iii_asset_copied == false'
  'openra_asset_copied == false'
  'third_party_asset_copied == false'
)

for line in "${required_lines[@]}"; do
  if ! grep -Fq -- "$line" "$SCRIPT" "$RUST" "$MAIN"; then
    echo "[FAIL] player UI rescue contract missing line: $line" >&2
    exit 1
  fi
done

echo "[PASS] player UI rescue gate keeps player-first route/action/status layer and demotes debug text"
