#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_release_review_packet_integrity.sh"

required_lines=(
  'trillionnium_world_release_review_packet_integrity_v1'
  'check_trillionnium_world_release_review_packet.sh'
  'release-review-packet-integrity.json'
  'release-review-packet-integrity-packet.log'
  'release_review_acceptance_lock.sh'
  'trnm_acquire_release_review_acceptance_lock "$ACCEPTANCE_DIR"'
  'TRILLIONNIUM_WORLD_RELEASE_REVIEW_PACKET_JSON'
  'TRILLIONNIUM_WORLD_RELEASE_REVIEW_PACKET_MD'
  'TRILLIONNIUM_WORLD_RELEASE_REVIEW_PACKET_LOG'
  '--no-refresh'
  'PACKET_ARTIFACTS_TSV'
  'PACKET_ARTIFACT_PATH_BY_ID'
  'load_packet_artifacts'
  'sha256sum'
  'bytes_match'
  'contract_match'
  'status_match'
  '([120, 121, 124, 126, 127, 128] | index($count)) != null'
  'expected one hundred twenty, one hundred twenty-one, one hundred twenty-four, one hundred twenty-six, one hundred twenty-seven, or one hundred twenty-eight artifacts including visible button hit-test map, live-window mouse hit-test sequence, classic playtest launcher, playtest handoff readiness/packet/Markdown, First Contact Basin source-manifest spec, full screen/UI replication, shell/meta UI replication, match setup UI replication, campaign outcome UI readiness, campaign UI continuity JSON/PPM, in-match HUD/state replication, session state continuity, combat readability/pressure readiness, camera/minimap sync JSON/PPM, full-game visual/UI replication JSON/PPM, OpenRA screen-for-screen UI replication JSON/PPM, OpenRA engine port asset parity JSON/PPM'
  'first_contact_basin_offline_adapter_semantics'
  'trnm_rts_online_offline_adapter_v1'
  'trnm_rts_online_offline_adapter_local_replay_v1'
  'trnm_rts_online_offline_adapter_runtime_handoff_v1'
  'trillionnium_world_bevy_first_contact_offline_adapter_consumption_v1'
  'local_runtime_handoff.accepted_runtime_command_labels == ["move:8,4"]'
  'accepted_runtime_command_labels == ["move:8,4"]'
  'adapter_runtime_handoff_contract == "trnm_rts_online_offline_adapter_runtime_handoff_v1"'
  'rejected_commands_suppressed == true'
  'runtime_command_stamp_source == "trnm-rts-online:offline_loopback_authority"'
  'runtime_player_screen_review.map_scene == "first_contact_basin"'
  'runtime_player_screen_review.command_queue == ["move:8,4"]'
  'local_session_handoff_gate == true'
  'player_screen_review_gate == true'
  'runtime_path == "classic_first_contact_player_screen_runtime -> NativeFirstPlayableRuntime local player-screen/session handoff"'
  'no_network_claim_gate == true'
  'keyboard_replay_semantics'
  'native_bevy_keyboard_replay'
  'trillionnium_world_bevy_build_branch_title_route_all_branch_keyboard_replay_v1'
  'keyboard_replay_green'
  'all_branch_keyboard_loop_contract_green == true'
  'branch_count == 3'
  'all_branch_replay_gate == true'
  'recorded_sequence_count == 10'
  'recorded_sequence_count == 8'
  'recorded_sequence_count == 7'
  'force-mastery-signet'
  'agility-mastery-signet'
  'craft-mastery-signet'
  'external_evidence_ignored_for_current_keyboard_replay_pass == true'
  'classic_animation_preview_semantics'
  'classic_animation_preview_ppm_semantics'
  'classic_animation_selector_semantics'
  'native_bevy_classic_animation_preview'
  'native_bevy_classic_animation_preview_ppm'
  'native_bevy_classic_animation_selector'
  'trillionnium_world_bevy_classic_animation_preview_v1'
  'trillionnium_world_bevy_classic_animation_selector_v1'
  'classic_animation_preview_green'
  'classic_animation_selector_green'
  'clip_count >= 4'
  'rendered_frame_slot_count >= 15'
  'all_clip_refs_valid == true'
  'actor_player_walk_south_1'
  'actor_mentor_talk'
  'actor_enemy_attack'
  'actor_enemy_hit'
  'selector_case_gate == true'
  'selected_frame_manifest_gate == true'
  'animation_transition_gate == true'
  'mentor_dialogue_talk'
  'enemy_combat_attack'
  'enemy_combat_hit'
  'objective_marker_pulse'
  'external_evidence_ignored_for_current_animation_preview_pass == true'
  'external_evidence_ignored_for_current_animation_selector_pass == true'
  '640 448'
  'classic_player_motion_probe_semantics'
  'classic_player_motion_probe_ppm_semantics'
  'native_bevy_classic_player_motion_probe'
  'native_bevy_classic_player_motion_probe_ppm'
  'trillionnium_world_bevy_classic_player_motion_probe_v1'
  'classic_player_motion_probe_green'
  'sample_count == 8'
  'accepted_input_count == 8'
  'direction_coverage_gate == true'
  'frame_match_gate == true'
  'manifest_frame_gate == true'
  'actor_player_walk_north_1'
  'actor_player_walk_east_1'
  'actor_player_walk_south_1'
  'actor_player_walk_west_1'
  'external_evidence_ignored_for_current_player_motion_probe_pass == true'
  '640 192'
  'action_coach_semantics'
  'native_bevy_action_coach'
  'trillionnium_world_bevy_action_coach_v1'
  'action_coach_green'
  'coach_stage_gate == true'
  'enter_execution_gate == true'
  'final_next_gate == true'
  'input_hint_contract_gate == true'
  'external_evidence_ignored_for_current_action_coach_pass == true'
  'player_hud_debug_layer_semantics'
  'native_bevy_player_hud_debug_layer'
  'trillionnium_world_bevy_player_hud_debug_layer_v1'
  'player_hud_debug_layer_green'
  'player_hud_gate == true'
  'quest_layer_gate == true'
  'debug_layer_gate == true'
  'scene_debug_gate == true'
  'input_hint_gate == true'
  'panel_layer_gate == true'
  'runtime_gate == true'
  'external_evidence_ignored_for_current_player_hud_pass == true'
  'player_ui_rescue_semantics'
  'native_bevy_player_ui_rescue'
  'trillionnium_world_bevy_player_ui_rescue_v1'
  'player_ui_rescue_green'
  'player_status_gate == true'
  'route_panel_gate == true'
  'quest_panel_gate == true'
  'action_layer_gate == true'
  'debug_deprioritized_gate == true'
  'event_log_separation_gate == true'
  'button_wall_deprioritized_gate == true'
  'contextual_deck_layout_gate == true'
  'right_rail_summary_gate == true'
  'top_hud_density_gate == true'
  'toast_lane_gate == true'
  'visual_hierarchy_gate == true'
  'art_direction_gate == true'
  'scene_readability_gate == true'
  'sprite_asset_quality_gate == true'
  'map_model_visual_gate == true'
  'map_occlusion_gate == true'
  'ui_polish_gate == true'
  'tileset_polish_gate == true'
  'authored_art_pack_gate == true'
  'external_evidence_ignored_for_current_player_ui_rescue_pass == true'
  'public_launch_ready == false'
  'production_ready_ui_claimed == false'
  'screen_for_screen_openra_ui_claimed == false'
  'openra_engine_port_claimed == false'
  'warcraft_iii_asset_copied == false'
  'openra_asset_copied == false'
  'third_party_asset_copied == false'
  'live_window_screenshot_sequence_semantics'
  'native_bevy_live_window_screenshot_sequence'
  'trillionnium_world_bevy_live_window_screenshot_sequence_v1'
  'live_window_screenshot_sequence_green'
  'host_window_gate == true'
  'frame_sequence_gate == true'
  'runtime_texture_manifest_hash_gate == true'
  'runtime_texture_sprite_asset_binding_gate == true'
  'internal_live_window_screenshot_sequence_claimed == true'
  'external_evidence_ignored_for_current_live_window_pass == true'
  'visible_button_hit_test_map_semantics'
  'native_bevy_visible_button_hit_test_map'
  'require_artifact_json_expr_when_packet_count_at_least visible_button_hit_test_map_semantics native_bevy_visible_button_hit_test_map 128'
  'trillionnium_world_bevy_visible_button_hit_test_map_v1'
  'trillionnium_world_bevy_live_window_mouse_hit_test_sequence_v1'
  'client_window_pixels_from_top_left'
  'state_specific_visible_button'
  'core_route_actions_reflowed'
  'visible button hit-test map packet artifact binds first-minute button centers'
  'live_window_mouse_hit_test_sequence_semantics'
  'native_bevy_live_window_mouse_hit_test_sequence'
  'trillionnium_world_bevy_live_window_mouse_hit_test_sequence_v1'
  'trillionnium_world_bevy_visible_button_hit_test_map_v1'
  'trillionnium_world_bevy_runtime_probe_v1'
  'hit_test_map_gate == true'
  'runtime_feedback_gate == true'
  'mouse_event_count_gate == true'
  'slot_write_gate == true'
  'XTest mouse button events click Bevy-exposed client hit centers'
  'state_specific_visible_button'
  'core_route_actions_reflowed'
  'CONTINUE:SESSION'
  'sprite_texture_sampling_semantics'
  'native_bevy_sprite_texture_sampling'
  'trillionnium_world_bevy_sprite_texture_sampling_v1'
  'sprite_texture_sampling_green'
  'runtime_texture_manifest_probe_contract == "trillionnium_world_bevy_runtime_texture_manifest_probe_v1"'
  'asset_store_registration_contract == "trillionnium_world_bevy_asset_store_registration_v1"'
  'sprite_asset_binding_contract == "trillionnium_world_bevy_sprite_asset_binding_v1"'
  'four_layer_texture_sampling_gate == true'
  'global_unique_texture_color_gate == true'
  'sampled_surface_count >= 24'
  'host_side_cpu_texture_sampling_claimed == true'
  'external_evidence_ignored_for_current_sprite_texture_pass == true'
  'live_window_sampled_texture_correlation_semantics'
  'native_bevy_live_window_sampled_texture_correlation'
  'trillionnium_world_bevy_live_window_sampled_texture_correlation_v1'
  'live_window_sampled_texture_correlation_green'
  'four_layer_sampled_live_correlation_gate == true'
  'same_runtime_manifest_hash_gate == true'
  'internal_live_window_sampled_texture_correlation_claimed == true'
  'external_evidence_ignored_for_current_sampled_texture_pass == true'
  'render_asset_eligibility_semantics'
  'native_bevy_render_asset_eligibility'
  'trillionnium_world_bevy_render_asset_eligibility_v1'
  'render_asset_eligibility_green'
  'runtime_texture_asset_contract == "trillionnium_world_bevy_runtime_texture_asset_v1"'
  'sprite_texture_sampling_contract == "trillionnium_world_bevy_sprite_texture_sampling_v1"'
  'live_window_sampled_texture_correlation_contract == "trillionnium_world_bevy_live_window_sampled_texture_correlation_v1"'
  'render_asset_usage_gate == true'
  'image_descriptor_render_eligibility_gate == true'
  'atlas_layout_render_eligibility_gate == true'
  'sprite_render_reference_gate == true'
  'image_asset_usage_main_world == true'
  'image_asset_usage_render_world == true'
  'host_side_render_asset_eligibility_claimed == true'
  'external_evidence_ignored_for_current_render_asset_pass == true'
  'render_world_extraction_completed_claimed == false'
  'cex_adapter_readiness_semantics'
  'cex_adapter_readiness'
  'trillionnium_world_cex_adapter_readiness_gate_v1'
  'cex_adapter_readiness_green'
  'trillionnium_world_crates_do_not_import_cex_service_internals'
  'cex_runtime_exports_json_evidence_for_trillionnium_release_review'
  'cex_trillionnium_world_production_adapter_v1'
  'trillionnium_world_runtime_adapter_v1'
  'cex_production_adapter_bridge_ready'
  'cex_production_impls_connected_to_standalone_traits'
  'consumer_entry_api_depends_on_trnm_world_api_without_trnm_world_importing_cex'
  'route_record_total >= 7000'
  'world_node_count >= 20'
  'counts_ok == true'
  's5_real_device_evidence_semantics'
  's5_real_device_evidence'
  'trillionnium_world_s5_real_device_evidence_gate_v1'
  'blocked_no_connected_android_device'
  'host_side_replay_credit == false'
  'template_requires_real_s5_device_evidence'
  'real_device_screenshot'
  'real_device_gfxinfo_or_frame_stats'
  'real_device_cjk_display_input'
  'real_device_weak_network'
  'crash_free_logcat_window'
  'public_launch_readiness_semantics'
  'public_launch_readiness'
  'trillionnium_world_public_launch_readiness_v1'
  'blocked_missing_public_launch_evidence'
  'do_not_claim_public_launch_ready_without_native_bevy_local_playability_texture_sampling_render_asset_eligibility_real_device_map_pack_cohort_commercial_multi_node_and_public_deploy_evidence'
  'native_bevy_render_asset_eligibility'
  'host_side_render_asset_eligibility_not_render_world_extraction_or_gpu_upload'
  'runtime_clients_fetch_public_osm_directly == false'
  'public_launch_blocker_consistency_semantics'
  'public_launch_blocker_consistency'
  'trillionnium_world_public_launch_blocker_consistency_v1'
  'public_launch_blocker_consistency_green_with_public_launch_blockers'
  'public_launch_claimed == false'
  'public_launch_readiness_blockers_must_match_evidence_intake_items_and_field_level_validator_statuses'
  'unknown_readiness_blockers // [] | length'
  'blocked_missing_s5_real_device_evidence'
  'blocked_missing_production_map_pack_public_evidence'
  'blocked_missing_first_beta_cohort_evidence'
  'blocked_missing_commercial_launch_drill_evidence'
  'blocked_missing_multi_node_or_live_traffic_latency_evidence'
  'blocked_missing_public_network_live_exposure_evidence'
  'public_launch_evidence_intake_semantics'
  'public_launch_evidence_intake'
  'trillionnium_world_public_launch_evidence_intake_v1'
  'public_launch_evidence_intake_ready_for_operator_collection'
  'collect_real_external_public_launch_evidence_without_claiming_public_launch_ready_or_android_s5_real_device_ready'
  'public_launch_evidence_intake_markdown_semantics'
  'public_launch_evidence_intake_markdown'
  'Trillionnium World Public Launch Evidence Intake'
  'This is an intake/checklist artifact, not a public-launch approval.'
  'production_map_pack_public_evidence_collection_semantics'
  'production_map_pack_public_evidence_collection'
  'trillionnium_world_production_map_pack_public_evidence_collection_v1'
  'production_map_pack_public_evidence_collection_ready'
  'runtime_clients_fetch_public_osm_directly == false'
  'approved_production_map_source'
  'Only the validator can grant public launch credit after real external artifacts are attached.'
  'cohort_commercial_evidence_collection_semantics'
  'cohort_commercial_evidence_collection'
  'trillionnium_world_cohort_commercial_evidence_collection_v1'
  'cohort_commercial_evidence_collection_ready'
  'Use sanitized participant ids and evidence references.'
  'Do not store private personal data in templates.'
  'external_ops_evidence_collection_semantics'
  'external_ops_evidence_collection'
  'trillionnium_world_external_ops_evidence_collection_v1'
  'external_ops_evidence_collection_ready'
  'local_release_latency_drill_green'
  'It does not open a public network route.'
  'Local latency/deploy drills are useful but have no public-launch credit.'
  'production_map_pack_public_evidence_semantics'
  'production_map_pack_public_evidence'
  'trillionnium_world_production_map_pack_public_evidence_gate_v1'
  'only_when_status_is_production_map_pack_public_ready_green'
  'production_map_source_artifact_status == "missing"'
  'direct_public_osm_client_fetch_forbidden == true'
  'cohort_commercial_evidence_semantics'
  'cohort_commercial_evidence'
  'trillionnium_world_cohort_commercial_evidence_gate_v1'
  'participant_count == 0'
  'participants_match_count'
  'real_or_sanitized_commercial_signoff'
  'external_ops_evidence_semantics'
  'external_ops_evidence'
  'trillionnium_world_external_ops_evidence_gate_v1'
  'local_release_load_drill_only_not_multi_node_or_live_traffic'
  'live_public_exposure_performed_by_this_script == false'
  'node_count == 0'
  'public_launch_evidence_kit_semantics'
  'public_launch_evidence_kit'
  'trillionnium_world_public_launch_evidence_kit_v1'
  'public_launch_evidence_kit_ready_for_operator_collection'
  'operator_templates_must_exist_and_must_not_claim_green_until_real_external_evidence_passes_field_validators'
  'needs_collection_count == 6'
  'template_public_launch_credit == false'
  'public_launch_evidence_kit_markdown_semantics'
  'public_launch_evidence_kit_markdown'
  'Trillionnium World Public Launch Evidence Kit'
  'Templates are collection scaffolding only and carry no public-launch credit.'
  'public_launch_template_negative_fixtures_semantics'
  'public_launch_template_negative_fixtures'
  'trillionnium_world_public_launch_template_negative_fixtures_v1'
  'no_credit_templates_must_fail_strict_field_validators_before_public_launch_handoff'
  'template_count == 6'
  's5_real_device_template'
  'production_map_pack_template'
  'cohort_commercial_templates'
  'external_ops_templates'
  's5-device-evidence.template.json'
  'public-network-deploy-evidence.template.json'
  'public_launch_evidence_bundle_semantics'
  'public_launch_evidence_bundle'
  'trillionnium_world_public_launch_evidence_bundle_gate_v1'
  'public_launch_evidence_bundle_ready_for_real_evidence'
  'single_manifest_must_point_to_real_external_evidence_that_passes_all_field_validators_before_public_launch_credit'
  'public_launch_evidence_bundle_markdown_semantics'
  'public_launch_evidence_bundle_markdown'
  'Trillionnium World Public Launch Evidence Bundle'
  'Public launch credit requires the bundle status and all six field validators to be green.'
  'public_launch_bundle_negative_fixtures_semantics'
  'public_launch_bundle_negative_fixtures'
  'trillionnium_world_public_launch_bundle_negative_fixtures_v1'
  'fake_green_bundle_manifest_pointing_to_no_credit_templates_must_fail_require_ready'
  'public_launch_evidence_bundle_blocked_invalid_real_evidence'
  'expected_item_failure_count == 6'
  'public_launch_status_only_fixture_guard_semantics'
  'public_launch_status_only_fixture_guard'
  'trillionnium_world_public_launch_status_only_fixture_guard_v1'
  'status_only_green_fixtures_must_be_rejected_by_field_level_public_launch_evidence_validators'
  'result_count == 4'
  'failure_count == 0'
  's5_status_only_fixture'
  'production_map_pack_status_only_fixture'
  'cohort_commercial_status_only_fixture'
  'external_ops_status_only_fixture'
  'release_signoff_summary_semantics'
  'release_signoff_summary'
  'trillionnium_world_release_signoff_summary_v1'
  'native_bevy_keyboard_replay_action_coach_player_hud_live_screenshot_texture_sampling_correlation_render_asset_eligibility_and_cex_adapter_readiness_must_be_green_and_public_launch_readiness_must_consume_local_playability_before_release_review'
  'native_bevy_render_asset_eligibility.sprite_render_reference_count >= 32'
  'public_launch_consumes_local_playability.render_asset_eligibility == true'
  'local_drill_is_not_multi_node_or_live_traffic == true'
  'local_drill_is_not_public_network_exposure == true'
  'release_review_status_semantics'
  'release_review_status_json'
  'trillionnium_world_release_review_status_v1'
  'release_review_ready_public_launch_blocked'
  'trillionnium_world_release_review_status'
  'quickcheck_summary | endswith("release-review-quickcheck.json")'
  'signoff_summary | endswith("release-signoff-summary.json")'
  'ready_items | length) == 13'
  'blocked_items | length) == 6'
  'collect_real_external_public_launch_evidence'
  'blocked_until_real_external_evidence_is_attached'
  'release_review_status_markdown_semantics'
  'release_review_status_markdown'
  'Trillionnium World Release Review Status'
  'Still Requires Real External Evidence'
  'Public launch remains blocked until the external evidence above is attached.'
  'release_review_convergence_semantics'
  'release_review_convergence'
  'trillionnium_world_release_review_convergence_v1'
  'release_review_convergence_green_with_public_launch_blockers'
  'trillionnium_world_release_review_convergence'
  'release_review_status_must_refresh_and_scripts_docs_workflow_guards_evidence_outputs_must_remain_connected'
  'refreshed_status.json_path | endswith("release-review-status.json")'
  'checks | length) == 39'
  'cex_adapter_readiness_refresh'
  'release_review_status_refresh'
  'doc_README_md_convergence'
  'workflow_status_guard'
  'release_review_status_markdown_boundary'
  'release_review_status_markdown_cex_boundary'
  'local playability contracts are not blockers'
  'not real external public-launch evidence'
  'release_review_packet_convergence_log_semantics'
  'release_review_packet_convergence_log'
  'TRILLIONNIUM_WORLD_RELEASE_REVIEW_CONVERGENCE_GREEN_WITH_PUBLIC_LAUNCH_BLOCKERS'
  'release_review_quickcheck_semantics'
  'release_review_quickcheck'
  'trillionnium_world_release_review_quickcheck_v1'
  'release_review_quickcheck_green_with_public_launch_blockers'
  'refresh_public_launch_readiness_then_release_signoff_summary_and_fail_only_when_native_bevy_local_playability_texture_sampling_render_asset_eligibility_cex_adapter_readiness_or_consumption_is_broken_unless_require_ready_is_set'
  'refreshed_evidence.public_launch_readiness.summary_path'
  'refreshed_evidence.release_signoff_summary.summary_path'
  'native_bevy_render_asset_eligibility_ready == true'
  'public_launch_consumes_local_playability == true'
  'signoff_summary_blockers // [] | length'
  'map_modeling_gate_semantics'
  'map_modeling_gate'
  'trillionnium_world_map_modeling_gate_v1'
  'fixture_map_modeling_gate_green_with_public_data_blockers'
  'fixture_only == true'
  'runtime_clients_fetch_public_osm_directly == false'
  'public_network_ready == false'
  'building_mass_from_map_pack_node'
  'road_path_from_map_pack_edge'
  'greenery_cluster_from_map_pack_tags'
  'water_and_bank_surface'
  'signed production map_pack artifacts'
  'classic_asset_pack_semantics'
  'native_bevy_classic_asset_pack'
  'trillionnium_world_bevy_classic_asset_pack_v1'
  'renderer_uses_manifest == true'
  'directional_player_frame_gate == true'
  'project_owned_manifest_ppm_atlas_for_classic_low_spec_renderer_not_cex_runtime'
  'classic_manifest_lint_semantics'
  'native_bevy_classic_manifest_lint'
  'trillionnium_world_bevy_classic_manifest_lint_v1'
  'duplicate_frame_ids == []'
  'frame_overlap_detected == false'
  'role_counts.player_actor >= 12'
  'catalog_ready_gate == true'
  'classic_input_frame_budget_semantics'
  'native_bevy_classic_input_frame_budget'
  'trillionnium_world_bevy_classic_input_frame_budget_v1'
  'NativeControlAction::Move -> apply_live_native_action -> classic_draw_scene'
  'response_p95_budget_gate == true'
  'accepted_input_count == .sample_count'
  'actor_player_walk_east_2'
  'classic_render_budget_semantics'
  'native_bevy_classic_render_budget'
  'trillionnium_world_bevy_classic_render_budget_v1'
  'classic_cpu_ppm_minifb_low_spec'
  'frame_count >= 180'
  'p95_micros <= .p95_budget_micros'
  'max_micros <= .max_budget_micros'
  'classic_isometric_modeling_semantics'
  'classic_isometric_modeling_ppm_semantics'
  'native_bevy_classic_isometric_modeling'
  'native_bevy_classic_isometric_modeling_ppm'
  'trillionnium_world_bevy_classic_isometric_modeling_v1'
  'orthographic_isometric_2_5d'
  'rts_model_entity_count >= 13'
  'neutral_guard_worker_creep_units'
  'command_feedback_gate == true'
  '640 360'
  'classic_scene_preview_semantics'
  'classic_scene_preview_ppm_semantics'
  'native_bevy_classic_scene_preview'
  'native_bevy_classic_scene_preview_ppm'
  'trillionnium_world_bevy_classic_scene_preview_v1'
  'classic_scene_preview_green'
  'panel_count == 4'
  'renderer_manifest_gate == true'
  'dynamic_landmark_animation_gate == true'
  'actor_player_walk_east_1'
  'league_coliseum'
  'external_evidence_ignored_for_current_scene_preview_pass == true'
  '1280 720'
  'classic_model_catalog_semantics'
  'classic_model_catalog_ppm_semantics'
  'native_bevy_classic_model_catalog'
  'native_bevy_classic_model_catalog_ppm'
  'trillionnium_world_bevy_classic_model_catalog_v1'
  'classic_model_catalog_green'
  'rendered_frame_count == .frame_count'
  'role_counts.player_actor >= 12'
  'actor_mentor_talk'
  'marker_objective'
  'external_evidence_ignored_for_current_model_catalog_pass == true'
  '640 1056'
  'classic_renderer_probe_semantics'
  'classic_renderer_probe_ppm_semantics'
  'native_bevy_classic_renderer_probe'
  'native_bevy_classic_renderer_probe_ppm'
  'trillionnium_world_bevy_classic_renderer_probe_v1'
  'classic_renderer_probe_green'
  'player_frame_id == "actor_player_walk_east_1"'
  'hud_probe_gate == true'
  'player_frame_color_gate == true'
  'external_evidence_ignored_for_current_renderer_probe_pass == true'
  '640 360'
  'classic_playtest_runner_status_semantics'
  'native_bevy_classic_playtest_runner_status'
  'trillionnium_world_bevy_classic_playtest_runner_status_v1'
  'service.cpu_quota_per_sec_usec == "500ms"'
  'service.cpu_weight == "50"'
  'gates.cpu_budget_gate == true'
  'bounded CPUQuota/CPUWeight budget'
  'classic_playtest_launcher_semantics'
  'native_bevy_classic_playtest_launcher'
  'trillionnium_world_bevy_classic_playtest_launcher_v1'
  'player_entry.title_actions == ["CAMPAIGN:START", "CAMPAIGN:CONTINUE", "CAMPAIGN:REPLAY"]'
  'player_entry.followup_action_after_resume == "CONTINUE:SESSION"'
  'player_entry.final_open_world_handoff_state == "resumed:league-coliseum"'
  'live_runner.service.unit == "trillionnium-bevy-playtest.service"'
  'live_runner.runtime.cmdline == [.live_runner.runtime.expected_binary, "run"]'
  'gates.player_launch_ready_gate == true'
  'trillionnium-bevy-playtest.service'
  'release_binary_gate == true'
  'classic_env_gate == true'
  'manifest_gate == true'
  'override_dir_gate == true'
  'workdir_gate == true'
  'cex_path_gate == true'
  'TRNM_WORLD_BEVY_CLASSIC_RENDERER'
  'TRNM_WORLD_BEVY_CLASSIC_ASSET_MANIFEST'
  'campaign_ui_continuity_semantics'
  'native_bevy_classic_rts_campaign_ui_continuity'
  'trillionnium_world_bevy_classic_rts_campaign_ui_continuity_v1'
  'campaign_handoff_contract == "trillionnium_world_bevy_classic_rts_campaign_handoff_v1"'
  'runtime_screen_mode == "player_runtime_campaign_ui_continuity_screen"'
  'evidence_board_only == false'
  'player_first_campaign_continuity_screen_gate == true'
  'campaign_continuity_pixel_counts.player_first_campaign_view_non_background > 600000'
  'capture_frame_count == 16'
  'final_open_world_handoff_state == "resumed:league-coliseum"'
  'restored_open_world_handoff_state == "resumed:league-coliseum"'
  'milestones | to_entries | all(.value == true)'
  'native_client_boundary_gate == true'
  'campaign_ui_continuity_ppm_semantics'
  'native_bevy_classic_rts_campaign_ui_continuity_ppm'
  '1920 1080'
  'classic_playtest_readiness_semantics'
  'classic_playtest_readiness_full_game_visual_ui_replication_semantics'
  'openra_engine_port_asset_parity_semantics'
  'native_bevy_classic_rts_openra_engine_port_asset_parity'
  'trillionnium_world_bevy_classic_rts_openra_engine_port_asset_parity_v1'
  'rust_reimplementation_of_openra_engine_foundation_owned_assets'
  'openra_engine_port_scope == "moddata_ruleset_actor_world_order_chrome_widget_sprite_palette_asset_loader_replay_foundation"'
  'ported_engine_module_count >= 10'
  'pixel_parity.coverage == "full_classic_asset_manifest_frame_set"'
  'pixel_parity.sample_count == .asset_manifest.frame_count'
  'pixel_parity.manifest_frame_match_count == .asset_manifest.frame_count'
  'pixel_parity.sample_pixel_mismatch_count == 0'
  'pixel_parity.reference_render_pixel_mismatch_count == 0'
  'openra_style_engine_foundation_claimed == true'
  'openra_engine_port_foundation_claimed == false'
  'openra_engine_port_claimed == false'
  'openra_full_engine_port_claimed == false'
  'trillionnium_owned_asset_pack_pixel_parity_claimed == true'
  'openra_pixel_perfect_asset_parity_claimed == false'
  'openra_westwood_pixel_perfect_asset_parity_claimed == false'
  'openra_csharp_engine_code_copied == false'
  'openra_engine_port_asset_parity_ppm_semantics'
  'native_bevy_classic_rts_openra_engine_port_asset_parity_ppm'
  'classic_playtest_handoff_readiness_semantics'
  'classic_playtest_handoff_packet_semantics'
  'classic_playtest_handoff_packet_markdown_semantics'
  'require_artifact_text_contains'
  'native_bevy_classic_playtest_handoff_readiness'
  'native_bevy_classic_playtest_handoff_packet'
  'native_bevy_classic_playtest_handoff_packet_markdown'
  'public_launch_operator_handoff_semantics'
  'public_launch_operator_handoff_markdown_semantics'
  'public_launch_operator_handoff'
  'public_launch_operator_handoff_markdown'
  'trillionnium_world_public_launch_operator_handoff_v1'
  'public_launch_operator_handoff_ready_with_external_blockers'
  'S5 Android real-device matrix'
  'TRILLIONNIUM_PUBLIC_LAUNCH_EVIDENCE_BUNDLE_PATH=<real-bundle.json>'
  'trillionnium_world_bevy_classic_playtest_handoff_readiness_v1'
  'trillionnium_world_bevy_classic_playtest_handoff_packet_v1'
  'classic_playtest_handoff_readiness_green'
  'classic_playtest_handoff_packet_green'
  'Bevy Classic Playtest Handoff Packet'
  'OpenRA natural replay/headless parity: `false`'
  'local human-playtest handoff layer'
  'artifact_manifest | length) == 5'
  'playtest_observability_readiness'
  'refresh_handoff'
  'refresh_packet'
  'native_bevy_classic_playtest_readiness'
  'trillionnium_world_bevy_classic_playtest_readiness_v1'
  'classic_playtest_readiness_green'
  'classic_rts_full_screen_ui_replication_green == true'
  'classic_rts_full_game_visual_ui_replication_green == true'
  'rts_full_screen_ui_replication_player_first_screen_gate == true'
  'rts_full_screen_ui_replication_player_first_tactical_view_non_background > 80000'
  'rts_full_screen_ui_replication_player_first_tactical_view_frame_pixel_count > 8000'
  'rts_full_screen_ui_replication_player_first_status_strip_pixel_count > 6000'
  'rts_continuous_player_flow_player_first_continuous_flow_screen_gate == true'
  'rts_continuous_player_flow_player_first_flow_view_non_background > 300000'
  'rts_continuous_player_flow_player_first_flow_view_frame_pixel_count > 8000'
  'rts_continuous_player_flow_player_first_flow_status_strip_pixel_count > 10000'
  'rts_continuous_player_flow_player_first_flow_stage_rail_pixel_count > 50000'
  'rts_full_game_visual_ui_replication_surface_count == 18'
  'rts_full_game_visual_ui_replication_runtime_screen_mode == "player_runtime_full_game_visual_ui_screen"'
  'rts_full_game_visual_ui_replication_runtime_screen_gate == true'
  'rts_full_game_visual_ui_replication_evidence_board_only == false'
  'rts_full_game_visual_ui_replication_player_first_tactical_composition_gate == true'
  'rts_full_game_visual_ui_replication_player_first_screen_gate == true'
  'rts_full_game_visual_ui_replication_player_first_tactical_preview_non_background > 350000'
  'rts_full_game_visual_ui_replication_player_first_tactical_viewport_frame_pixel_count > 8000'
  'rts_full_game_visual_ui_replication_player_first_tactical_status_strip_pixel_count > 10000'
  'rts_live_session_playthrough_player_first_live_session_screen_gate == true'
  'rts_live_session_playthrough_player_first_live_view_non_background > 250000'
  'rts_live_session_playthrough_player_first_live_view_frame_pixel_count > 8000'
  'rts_live_session_playthrough_player_first_live_status_strip_pixel_count > 10000'
  'rts_live_session_playthrough_player_first_live_stage_rail_pixel_count > 25000'
  'rts_full_game_visual_ui_replication_gate == true'
  'classic_rts_full_game_visual_ui_replication'
  'classic_rts_combat_readability_pressure_readiness_green == true'
  'rts_session_state_continuity_player_first_session_resume_screen_gate == true'
  'rts_session_state_continuity_player_first_resume_view_non_background > 250000'
  'rts_session_state_continuity_slot_a_bytes > 10000'
  'internal_classic_playtest_readiness_claimed == true'
  'external_evidence_ignored_for_current_playtest_pass == true'
  'shell_meta_ui_replication_semantics'
  'native_bevy_classic_rts_shell_meta_ui_replication'
  'trillionnium_world_bevy_classic_rts_shell_meta_ui_replication_v1'
  'classic_rts_shell_meta_ui_replication_green'
  'shell_meta_surface_count == 12'
  'TITLE / ACCOUNT'
  'SESSION SLOT MENU'
  'PAUSE / RESUME'
  'runtime_screen_mode == "player_runtime_shell_meta_screen"'
  'runtime_screen_gate == true'
  'evidence_board_only == false'
  'top account/login/continue CTA strip'
  'visible save slots with selected slot A'
  'pause, settings, input HUD, and hit-test cards'
  'bottom create-to-continue gameplay route'
  'shell_meta_pixel_counts.board > 80000'
  'shell_meta_ui_replication_gate == true'
  'internal_shell_meta_ui_replication_claimed == true'
  'match_setup_ui_replication_semantics'
  'native_bevy_classic_rts_match_setup_ui_replication'
  'trillionnium_world_bevy_classic_rts_match_setup_ui_replication_v1'
  'classic_rts_match_setup_ui_replication_green'
  'setup_surface_count == 10'
  'CAMPAIGN ACTIONS'
  'MAP SELECT'
  'FACTION SELECT'
  'START READY'
  'runtime_screen_mode == "player_runtime_match_setup_screen"'
  'large First Contact Basin tactical setup viewport'
  'in-map camera fog and spawn-lane preview'
  'faction, resources, bot, victory, and boundary confirmation rail'
  'bottom player launch strip with local Rust/Bevy ready state'
  'match_setup_player_first_pixel_counts.player_first_match_setup_map_non_background > 80000'
  'player_first_match_setup_screen_gate == true'
  'match_setup_ui_replication_gate == true'
  'internal_match_setup_ui_replication_claimed == true'
  'campaign_outcome_ui_readiness_semantics'
  'native_bevy_classic_rts_campaign_outcome_ui_readiness'
  'trillionnium_world_bevy_classic_rts_campaign_outcome_ui_readiness_v1'
  'classic_rts_campaign_outcome_ui_readiness_green'
  'preview_count == 5'
  'runtime_screen_mode == "player_runtime_campaign_outcome_screen"'
  'title to victory to aftermath to open-world resume'
  'league-coliseum arena_outdoor resume state'
  'campaign_outcome_ui_readiness_gate == true'
  'first_minute_gate == true'
  'objective_victory_gate == true'
  'base_assault_gate == true'
  'battle_aftermath_gate == true'
  'open_world_return_gate == true'
  'open_world_summary.runtime_screen_mode == "player_runtime_open_world_after_action_screen"'
  'open_world_summary.player_first_open_world_after_action_screen_gate == true'
  'internal_campaign_outcome_ui_readiness_claimed == true'
  'external_evidence_ignored_for_current_outcome_pass == true'
  'in_match_hud_state_replication_semantics'
  'native_bevy_classic_rts_in_match_hud_state_replication'
  'trillionnium_world_bevy_classic_rts_in_match_hud_state_replication_v1'
  'classic_rts_in_match_hud_state_replication_green'
  'hud_surface_count == 8'
  'COMMAND GRID'
  'COMBAT ALERTS'
  'runtime_screen_mode == "player_runtime_in_match_hud_screen"'
  'single in-match First Contact Basin tactical viewport'
  'move/train/build/attack command grid and queue'
  'player_first_in_match_hud_screen_gate == true'
  'in_match_hud_player_first_pixel_counts.player_first_in_match_hud_view_non_background > 350000'
  'rts_in_match_hud_state_replication_player_first_screen_gate == true'
  'in_match_hud_state_replication_gate == true'
  'internal_in_match_hud_state_replication_claimed == true'
  'session_state_continuity_semantics'
  'native_bevy_classic_rts_session_state_continuity'
  'trillionnium_world_bevy_classic_rts_session_state_continuity_v1'
  'classic_rts_session_state_continuity_green'
  'state_continuity_surface_count == 8'
  'SESSION SLOT WRITE'
  'LOAD RESUME LOCK'
  'OPEN-WORLD RESUME'
  'runtime_screen_mode == "player_runtime_session_resume_screen"'
  'single visible save/load/continue chain from match setup into restored play'
  'large restored tactical state with save-resume rail'
  'player_first_resume_view_non_background > 250000'
  'player_first_session_resume_screen_gate == true'
  'player_runtime_in_match_hud_screen'
  'session_state_continuity_gate == true'
  'internal_session_state_continuity_claimed == true'
  'combat_readability_pressure_readiness_semantics'
  'native_bevy_classic_rts_combat_readability_pressure_readiness'
  'trillionnium_world_bevy_classic_rts_combat_readability_pressure_readiness_v1'
  'classic_rts_combat_readability_pressure_readiness_green'
  'preview_count == 6'
  'source_preview_count == 5'
  'player_screen_format == "ppm_p3_rgb"'
  'player_screen_width == 1280'
  'player_screen_height == 768'
  'runtime_screen_mode == "player_runtime_combat_pressure_screen"'
  'selected unit portrait, bars, role, and queue badges'
  'central keep shield, guard, siege line, and defeat-risk feedback'
  'large central-keep combat pressure tactical viewport'
  'unit, command, ability, depth, and pressure feedback rail'
  'player combat commands with attack, ability, hold, break, and retreat states'
  'unit_status_gate == true'
  'command_feedback_gate == true'
  'ability_telegraph_gate == true'
  'pressure_feedback_gate == true'
  'player_first_combat_pressure_screen_gate == true'
  'combat_pressure_pixel_counts.player_first_combat_pressure_view_non_background > 120000'
  'rts_combat_readability_pressure_player_first_screen_gate == true'
  'combat_readability_pressure_readiness_gate == true'
  'internal_combat_readability_pressure_readiness_claimed == true'
  'external_evidence_ignored_for_current_combat_readability_pass == true'
  'classic_rts_camera_minimap_sync_semantics'
  'classic_rts_camera_minimap_sync_ppm_semantics'
  'native_bevy_classic_rts_camera_minimap_sync'
  'native_bevy_classic_rts_camera_minimap_sync_ppm'
  'trillionnium_world_bevy_classic_rts_camera_minimap_sync_v1'
  'classic_draw_scene+classic_draw_rts_camera_minimap_sync_overlay'
  'apply_rts_scrollable_map_camera_input(classic_rts_camera_minimap_sync_input)'
  'rts_camera_minimap_selection_follow_step'
  'update_native_rts_scrollable_map_camera+apply_native_rts_scrollable_map_view+rts_camera_minimap_viewport_rect'
  'large_map.map_width_tiles == 34'
  'large_map_minimap_gate == true'
  'viewport_sync_gate == true'
  'fog_reveal_gate == true'
  'selection_follow_gate == true'
  'control_group_sync_gate == true'
  'route_projection_gate == true'
  'zoom_rect_sync_gate == true'
  'minimap_runtime_gate == true'
  'minimap_route_target'
  '1920 720'
  'full_screen_ui_replication_semantics'
  'native_bevy_classic_rts_full_screen_ui_replication'
  'trillionnium_world_bevy_classic_rts_full_screen_ui_replication_v1'
  'classic_rts_full_screen_ui_replication_green'
  'replication_surface_count == 10'
  'runtime_screen_mode == "player_runtime_screen"'
  'production_ui_runtime_screen_mode == "player_runtime_production_hud_skin_screen"'
  'interaction_runtime_screen_mode == "player_runtime_command_interaction_screen"'
  'single large scrollable map viewport'
  'full_screen_ui_pixel_counts.player_first_full_screen_tactical_view_non_background > 80000'
  'player_first_full_screen_ui_surface_gate == true'
  'player command buttons, queue, and interaction feedback'
  'external_evidence_ignored_for_current_replication_pass == true'
  'production_desktop_review_packet_semantics'
  'native_bevy_classic_rts_production_desktop_review_packet'
  'trillionnium_world_bevy_classic_rts_production_desktop_review_packet_v1'
  'classic_rts_production_desktop_review_packet_green'
  'production_interaction_polish_gate == true'
  'production_review_summary.runtime_screen_mode == "player_runtime_command_interaction_screen"'
  'production_review_summary.ui_skin_runtime_screen_mode == "player_runtime_production_hud_skin_screen"'
  'production_review_summary.evidence_board_only == false'
  'desktop_playtest_review_packet_gate == true'
  'desktop_review_scope == "local_linux_desktop_x11_window_keyboard_mouse_with_production_interaction_polish"'
  'require_artifact_json_expr'
  'require_artifact_ppm_header'
  'packet_integrity_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_semantic_fixture_v1'
  'fake_packet_artifact_count == 121'
  'expected_semantic_failure_count == 17'
  'release_review_convergence_semantics'
  'release_review_status_semantics'
  'release_review_status_markdown_semantics'
  'release_review_quickcheck_semantics'
  'cex_adapter_readiness_semantics'
  'checksum_mismatch_failure_count == 0'
  'packet_integrity_bot_executor_semantic_fixture'
  'release_review_packet_integrity_bot_executor_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_bot_executor_semantic_fixture_v1'
  'expected_semantic_failure_count == 9'
  'packet_integrity_bot_executor_matrix_semantic_fixture'
  'release_review_packet_integrity_bot_executor_matrix_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_bot_executor_matrix_semantic_fixture_v1'
  'expected_semantic_failure_count == 3'
  'packet_integrity_bot_gap_semantic_fixture'
  'release_review_packet_integrity_bot_gap_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_bot_gap_semantic_fixture_v1'
  'expected_semantic_failure_count == 8'
  'packet_integrity_control_loop_semantic_fixture'
  'release_review_packet_integrity_control_loop_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_control_loop_semantic_fixture_v1'
  'expected_semantic_failure_count == 2'
  'packet_integrity_selection_minimap_semantic_fixture'
  'release_review_packet_integrity_selection_minimap_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_selection_minimap_semantic_fixture_v1'
  'packet_integrity_build_lifecycle_semantic_fixture'
  'release_review_packet_integrity_build_lifecycle_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_build_lifecycle_semantic_fixture_v1'
	  'packet_integrity_tech_tree_semantic_fixture'
	  'release_review_packet_integrity_tech_tree_semantic_fixture'
	  'trillionnium_world_release_review_packet_integrity_tech_tree_semantic_fixture_v1'
	  'packet_integrity_projectile_ability_semantic_fixture'
	  'release_review_packet_integrity_projectile_ability_semantic_fixture'
	  'trillionnium_world_release_review_packet_integrity_projectile_ability_semantic_fixture_v1'
	  'classic_rts_control_loop_semantics'
  'native_bevy_classic_rts_control_loop'
  'move_selected_unit_count >= 4'
  'attack_target_id == "arena_creep_attack"'
  'classic_rts_control_loop_ppm_semantics'
  'native_bevy_classic_rts_control_loop_ppm'
  'classic_rts_selection_minimap_semantics'
  'native_bevy_classic_rts_selection_minimap'
  'accepted_input_count == 4'
  '(.stage_summaries | any(.stage == "minimap_rally"'
  'final_minimap_command_tile_id == "6,5"'
  'classic_rts_selection_minimap_ppm_semantics'
  'native_bevy_classic_rts_selection_minimap_ppm'
  'classic_rts_build_lifecycle_semantics'
  'native_bevy_classic_rts_build_lifecycle'
  'accepted_input_count == 6'
  'final_structure_state == "cancelled:scout_tower@8,4"'
  'final_repair_target_id == "watch_tower"'
  'classic_rts_build_lifecycle_ppm_semantics'
  'native_bevy_classic_rts_build_lifecycle_ppm'
  'classic_rts_tech_tree_semantics'
  'native_bevy_classic_rts_tech_tree'
  'final_faction_id == "mirror_guard"'
  'final_tech_state == "unlocked:relay_guard"'
  'faction_base_gate == true'
  'dependency_gate == true'
	  'classic_rts_tech_tree_ppm_semantics'
	  'native_bevy_classic_rts_tech_tree_ppm'
	  'classic_rts_projectile_ability_semantics'
	  'native_bevy_classic_rts_projectile_ability'
	  'final_active_projectile_id == "guard_break_bolt"'
	  'final_ability_resolution_state == "resolved:guard_break:arena_creep_attack"'
	  'projectile_trail_gate == true'
	  'armor_shield_gate == true'
	  'classic_rts_projectile_ability_ppm_semantics'
	  'native_bevy_classic_rts_projectile_ability_ppm'
	  'packet integrity projectile/ability semantic fixture proves bad projectile/ability summary and PPM semantics fail even when checksums, bytes, contracts, and statuses match'
	  'first_minute_command_feedback_replay_semantics'
  'command_input_action_count == 7'
  'accepted_command_input_count == 7'
  'retained_history_group_ids == ["26", "27", "28"]'
  'pruned_history_group_ids == ["25", "24"]'
  'cleared_active_stale_pixel_count == 0'
  'first_minute_command_feedback_source_recording_semantics'
  'source_timeline_green == true'
  'first_minute_command_feedback_recording_semantics'
  'RTS:MOVE:18,31:line'
  'first_minute_command_feedback_replay_ppm_semantics'
  'first_minute_command_feedback_rejection_replay_semantics'
  'accepted_command_input_count == 1'
  'blocked_command_input_count == 7'
  'command_queue_rejection_pollution_count == 0'
  'rts_invalid_tile:bad-tile'
  'first_minute_command_feedback_rejection_source_recording_semantics'
  'first_minute_command_feedback_rejection_recording_semantics'
  'RTS:ABILITY:guard_break'
  'first_minute_command_feedback_rejection_replay_ppm_semantics'
  'bot_planner_action_executor_semantics'
  'native_bevy_bot_planner_action_executor'
  'bot_planner_action_executor_gate == true'
  'bot_planner_action_executor_log_semantics'
  'native_bevy_bot_planner_action_executor_log'
  'bot_planner_action_executor_ppm_semantics'
  'bot_planner_executor_replay_determinism_semantics'
  'native_bevy_bot_planner_executor_replay_determinism'
  'bot_planner_executor_replay_determinism_gate == true'
  'source_final_runtime_sha256 == .replay_final_runtime_sha256'
  'bot_planner_executor_replay_determinism_log_semantics'
  'native_bevy_bot_planner_executor_replay_determinism_log'
  'bot_planner_executor_replay_determinism_ppm_semantics'
  'multi_match_bot_executor_evaluation_semantics'
  'native_bevy_multi_match_bot_executor_evaluation'
  'multi_match_bot_executor_evaluation_gate == true'
  'variant_count == 4'
  'total_accepted_action_count == 24'
  'multi_match_bot_executor_evaluation_log_semantics'
  'native_bevy_multi_match_bot_executor_evaluation_log'
  'multi_match_bot_executor_evaluation_ppm_semantics'
  'packet integrity bot executor semantic fixture proves bad bot executor source-chain semantics fail even when checksums, bytes, contracts, and statuses match'
  'packet integrity bot executor failure/recovery matrix semantic fixture proves bad matrix semantics fail even when checksums, bytes, contracts, and statuses match'
  'bot_executor_failure_recovery_matrix_semantics'
  'bot_executor_failure_recovery_matrix_state == "bevy_executor_rejects_blocked_actions_and_recovers_without_command_queue_pollution_not_openra_runtime_bot"'
  'blocked_injection_count == 6'
  'blocked_rejection_count == 6'
  'blocked_command_queue_unchanged_count == 6'
  'recovery_accepted_action_count == 6'
  'recovery_command_delta_match_count == 6'
  'recovery_safe_runtime_sha_match == true'
  'source_multi_match_summary.variant_count == 4'
  'bot_executor_failure_recovery_matrix_log_semantics'
  'native_bevy_bot_executor_failure_recovery_matrix_log'
  'bot_executor_failure_recovery_matrix_ppm_semantics'
  'native_bevy_bot_executor_failure_recovery_matrix_ppm'
  'bot_decision_state_gap_semantics'
  'native_bevy_bot_decision_state_gap'
  'bevy_bot_decision_gap_state == "bevy_bot_decision_vocabulary_not_openra_native_bot_ai"'
  'bot_decision_state_gap_ppm_semantics'
  'native_bevy_bot_decision_state_gap_ppm'
  'bot_adaptive_build_order_gap_semantics'
  'native_bevy_bot_adaptive_build_order_gap'
  'bevy_bot_adaptive_build_gap_state == "bevy_adaptive_build_order_vocabulary_not_openra_native_ai_planner"'
  'bot_adaptive_build_order_gap_ppm_semantics'
  'native_bevy_bot_adaptive_build_order_gap_ppm'
  'bot_tactical_micro_gap_semantics'
  'native_bevy_bot_tactical_micro_gap'
  'bevy_bot_tactical_micro_gap_state == "bevy_tactical_micro_vocabulary_not_openra_native_combat_ai"'
  'bot_tactical_micro_gap_ppm_semantics'
  'native_bevy_bot_tactical_micro_gap_ppm'
  'bot_map_intel_gap_semantics'
  'native_bevy_bot_map_intel_gap'
  'bevy_bot_map_intel_gap_state == "bevy_map_intel_vocabulary_not_openra_native_shroud_memory_ai"'
  'bot_map_intel_gap_ppm_semantics'
  'native_bevy_bot_map_intel_gap_ppm'
  'packet integrity bot gap semantic fixture proves bad bot gap foundation/micro/intel semantics fail even when checksums, bytes, contracts, and statuses match'
  '1280 1080'
  'ppm_header_and_size_match'
  'release_review_packet_integrity_green_with_public_launch_blockers'
  'android_s5_real_device_claimed: false'
  'host_side_bevy_runtime_replay_not_android_real_device'
	  'packet_artifact_paths_must_exist_and_recorded_sha256_bytes_contract_status_must_match_current_files_including_checkpoint_manifest_packet_semantic_negative_fixture_classic_rts_control_loop_semantic_negative_fixture_classic_rts_selection_minimap_semantic_negative_fixture_classic_rts_build_lifecycle_semantic_negative_fixture_classic_rts_tech_tree_semantic_negative_fixture_classic_rts_projectile_ability_semantic_negative_fixture_bot_executor_source_chain_semantic_negative_fixture_bot_executor_failure_recovery_matrix_semantic_negative_fixture_bot_gap_foundation_micro_intel_semantic_negative_fixture_cex_adapter_local_bevy_playability_evidence_cex_adapter_readiness_semantics_s5_real_device_evidence_semantics_keyboard_replay_semantics_classic_animation_preview_semantics_classic_animation_preview_ppm_semantics_classic_animation_selector_semantics_classic_player_motion_probe_semantics_classic_player_motion_probe_ppm_semantics_action_coach_semantics_player_hud_debug_layer_semantics_player_ui_rescue_semantics_live_window_screenshot_sequence_semantics_visible_button_hit_test_map_semantics_live_window_mouse_hit_test_sequence_semantics_sprite_texture_sampling_semantics_live_window_sampled_texture_correlation_semantics_render_asset_eligibility_semantics_public_launch_readiness_semantics_public_launch_blocker_consistency_semantics_public_launch_evidence_intake_semantics_public_launch_evidence_intake_markdown_semantics_production_map_pack_public_evidence_collection_semantics_cohort_commercial_evidence_collection_semantics_external_ops_evidence_collection_semantics_production_map_pack_public_evidence_semantics_cohort_commercial_evidence_semantics_external_ops_evidence_semantics_public_launch_evidence_kit_semantics_public_launch_evidence_kit_markdown_semantics_public_launch_template_negative_fixtures_semantics_public_launch_evidence_bundle_semantics_public_launch_evidence_bundle_markdown_semantics_public_launch_bundle_negative_fixtures_semantics_public_launch_status_only_fixture_guard_semantics_public_launch_operator_handoff_semantics_public_launch_operator_handoff_markdown_semantics_release_signoff_summary_semantics_release_review_quickcheck_semantics_release_review_status_semantics_release_review_status_markdown_semantics_release_review_convergence_semantics_release_review_packet_convergence_log_semantics_map_modeling_gate_semantics_classic_asset_pack_semantics_classic_manifest_lint_semantics_classic_input_frame_budget_semantics_classic_render_budget_semantics_classic_isometric_modeling_semantics_classic_isometric_modeling_ppm_semantics_classic_scene_preview_semantics_classic_scene_preview_ppm_semantics_classic_model_catalog_semantics_classic_model_catalog_ppm_semantics_classic_renderer_probe_semantics_classic_renderer_probe_ppm_semantics_classic_playtest_runner_status_semantics_classic_playtest_launcher_semantics_classic_playtest_handoff_readiness_semantics_classic_playtest_handoff_packet_semantics_classic_playtest_handoff_packet_markdown_semantics_classic_playtest_readiness_semantics_classic_playtest_readiness_full_game_visual_ui_replication_semantics_full_screen_ui_replication_semantics_shell_meta_ui_replication_semantics_match_setup_ui_replication_semantics_campaign_outcome_ui_readiness_semantics_campaign_ui_continuity_semantics_campaign_ui_continuity_ppm_semantics_in_match_hud_state_replication_semantics_session_state_continuity_semantics_combat_readability_pressure_readiness_semantics_classic_rts_camera_minimap_sync_semantics_classic_rts_camera_minimap_sync_ppm_semantics_openra_engine_port_asset_parity_semantics_openra_engine_port_asset_parity_ppm_semantics_classic_rts_control_loop_semantics_classic_rts_selection_minimap_semantics_classic_rts_build_lifecycle_semantics_classic_rts_tech_tree_semantics_classic_rts_projectile_ability_semantics_first_minute_command_feedback_replay_semantics_first_minute_command_feedback_rejection_replay_semantics_bot_executor_source_chain_semantics_bot_executor_failure_recovery_matrix_semantics_and_bot_gap_foundation_micro_intel_semantics'
)

for line in "${required_lines[@]}"; do
  if ! grep -Fq -- "$line" "$SCRIPT"; then
    echo "[FAIL] release review packet integrity script missing contract line: $line" >&2
    exit 1
  fi
done

echo "[PASS] release review packet integrity script keeps packet refresh, checksum/byte/contract/status verification, convergence/status/quickcheck/signoff summary semantics, first-minute command feedback replay/rejection semantic checks, no-refresh mode, and Android S5 boundary"
