#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_release_review_packet.sh"

required_lines=(
  'trillionnium_world_release_review_packet_v1'
  'check_trillionnium_world_release_review_convergence.sh'
  'release-review-packet.json'
  'release-review-packet.md'
  'release-review-packet-convergence.log'
  'release-review-packet-evidence-intake.log'
  'release-review-packet-blocker-consistency.log'
  'release-review-packet-evidence-kit.log'
  'release-review-packet-operator-handoff.log'
  'release-review-packet-template-negative-fixtures.log'
  'release-review-packet-evidence-bundle.log'
  'release-review-packet-bundle-negative-fixtures.log'
  'release-review-packet-map-modeling-gate.log'
  'release-review-packet-cex-adapter-readiness.log'
  'release-review-packet-checkpoint-manifest.log'
  'sha256sum'
  'native_bevy_keyboard_replay'
  'native_bevy_action_coach'
  'bevy-action-coach.json'
  'native_bevy_player_hud_debug_layer'
  'bevy-player-hud-debug-layer.json'
  'native_bevy_player_ui_rescue'
  'bevy-player-ui-rescue.json'
  'native_bevy_live_window_screenshot_sequence'
  'bevy-live-window-screenshot-sequence.json'
  'native_bevy_sprite_texture_sampling'
  'bevy-sprite-texture-sampling.json'
  'native_bevy_live_window_sampled_texture_correlation'
  'bevy-live-window-sampled-texture-correlation.json'
  'native_bevy_render_asset_eligibility'
  'bevy-render-asset-eligibility.json'
  'native_bevy_classic_asset_pack'
  'bevy-classic-asset-pack.json'
  'native_bevy_classic_manifest_lint'
  'bevy-classic-manifest-lint.json'
  'native_bevy_classic_animation_preview'
  'bevy-classic-animation-preview.json'
  'native_bevy_classic_animation_preview_ppm'
  'bevy-classic-animation-preview.ppm'
  'native_bevy_classic_animation_selector'
  'bevy-classic-animation-selector.json'
  'native_bevy_classic_player_motion_probe'
  'bevy-classic-player-motion-probe.json'
  'native_bevy_classic_player_motion_probe_ppm'
  'bevy-classic-player-motion-probe.ppm'
  'native_bevy_classic_input_frame_budget'
  'bevy-classic-input-frame-budget.json'
  'native_bevy_classic_render_budget'
  'bevy-classic-render-budget.json'
  'native_bevy_classic_scene_preview'
  'bevy-classic-scene-preview.json'
  'native_bevy_classic_scene_preview_ppm'
  'bevy-classic-scene-preview.ppm'
  'native_bevy_classic_model_catalog'
  'bevy-classic-model-catalog.json'
  'native_bevy_classic_model_catalog_ppm'
  'bevy-classic-model-catalog.ppm'
  'native_bevy_classic_renderer_probe'
  'bevy-classic-renderer-probe.json'
  'native_bevy_classic_renderer_probe_ppm'
  'bevy-classic-renderer-probe.ppm'
  'native_bevy_classic_isometric_modeling'
  'bevy-classic-isometric-modeling.json'
  'native_bevy_classic_isometric_modeling_ppm'
  'bevy-classic-isometric-modeling.ppm'
  'native_bevy_classic_playtest_readiness'
  'bevy-classic-playtest-readiness.json'
  'native_bevy_classic_playtest_runner_status'
  'bevy-classic-playtest-runner-status.json'
  'cex_adapter_readiness'
  'CEX production world adapter readiness'
  'cex-production-adapter-readiness.json'
  'check_trillionnium_world_cex_adapter_readiness.sh'
  'release_review_checkpoint_manifest'
  'Release review checkpoint manifest'
  'release-review-checkpoint-manifest.json'
  'check_trillionnium_world_release_review_checkpoint_manifest.sh'
  's5_real_device_evidence'
  's5-real-device-evidence-validation.json'
  'public_launch_readiness'
  'public_launch_evidence_intake'
  'public-launch-evidence-intake.json'
  'production_map_pack_public_evidence_collection'
  'production-map-pack-public-evidence-collection.json'
  'map_modeling_gate'
  'map-modeling-gate.json'
  'check_trillionnium_world_map_modeling_gate.sh'
  'cohort_commercial_evidence_collection'
  'cohort-commercial-evidence-collection.json'
  'external_ops_evidence_collection'
  'external-ops-evidence-collection.json'
  'public_launch_blocker_consistency'
  'public-launch-blocker-consistency.json'
  'check_trillionnium_world_public_launch_blocker_consistency.sh'
  'public_launch_evidence_kit'
  'public-launch-evidence-kit.json'
  'check_trillionnium_world_public_launch_evidence_kit.sh'
  'public_launch_operator_handoff'
  'public-launch-operator-handoff.json'
  'check_trillionnium_world_public_launch_operator_handoff.sh'
  'public_launch_template_negative_fixtures'
  'public-launch-template-negative-fixtures.json'
  'check_trillionnium_world_public_launch_template_negative_fixtures.sh'
  'public_launch_evidence_bundle'
  'public-launch-evidence-bundle.json'
  'check_trillionnium_world_public_launch_evidence_bundle.sh'
  'public_launch_bundle_negative_fixtures'
  'public-launch-bundle-negative-fixtures.json'
  'check_trillionnium_world_public_launch_bundle_negative_fixtures.sh'
  'public_launch_status_only_fixture_guard'
  'public-launch-status-only-fixtures.json'
  'production_map_pack_public_evidence'
  'production-map-pack-public-evidence.json'
  'cohort_commercial_evidence'
  'cohort-commercial-evidence.json'
  'external_ops_evidence'
  'external-ops-evidence.json'
  'release_signoff_summary'
  'release_review_quickcheck'
  'release_review_status_json'
  'release_review_status_markdown'
  'release_review_convergence'
  'android_s5_real_device_claimed: false'
  'host_side_bevy_runtime_replay_not_android_real_device'
  'sprite texture sampling'
  'sampled texture live-window correlation'
  'render asset eligibility'
  'classic scene preview'
  'classic manifest lint'
  'classic animation preview'
  'classic animation selector'
  'classic player motion probe'
  'classic input-frame budget'
  'classic render budget'
  'classic playtest readiness'
  'classic playtest runner status'
  'classic model catalog'
  'classic renderer probe'
  'classic isometric modeling'
  'CEX adapter readiness proves the current CEX incubator exports the Trillionnium world runtime adapter contract'
  'Public launch operator handoff is a checksum-bound collection checklist'
  'The checkpoint manifest groups the current dirty working tree for review; it does not stage, commit, or publish anything.'
  'Still Requires Real External Evidence'
)

for line in "${required_lines[@]}"; do
  if ! grep -Fq -- "$line" "$SCRIPT"; then
    echo "[FAIL] release review packet script missing contract line: $line" >&2
    exit 1
  fi
done

echo "[PASS] release review packet script keeps convergence refresh, checksummed artifacts, packet outputs, and Android S5 boundary"
