#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_release_review_packet_integrity.sh"

required_lines=(
  'trillionnium_world_release_review_packet_integrity_v1'
  'check_trillionnium_world_release_review_packet.sh'
  'release-review-packet-integrity.json'
  'release-review-packet-integrity-packet.log'
  'TRILLIONNIUM_WORLD_RELEASE_REVIEW_PACKET_JSON'
  'TRILLIONNIUM_WORLD_RELEASE_REVIEW_PACKET_MD'
  'TRILLIONNIUM_WORLD_RELEASE_REVIEW_PACKET_LOG'
  '--no-refresh'
  'sha256sum'
  'bytes_match'
  'contract_match'
  'status_match'
  'length == 107'
  'expected one hundred seven artifacts including full screen/UI replication, shell/meta UI replication, match setup UI replication, campaign outcome UI readiness, in-match HUD/state replication, session state continuity, combat readability/pressure readiness'
  'action_coach_semantics'
  'native_bevy_action_coach'
  'trillionnium_world_bevy_action_coach_v1'
  'action_coach_green'
  'coach_stage_gate == true'
  'enter_execution_gate == true'
  'final_next_gate == true'
  'input_hint_contract_gate == true'
  'external_evidence_ignored_for_current_action_coach_pass == true'
  'player_hud_debug_layer_semantics'
  'native_bevy_player_hud_debug_layer'
  'trillionnium_world_bevy_player_hud_debug_layer_v1'
  'player_hud_debug_layer_green'
  'player_hud_gate == true'
  'quest_layer_gate == true'
  'debug_layer_gate == true'
  'scene_debug_gate == true'
  'input_hint_gate == true'
  'panel_layer_gate == true'
  'runtime_gate == true'
  'external_evidence_ignored_for_current_player_hud_pass == true'
  'player_ui_rescue_semantics'
  'native_bevy_player_ui_rescue'
  'trillionnium_world_bevy_player_ui_rescue_v1'
  'player_ui_rescue_green'
  'player_status_gate == true'
  'route_panel_gate == true'
  'quest_panel_gate == true'
  'action_layer_gate == true'
  'debug_deprioritized_gate == true'
  'event_log_separation_gate == true'
  'button_wall_deprioritized_gate == true'
  'contextual_deck_layout_gate == true'
  'right_rail_summary_gate == true'
  'top_hud_density_gate == true'
  'toast_lane_gate == true'
  'visual_hierarchy_gate == true'
  'art_direction_gate == true'
  'scene_readability_gate == true'
  'sprite_asset_quality_gate == true'
  'map_model_visual_gate == true'
  'map_occlusion_gate == true'
  'ui_polish_gate == true'
  'tileset_polish_gate == true'
  'authored_art_pack_gate == true'
  'external_evidence_ignored_for_current_player_ui_rescue_pass == true'
  'public_launch_ready == false'
  'production_ready_ui_claimed == false'
  'screen_for_screen_openra_ui_claimed == false'
  'openra_engine_port_claimed == false'
  'warcraft_iii_asset_copied == false'
  'openra_asset_copied == false'
  'third_party_asset_copied == false'
  'live_window_screenshot_sequence_semantics'
  'native_bevy_live_window_screenshot_sequence'
  'trillionnium_world_bevy_live_window_screenshot_sequence_v1'
  'live_window_screenshot_sequence_green'
  'host_window_gate == true'
  'frame_sequence_gate == true'
  'runtime_texture_manifest_hash_gate == true'
  'runtime_texture_sprite_asset_binding_gate == true'
  'internal_live_window_screenshot_sequence_claimed == true'
  'external_evidence_ignored_for_current_live_window_pass == true'
  'sprite_texture_sampling_semantics'
  'native_bevy_sprite_texture_sampling'
  'trillionnium_world_bevy_sprite_texture_sampling_v1'
  'sprite_texture_sampling_green'
  'runtime_texture_manifest_probe_contract == "trillionnium_world_bevy_runtime_texture_manifest_probe_v1"'
  'asset_store_registration_contract == "trillionnium_world_bevy_asset_store_registration_v1"'
  'sprite_asset_binding_contract == "trillionnium_world_bevy_sprite_asset_binding_v1"'
  'four_layer_texture_sampling_gate == true'
  'global_unique_texture_color_gate == true'
  'sampled_surface_count >= 24'
  'host_side_cpu_texture_sampling_claimed == true'
  'external_evidence_ignored_for_current_sprite_texture_pass == true'
  'live_window_sampled_texture_correlation_semantics'
  'native_bevy_live_window_sampled_texture_correlation'
  'trillionnium_world_bevy_live_window_sampled_texture_correlation_v1'
  'live_window_sampled_texture_correlation_green'
  'four_layer_sampled_live_correlation_gate == true'
  'same_runtime_manifest_hash_gate == true'
  'internal_live_window_sampled_texture_correlation_claimed == true'
  'external_evidence_ignored_for_current_sampled_texture_pass == true'
  'render_asset_eligibility_semantics'
  'native_bevy_render_asset_eligibility'
  'trillionnium_world_bevy_render_asset_eligibility_v1'
  'render_asset_eligibility_green'
  'runtime_texture_asset_contract == "trillionnium_world_bevy_runtime_texture_asset_v1"'
  'sprite_texture_sampling_contract == "trillionnium_world_bevy_sprite_texture_sampling_v1"'
  'live_window_sampled_texture_correlation_contract == "trillionnium_world_bevy_live_window_sampled_texture_correlation_v1"'
  'render_asset_usage_gate == true'
  'image_descriptor_render_eligibility_gate == true'
  'atlas_layout_render_eligibility_gate == true'
  'sprite_render_reference_gate == true'
  'image_asset_usage_main_world == true'
  'image_asset_usage_render_world == true'
  'host_side_render_asset_eligibility_claimed == true'
  'external_evidence_ignored_for_current_render_asset_pass == true'
  'render_world_extraction_completed_claimed == false'
  'classic_playtest_readiness_semantics'
  'native_bevy_classic_playtest_readiness'
  'trillionnium_world_bevy_classic_playtest_readiness_v1'
  'classic_playtest_readiness_green'
  'classic_rts_full_screen_ui_replication_green == true'
  'classic_rts_combat_readability_pressure_readiness_green == true'
  'rts_session_state_continuity_slot_a_bytes > 10000'
  'internal_classic_playtest_readiness_claimed == true'
  'external_evidence_ignored_for_current_playtest_pass == true'
  'shell_meta_ui_replication_semantics'
  'native_bevy_classic_rts_shell_meta_ui_replication'
  'trillionnium_world_bevy_classic_rts_shell_meta_ui_replication_v1'
  'classic_rts_shell_meta_ui_replication_green'
  'shell_meta_surface_count == 12'
  'TITLE / ACCOUNT'
  'SESSION SLOT MENU'
  'PAUSE / RESUME'
  'shell_meta_pixel_counts.board > 80000'
  'shell_meta_ui_replication_gate == true'
  'internal_shell_meta_ui_replication_claimed == true'
  'match_setup_ui_replication_semantics'
  'native_bevy_classic_rts_match_setup_ui_replication'
  'trillionnium_world_bevy_classic_rts_match_setup_ui_replication_v1'
  'classic_rts_match_setup_ui_replication_green'
  'setup_surface_count == 10'
  'CAMPAIGN ACTIONS'
  'MAP SELECT'
  'FACTION SELECT'
  'START READY'
  'match_setup_ui_replication_gate == true'
  'internal_match_setup_ui_replication_claimed == true'
  'campaign_outcome_ui_readiness_semantics'
  'native_bevy_classic_rts_campaign_outcome_ui_readiness'
  'trillionnium_world_bevy_classic_rts_campaign_outcome_ui_readiness_v1'
  'classic_rts_campaign_outcome_ui_readiness_green'
  'preview_count == 5'
  'first_minute_gate == true'
  'objective_victory_gate == true'
  'base_assault_gate == true'
  'battle_aftermath_gate == true'
  'open_world_return_gate == true'
  'internal_campaign_outcome_ui_readiness_claimed == true'
  'external_evidence_ignored_for_current_outcome_pass == true'
  'in_match_hud_state_replication_semantics'
  'native_bevy_classic_rts_in_match_hud_state_replication'
  'trillionnium_world_bevy_classic_rts_in_match_hud_state_replication_v1'
  'classic_rts_in_match_hud_state_replication_green'
  'hud_surface_count == 8'
  'COMMAND GRID'
  'COMBAT ALERTS'
  'in_match_hud_state_replication_gate == true'
  'internal_in_match_hud_state_replication_claimed == true'
  'session_state_continuity_semantics'
  'native_bevy_classic_rts_session_state_continuity'
  'trillionnium_world_bevy_classic_rts_session_state_continuity_v1'
  'classic_rts_session_state_continuity_green'
  'state_continuity_surface_count == 8'
  'SESSION SLOT WRITE'
  'LOAD RESUME LOCK'
  'OPEN-WORLD RESUME'
  'session_state_continuity_gate == true'
  'internal_session_state_continuity_claimed == true'
  'combat_readability_pressure_readiness_semantics'
  'native_bevy_classic_rts_combat_readability_pressure_readiness'
  'trillionnium_world_bevy_classic_rts_combat_readability_pressure_readiness_v1'
  'classic_rts_combat_readability_pressure_readiness_green'
  'unit_status_gate == true'
  'command_feedback_gate == true'
  'ability_telegraph_gate == true'
  'pressure_feedback_gate == true'
  'internal_combat_readability_pressure_readiness_claimed == true'
  'external_evidence_ignored_for_current_combat_readability_pass == true'
  'full_screen_ui_replication_semantics'
  'native_bevy_classic_rts_full_screen_ui_replication'
  'trillionnium_world_bevy_classic_rts_full_screen_ui_replication_v1'
  'classic_rts_full_screen_ui_replication_green'
  'replication_surface_count == 10'
  'external_evidence_ignored_for_current_replication_pass == true'
  'production_desktop_review_packet_semantics'
  'native_bevy_classic_rts_production_desktop_review_packet'
  'trillionnium_world_bevy_classic_rts_production_desktop_review_packet_v1'
  'classic_rts_production_desktop_review_packet_green'
  'production_interaction_polish_gate == true'
  'desktop_playtest_review_packet_gate == true'
  'desktop_review_scope == "local_linux_desktop_x11_window_keyboard_mouse_with_production_interaction_polish"'
  'require_artifact_json_expr'
  'require_artifact_ppm_header'
  'packet_integrity_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_semantic_fixture_v1'
  'fake_packet_artifact_count == 107'
  'expected_semantic_failure_count == 4'
  'checksum_mismatch_failure_count == 0'
  'packet_integrity_bot_executor_semantic_fixture'
  'release_review_packet_integrity_bot_executor_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_bot_executor_semantic_fixture_v1'
  'expected_semantic_failure_count == 9'
  'packet_integrity_bot_executor_matrix_semantic_fixture'
  'release_review_packet_integrity_bot_executor_matrix_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_bot_executor_matrix_semantic_fixture_v1'
  'expected_semantic_failure_count == 3'
  'packet_integrity_bot_gap_semantic_fixture'
  'release_review_packet_integrity_bot_gap_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_bot_gap_semantic_fixture_v1'
  'expected_semantic_failure_count == 8'
  'packet_integrity_control_loop_semantic_fixture'
  'release_review_packet_integrity_control_loop_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_control_loop_semantic_fixture_v1'
  'expected_semantic_failure_count == 2'
  'packet_integrity_selection_minimap_semantic_fixture'
  'release_review_packet_integrity_selection_minimap_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_selection_minimap_semantic_fixture_v1'
  'packet_integrity_build_lifecycle_semantic_fixture'
  'release_review_packet_integrity_build_lifecycle_semantic_fixture'
  'trillionnium_world_release_review_packet_integrity_build_lifecycle_semantic_fixture_v1'
	  'packet_integrity_tech_tree_semantic_fixture'
	  'release_review_packet_integrity_tech_tree_semantic_fixture'
	  'trillionnium_world_release_review_packet_integrity_tech_tree_semantic_fixture_v1'
	  'packet_integrity_projectile_ability_semantic_fixture'
	  'release_review_packet_integrity_projectile_ability_semantic_fixture'
	  'trillionnium_world_release_review_packet_integrity_projectile_ability_semantic_fixture_v1'
	  'classic_rts_control_loop_semantics'
  'native_bevy_classic_rts_control_loop'
  'move_selected_unit_count >= 4'
  'attack_target_id == "arena_creep_attack"'
  'classic_rts_control_loop_ppm_semantics'
  'native_bevy_classic_rts_control_loop_ppm'
  'classic_rts_selection_minimap_semantics'
  'native_bevy_classic_rts_selection_minimap'
  'accepted_input_count == 4'
  'final_minimap_command_tile_id == "9,2"'
  'classic_rts_selection_minimap_ppm_semantics'
  'native_bevy_classic_rts_selection_minimap_ppm'
  'classic_rts_build_lifecycle_semantics'
  'native_bevy_classic_rts_build_lifecycle'
  'accepted_input_count == 6'
  'final_structure_state == "cancelled:scout_tower@8,4"'
  'final_repair_target_id == "watch_tower"'
  'classic_rts_build_lifecycle_ppm_semantics'
  'native_bevy_classic_rts_build_lifecycle_ppm'
  'classic_rts_tech_tree_semantics'
  'native_bevy_classic_rts_tech_tree'
  'final_faction_id == "mirror_guard"'
  'final_tech_state == "unlocked:relay_guard"'
  'faction_base_gate == true'
  'dependency_gate == true'
	  'classic_rts_tech_tree_ppm_semantics'
	  'native_bevy_classic_rts_tech_tree_ppm'
	  'classic_rts_projectile_ability_semantics'
	  'native_bevy_classic_rts_projectile_ability'
	  'final_active_projectile_id == "guard_break_bolt"'
	  'final_ability_resolution_state == "resolved:guard_break:arena_creep_attack"'
	  'projectile_trail_gate == true'
	  'armor_shield_gate == true'
	  'classic_rts_projectile_ability_ppm_semantics'
	  'native_bevy_classic_rts_projectile_ability_ppm'
	  'packet integrity projectile/ability semantic fixture proves bad projectile/ability summary and PPM semantics fail even when checksums, bytes, contracts, and statuses match'
	  'first_minute_command_feedback_replay_semantics'
  'command_input_action_count == 7'
  'accepted_command_input_count == 7'
  'retained_history_group_ids == ["26", "27", "28"]'
  'pruned_history_group_ids == ["25", "24"]'
  'cleared_active_stale_pixel_count == 0'
  'first_minute_command_feedback_source_recording_semantics'
  'source_timeline_green == true'
  'first_minute_command_feedback_recording_semantics'
  'RTS:MOVE:18,31:line'
  'first_minute_command_feedback_replay_ppm_semantics'
  'first_minute_command_feedback_rejection_replay_semantics'
  'accepted_command_input_count == 1'
  'blocked_command_input_count == 6'
  'command_queue_rejection_pollution_count == 0'
  'rts_invalid_tile:bad-tile'
  'first_minute_command_feedback_rejection_source_recording_semantics'
  'first_minute_command_feedback_rejection_recording_semantics'
  'RTS:ABILITY:guard_break'
  'first_minute_command_feedback_rejection_replay_ppm_semantics'
  'bot_planner_action_executor_semantics'
  'native_bevy_bot_planner_action_executor'
  'bot_planner_action_executor_gate == true'
  'bot_planner_action_executor_log_semantics'
  'native_bevy_bot_planner_action_executor_log'
  'bot_planner_action_executor_ppm_semantics'
  'bot_planner_executor_replay_determinism_semantics'
  'native_bevy_bot_planner_executor_replay_determinism'
  'bot_planner_executor_replay_determinism_gate == true'
  'source_final_runtime_sha256 == .replay_final_runtime_sha256'
  'bot_planner_executor_replay_determinism_log_semantics'
  'native_bevy_bot_planner_executor_replay_determinism_log'
  'bot_planner_executor_replay_determinism_ppm_semantics'
  'multi_match_bot_executor_evaluation_semantics'
  'native_bevy_multi_match_bot_executor_evaluation'
  'multi_match_bot_executor_evaluation_gate == true'
  'variant_count == 4'
  'total_accepted_action_count == 24'
  'multi_match_bot_executor_evaluation_log_semantics'
  'native_bevy_multi_match_bot_executor_evaluation_log'
  'multi_match_bot_executor_evaluation_ppm_semantics'
  'packet integrity bot executor semantic fixture proves bad bot executor source-chain semantics fail even when checksums, bytes, contracts, and statuses match'
  'packet integrity bot executor failure/recovery matrix semantic fixture proves bad matrix semantics fail even when checksums, bytes, contracts, and statuses match'
  'bot_executor_failure_recovery_matrix_semantics'
  'bot_executor_failure_recovery_matrix_state == "bevy_executor_rejects_blocked_actions_and_recovers_without_command_queue_pollution_not_openra_runtime_bot"'
  'blocked_injection_count == 6'
  'blocked_rejection_count == 6'
  'blocked_command_queue_unchanged_count == 6'
  'recovery_accepted_action_count == 6'
  'recovery_command_delta_match_count == 6'
  'recovery_safe_runtime_sha_match == true'
  'source_multi_match_summary.variant_count == 4'
  'bot_executor_failure_recovery_matrix_log_semantics'
  'native_bevy_bot_executor_failure_recovery_matrix_log'
  'bot_executor_failure_recovery_matrix_ppm_semantics'
  'native_bevy_bot_executor_failure_recovery_matrix_ppm'
  'bot_decision_state_gap_semantics'
  'native_bevy_bot_decision_state_gap'
  'bevy_bot_decision_gap_state == "bevy_bot_decision_vocabulary_not_openra_native_bot_ai"'
  'bot_decision_state_gap_ppm_semantics'
  'native_bevy_bot_decision_state_gap_ppm'
  'bot_adaptive_build_order_gap_semantics'
  'native_bevy_bot_adaptive_build_order_gap'
  'bevy_bot_adaptive_build_gap_state == "bevy_adaptive_build_order_vocabulary_not_openra_native_ai_planner"'
  'bot_adaptive_build_order_gap_ppm_semantics'
  'native_bevy_bot_adaptive_build_order_gap_ppm'
  'bot_tactical_micro_gap_semantics'
  'native_bevy_bot_tactical_micro_gap'
  'bevy_bot_tactical_micro_gap_state == "bevy_tactical_micro_vocabulary_not_openra_native_combat_ai"'
  'bot_tactical_micro_gap_ppm_semantics'
  'native_bevy_bot_tactical_micro_gap_ppm'
  'bot_map_intel_gap_semantics'
  'native_bevy_bot_map_intel_gap'
  'bevy_bot_map_intel_gap_state == "bevy_map_intel_vocabulary_not_openra_native_shroud_memory_ai"'
  'bot_map_intel_gap_ppm_semantics'
  'native_bevy_bot_map_intel_gap_ppm'
  'packet integrity bot gap semantic fixture proves bad bot gap foundation/micro/intel semantics fail even when checksums, bytes, contracts, and statuses match'
  '1280 1080'
  'ppm_header_and_size_match'
  'release_review_packet_integrity_green_with_public_launch_blockers'
  'android_s5_real_device_claimed: false'
  'host_side_bevy_runtime_replay_not_android_real_device'
	  'packet_artifact_paths_must_exist_and_recorded_sha256_bytes_contract_status_must_match_current_files_including_checkpoint_manifest_packet_semantic_negative_fixture_classic_rts_control_loop_semantic_negative_fixture_classic_rts_selection_minimap_semantic_negative_fixture_classic_rts_build_lifecycle_semantic_negative_fixture_classic_rts_tech_tree_semantic_negative_fixture_classic_rts_projectile_ability_semantic_negative_fixture_bot_executor_source_chain_semantic_negative_fixture_bot_executor_failure_recovery_matrix_semantic_negative_fixture_bot_gap_foundation_micro_intel_semantic_negative_fixture_cex_adapter_local_bevy_playability_evidence_action_coach_semantics_player_hud_debug_layer_semantics_player_ui_rescue_semantics_live_window_screenshot_sequence_semantics_sprite_texture_sampling_semantics_live_window_sampled_texture_correlation_semantics_render_asset_eligibility_semantics_classic_playtest_readiness_semantics_full_screen_ui_replication_semantics_shell_meta_ui_replication_semantics_match_setup_ui_replication_semantics_campaign_outcome_ui_readiness_semantics_in_match_hud_state_replication_semantics_session_state_continuity_semantics_combat_readability_pressure_readiness_semantics_classic_rts_control_loop_semantics_classic_rts_selection_minimap_semantics_classic_rts_build_lifecycle_semantics_classic_rts_tech_tree_semantics_classic_rts_projectile_ability_semantics_first_minute_command_feedback_replay_semantics_first_minute_command_feedback_rejection_replay_semantics_bot_executor_source_chain_semantics_bot_executor_failure_recovery_matrix_semantics_and_bot_gap_foundation_micro_intel_semantics'
)

for line in "${required_lines[@]}"; do
  if ! grep -Fq -- "$line" "$SCRIPT"; then
    echo "[FAIL] release review packet integrity script missing contract line: $line" >&2
    exit 1
  fi
done

echo "[PASS] release review packet integrity script keeps packet refresh, checksum/byte/contract/status verification, first-minute command feedback replay/rejection semantic checks, no-refresh mode, and Android S5 boundary"
