#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SCRIPT="$ROOT/scripts/check_trillionnium_world_release_review_packet.sh"

required_lines=(
  'trillionnium_world_release_review_packet_v1'
  'check_trillionnium_world_release_review_convergence.sh'
  'release-review-packet.json'
  'release-review-packet.md'
  'release-review-packet-convergence.log'
  'release-review-packet-evidence-intake.log'
  'release-review-packet-blocker-consistency.log'
  'release-review-packet-evidence-kit.log'
  'release-review-packet-operator-handoff.log'
  'release-review-packet-template-negative-fixtures.log'
  'release-review-packet-evidence-bundle.log'
  'release-review-packet-bundle-negative-fixtures.log'
  'release-review-packet-map-modeling-gate.log'
  'release-review-packet-cex-adapter-readiness.log'
  'release-review-packet-checkpoint-manifest.log'
  'release-review-packet-integrity-semantic-fixture.log'
  'release-review-packet-integrity-bot-executor-semantic-fixture.log'
  'release-review-packet-integrity-bot-executor-matrix-semantic-fixture.log'
  'release-review-packet-integrity-bot-gap-semantic-fixture.log'
  'release-review-packet-integrity-control-loop-semantic-fixture.log'
  'release-review-packet-integrity-selection-minimap-semantic-fixture.log'
	  'release-review-packet-integrity-build-lifecycle-semantic-fixture.log'
	  'release-review-packet-integrity-tech-tree-semantic-fixture.log'
	  'release-review-packet-integrity-projectile-ability-semantic-fixture.log'
	  'release-review-packet-selection-minimap.log'
	  'release-review-packet-build-lifecycle.log'
	  'release-review-packet-tech-tree.log'
	  'release-review-packet-projectile-ability.log'
  'release-review-packet-bot-decision-state-gap.log'
  'release-review-packet-bot-adaptive-build-order-gap.log'
  'release-review-packet-bot-tactical-micro-gap.log'
  'release-review-packet-bot-map-intel-gap.log'
  'check_trillionnium_world_release_review_packet_integrity_semantic_fixture.sh'
  'check_trillionnium_world_release_review_packet_integrity_bot_executor_semantic_fixture.sh'
  'check_trillionnium_world_release_review_packet_integrity_bot_executor_matrix_semantic_fixture.sh'
  'check_trillionnium_world_release_review_packet_integrity_bot_gap_semantic_fixture.sh'
  'check_trillionnium_world_release_review_packet_integrity_control_loop_semantic_fixture.sh'
  'check_trillionnium_world_release_review_packet_integrity_selection_minimap_semantic_fixture.sh'
	  'check_trillionnium_world_release_review_packet_integrity_build_lifecycle_semantic_fixture.sh'
	  'check_trillionnium_world_release_review_packet_integrity_tech_tree_semantic_fixture.sh'
	  'check_trillionnium_world_release_review_packet_integrity_projectile_ability_semantic_fixture.sh'
	  'check_trillionnium_world_bevy_classic_rts_selection_minimap.sh'
	  'check_trillionnium_world_bevy_classic_rts_build_lifecycle.sh'
	  'check_trillionnium_world_bevy_classic_rts_tech_tree.sh'
	  'check_trillionnium_world_bevy_classic_rts_projectile_ability.sh'
  'check_trillionnium_world_bevy_classic_rts_bot_decision_state_gap.sh'
  'check_trillionnium_world_bevy_classic_rts_bot_adaptive_build_order_gap.sh'
  'check_trillionnium_world_bevy_classic_rts_bot_tactical_micro_gap.sh'
  'check_trillionnium_world_bevy_classic_rts_bot_map_intel_gap.sh'
  'sha256sum'
  'native_bevy_keyboard_replay'
  'native_bevy_action_coach'
  'bevy-action-coach.json'
  'native_bevy_player_hud_debug_layer'
  'bevy-player-hud-debug-layer.json'
  'native_bevy_player_ui_rescue'
  'bevy-player-ui-rescue.json'
  'native_bevy_live_window_screenshot_sequence'
  'bevy-live-window-screenshot-sequence.json'
  'native_bevy_sprite_texture_sampling'
  'bevy-sprite-texture-sampling.json'
  'native_bevy_live_window_sampled_texture_correlation'
  'bevy-live-window-sampled-texture-correlation.json'
  'native_bevy_render_asset_eligibility'
  'bevy-render-asset-eligibility.json'
  'native_bevy_classic_asset_pack'
  'bevy-classic-asset-pack.json'
  'native_bevy_classic_manifest_lint'
  'bevy-classic-manifest-lint.json'
  'native_bevy_classic_animation_preview'
  'bevy-classic-animation-preview.json'
  'native_bevy_classic_animation_preview_ppm'
  'bevy-classic-animation-preview.ppm'
  'native_bevy_classic_animation_selector'
  'bevy-classic-animation-selector.json'
  'native_bevy_classic_player_motion_probe'
  'bevy-classic-player-motion-probe.json'
  'native_bevy_classic_player_motion_probe_ppm'
  'bevy-classic-player-motion-probe.ppm'
  'native_bevy_classic_input_frame_budget'
  'bevy-classic-input-frame-budget.json'
  'native_bevy_classic_render_budget'
  'bevy-classic-render-budget.json'
  'native_bevy_classic_scene_preview'
  'bevy-classic-scene-preview.json'
  'native_bevy_classic_scene_preview_ppm'
  'bevy-classic-scene-preview.ppm'
  'native_bevy_classic_model_catalog'
  'bevy-classic-model-catalog.json'
  'native_bevy_classic_model_catalog_ppm'
  'bevy-classic-model-catalog.ppm'
  'native_bevy_classic_renderer_probe'
  'bevy-classic-renderer-probe.json'
  'native_bevy_classic_renderer_probe_ppm'
  'bevy-classic-renderer-probe.ppm'
  'native_bevy_classic_isometric_modeling'
  'bevy-classic-isometric-modeling.json'
  'native_bevy_classic_isometric_modeling_ppm'
  'bevy-classic-isometric-modeling.ppm'
  'native_bevy_classic_rts_control_loop'
  'bevy-classic-rts-control-loop.json'
  'native_bevy_classic_rts_control_loop_ppm'
  'bevy-classic-rts-control-loop.ppm'
  'native_bevy_classic_rts_selection_minimap'
  'bevy-classic-rts-selection-minimap.json'
  'native_bevy_classic_rts_selection_minimap_ppm'
  'bevy-classic-rts-selection-minimap.ppm'
  'native_bevy_classic_rts_build_lifecycle'
  'bevy-classic-rts-build-lifecycle.json'
  'native_bevy_classic_rts_build_lifecycle_ppm'
  'bevy-classic-rts-build-lifecycle.ppm'
	  'native_bevy_classic_rts_tech_tree'
	  'bevy-classic-rts-tech-tree.json'
	  'native_bevy_classic_rts_tech_tree_ppm'
	  'bevy-classic-rts-tech-tree.ppm'
	  'native_bevy_classic_rts_projectile_ability'
	  'bevy-classic-rts-projectile-ability.json'
	  'native_bevy_classic_rts_projectile_ability_ppm'
	  'bevy-classic-rts-projectile-ability.ppm'
	  'native_bevy_first_minute_command_feedback_replay'
  'bevy-first-minute-command-feedback-replay.json'
  'native_bevy_first_minute_command_feedback_source_recording'
  'bevy-first-minute-command-feedback-source-recording.json'
  'native_bevy_first_minute_command_feedback_recording'
  'bevy-first-minute-command-feedback-recording.json'
  'native_bevy_first_minute_command_feedback_replay_ppm'
  'bevy-first-minute-command-feedback-replay.ppm'
  'native_bevy_first_minute_command_feedback_rejection_replay'
  'bevy-first-minute-command-feedback-rejection-replay.json'
  'native_bevy_first_minute_command_feedback_rejection_source_recording'
  'bevy-first-minute-command-feedback-rejection-source-recording.json'
  'native_bevy_first_minute_command_feedback_rejection_recording'
  'bevy-first-minute-command-feedback-rejection-recording.json'
  'native_bevy_first_minute_command_feedback_rejection_replay_ppm'
  'bevy-first-minute-command-feedback-rejection-replay.ppm'
  'native_bevy_bot_planner_action_executor'
  'bevy-classic-rts-bot-planner-action-executor.json'
  'native_bevy_bot_planner_action_executor_log'
  'bot-planner-action-executor.actions.json'
  'native_bevy_bot_planner_action_executor_ppm'
  'bot-planner-action-executor.ppm'
  'native_bevy_bot_planner_executor_replay_determinism'
  'bevy-classic-rts-bot-planner-executor-replay-determinism.json'
  'native_bevy_bot_planner_executor_replay_determinism_log'
  'bot-planner-executor-replay-determinism.replay.json'
  'native_bevy_bot_planner_executor_replay_determinism_ppm'
  'bot-planner-executor-replay-determinism.ppm'
  'native_bevy_multi_match_bot_executor_evaluation'
  'bevy-classic-rts-multi-match-bot-executor-evaluation.json'
  'native_bevy_multi_match_bot_executor_evaluation_log'
  'multi-match-bot-executor-evaluation.matches.json'
  'native_bevy_multi_match_bot_executor_evaluation_ppm'
  'multi-match-bot-executor-evaluation.ppm'
  'native_bevy_bot_executor_failure_recovery_matrix'
  'bevy-classic-rts-bot-executor-failure-recovery-matrix.json'
  'native_bevy_bot_executor_failure_recovery_matrix_log'
  'bot-executor-failure-recovery-matrix.matrix.json'
  'native_bevy_bot_executor_failure_recovery_matrix_ppm'
  'bot-executor-failure-recovery-matrix.ppm'
  'native_bevy_bot_decision_state_gap'
  'bevy-classic-rts-bot-decision-state-gap.json'
  'native_bevy_bot_decision_state_gap_ppm'
  'bevy-classic-rts-bot-decision-state-gap.ppm'
  'native_bevy_bot_adaptive_build_order_gap'
  'bevy-classic-rts-bot-adaptive-build-order-gap.json'
  'native_bevy_bot_adaptive_build_order_gap_ppm'
  'bevy-classic-rts-bot-adaptive-build-order-gap.ppm'
  'native_bevy_bot_tactical_micro_gap'
  'bevy-classic-rts-bot-tactical-micro-gap.json'
  'native_bevy_bot_tactical_micro_gap_ppm'
  'bevy-classic-rts-bot-tactical-micro-gap.ppm'
  'native_bevy_bot_map_intel_gap'
  'bevy-classic-rts-bot-map-intel-gap.json'
  'native_bevy_bot_map_intel_gap_ppm'
  'bevy-classic-rts-bot-map-intel-gap.ppm'
  'native_bevy_classic_playtest_readiness'
  'bevy-classic-playtest-readiness.json'
  'native_bevy_classic_playtest_runner_status'
  'bevy-classic-playtest-runner-status.json'
  'native_bevy_classic_rts_full_screen_ui_replication'
  'Native/Bevy classic RTS full screen/UI replication'
  'bevy-classic-rts-full-screen-ui-replication.json'
  'native_bevy_classic_rts_shell_meta_ui_replication'
  'Native/Bevy classic RTS shell/meta UI replication'
  'bevy-classic-rts-shell-meta-ui-replication.json'
  'native_bevy_classic_rts_match_setup_ui_replication'
  'Native/Bevy classic RTS match setup UI replication'
  'bevy-classic-rts-match-setup-ui-replication.json'
  'native_bevy_classic_rts_campaign_outcome_ui_readiness'
  'Native/Bevy classic RTS campaign outcome UI readiness'
  'bevy-classic-rts-campaign-outcome-ui-readiness.json'
  'native_bevy_classic_rts_in_match_hud_state_replication'
  'Native/Bevy classic RTS in-match HUD/state replication'
  'bevy-classic-rts-in-match-hud-state-replication.json'
  'native_bevy_classic_rts_production_desktop_review_packet'
  'Native/Bevy classic RTS production desktop review packet'
  'bevy-classic-rts-production-desktop-review-packet.json'
  'cex_adapter_readiness'
  'CEX production world adapter readiness'
  'cex-production-adapter-readiness.json'
  'check_trillionnium_world_cex_adapter_readiness.sh'
  'release_review_checkpoint_manifest'
  'Release review checkpoint manifest'
  'release-review-checkpoint-manifest.json'
  'check_trillionnium_world_release_review_checkpoint_manifest.sh'
  'release_review_packet_integrity_semantic_fixture'
  'Release review packet integrity semantic fixture'
  'release-review-packet-integrity-semantic-fixture.json'
  'release_review_packet_integrity_bot_executor_semantic_fixture'
  'Release review packet integrity bot executor semantic fixture'
  'release-review-packet-integrity-bot-executor-semantic-fixture.json'
  'release_review_packet_integrity_bot_executor_matrix_semantic_fixture'
  'release_review_packet_integrity_bot_gap_semantic_fixture'
  'Release review packet integrity bot executor failure/recovery matrix semantic fixture'
  'release-review-packet-integrity-bot-executor-matrix-semantic-fixture.json'
  'release_review_packet_integrity_control_loop_semantic_fixture'
  'Release review packet integrity control loop semantic fixture'
  'release-review-packet-integrity-control-loop-semantic-fixture.json'
  'release_review_packet_integrity_selection_minimap_semantic_fixture'
  'Release review packet integrity selection/minimap semantic fixture'
  'release-review-packet-integrity-selection-minimap-semantic-fixture.json'
  'release_review_packet_integrity_build_lifecycle_semantic_fixture'
  'Release review packet integrity build lifecycle semantic fixture'
  'release-review-packet-integrity-build-lifecycle-semantic-fixture.json'
	  'release_review_packet_integrity_tech_tree_semantic_fixture'
	  'Release review packet integrity tech tree semantic fixture'
	  'release-review-packet-integrity-tech-tree-semantic-fixture.json'
	  'release_review_packet_integrity_projectile_ability_semantic_fixture'
	  'Release review packet integrity projectile/ability semantic fixture'
	  'release-review-packet-integrity-projectile-ability-semantic-fixture.json'
	  's5_real_device_evidence'
  's5-real-device-evidence-validation.json'
  'public_launch_readiness'
  'public_launch_evidence_intake'
  'public-launch-evidence-intake.json'
  'production_map_pack_public_evidence_collection'
  'production-map-pack-public-evidence-collection.json'
  'map_modeling_gate'
  'map-modeling-gate.json'
  'check_trillionnium_world_map_modeling_gate.sh'
  'cohort_commercial_evidence_collection'
  'cohort-commercial-evidence-collection.json'
  'external_ops_evidence_collection'
  'external-ops-evidence-collection.json'
  'public_launch_blocker_consistency'
  'public-launch-blocker-consistency.json'
  'check_trillionnium_world_public_launch_blocker_consistency.sh'
  'public_launch_evidence_kit'
  'public-launch-evidence-kit.json'
  'check_trillionnium_world_public_launch_evidence_kit.sh'
  'public_launch_operator_handoff'
  'public-launch-operator-handoff.json'
  'check_trillionnium_world_public_launch_operator_handoff.sh'
  'public_launch_template_negative_fixtures'
  'public-launch-template-negative-fixtures.json'
  'check_trillionnium_world_public_launch_template_negative_fixtures.sh'
  'public_launch_evidence_bundle'
  'public-launch-evidence-bundle.json'
  'check_trillionnium_world_public_launch_evidence_bundle.sh'
  'public_launch_bundle_negative_fixtures'
  'public-launch-bundle-negative-fixtures.json'
  'check_trillionnium_world_public_launch_bundle_negative_fixtures.sh'
  'public_launch_status_only_fixture_guard'
  'public-launch-status-only-fixtures.json'
  'production_map_pack_public_evidence'
  'production-map-pack-public-evidence.json'
  'cohort_commercial_evidence'
  'cohort-commercial-evidence.json'
  'external_ops_evidence'
  'external-ops-evidence.json'
  'release_signoff_summary'
  'release_review_quickcheck'
  'release_review_status_json'
  'release_review_status_markdown'
  'release_review_convergence'
  'android_s5_real_device_claimed: false'
  'host_side_bevy_runtime_replay_not_android_real_device'
  'sprite texture sampling'
  'sampled texture live-window correlation'
  'render asset eligibility'
  'classic scene preview'
  'classic manifest lint'
  'classic animation preview'
  'classic animation selector'
  'classic player motion probe'
  'classic input-frame budget'
  'classic render budget'
  'classic playtest readiness'
  'classic playtest runner status'
  'classic model catalog'
  'classic renderer probe'
  'classic isometric modeling'
  'classic RTS control loop'
  'first-minute command feedback replay'
  'first-minute command feedback rejection replay'
  'bot planner action executor'
  'bot planner executor replay determinism'
  'multi-match bot executor evaluation'
  'bot executor failure recovery matrix'
  'bot decision-state gap'
  'bot adaptive build-order gap'
  'packet integrity semantic fixture'
  'control loop semantic fixture'
  'bot executor semantic fixture'
  'bot executor failure/recovery matrix semantic fixture'
  'CEX adapter readiness proves the current CEX incubator exports the Trillionnium world runtime adapter contract'
  'Public launch operator handoff is a checksum-bound collection checklist'
  'The checkpoint manifest groups the current dirty working tree for review; it does not stage, commit, or publish anything.'
  'Still Requires Real External Evidence'
)

for line in "${required_lines[@]}"; do
  if ! grep -Fq -- "$line" "$SCRIPT"; then
    echo "[FAIL] release review packet script missing contract line: $line" >&2
    exit 1
  fi
done

echo "[PASS] release review packet script keeps convergence refresh, checksummed artifacts, packet outputs, and Android S5 boundary"
