#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
README="$ROOT/README.md"

required_lines=(
  '### 5.4 Trillionnium World release review quickcheck'
  './scripts/check_trillionnium_world_release_review_quickcheck.sh'
  './scripts/check_trillionnium_world_release_review_status.sh'
  './scripts/check_trillionnium_world_release_review_convergence.sh'
  './scripts/check_trillionnium_world_release_review_packet.sh'
  './scripts/check_trillionnium_world_release_review_packet_integrity.sh'
  './scripts/check_trillionnium_world_release_review_ci_gate.sh'
  './scripts/check_trillionnium_world_release_review_checkpoint_manifest.sh'
  './scripts/check_trillionnium_world_next_execution_plan.sh'
  './scripts/check_trillionnium_world_review_slice_manifest.sh'
  './scripts/check_trillionnium_world_review_triage_queue.sh'
  './scripts/check_trillionnium_world_review_primary_owner_plan.sh'
  './scripts/check_trillionnium_world_review_release_owner_queue.sh'
  './scripts/check_trillionnium_world_review_runtime_owner_queue.sh'
  './scripts/check_trillionnium_world_review_residual_queue.sh'
  './scripts/check_trillionnium_world_review_execution_batches.sh'
  './scripts/check_trillionnium_world_review_public_boundary_batch.sh'
  './scripts/check_trillionnium_world_review_release_native_handoff_batch.sh'
  './scripts/check_trillionnium_world_review_runtime_boundary_batch.sh'
  './scripts/check_trillionnium_world_review_runtime_core_semantics_batch.sh'
  './scripts/check_trillionnium_world_review_runtime_adapter_online_batch.sh'
  './scripts/check_trillionnium_world_review_openra_parity_claim_batch.sh'
  './scripts/check_trillionnium_world_review_first_contact_rts_data_batch.sh'
  './scripts/check_trillionnium_world_review_rts_evidence_crate_batch.sh'
  './scripts/check_trillionnium_world_review_evidence_exposure_batch.sh'
  './scripts/check_trillionnium_world_review_bevy_runtime_renderer_batch.sh'
  './scripts/check_trillionnium_world_review_first_contact_player_surface_cues_batch.sh'
  './scripts/check_trillionnium_world_review_generated_count_surface_batch.sh'
  './scripts/check_trillionnium_world_review_docs_plan_truth_source_batch.sh'
  './scripts/check_trillionnium_world_public_launch_blocker_execution_ledger.sh'
  './scripts/check_trillionnium_world_public_launch_operator_handoff.sh'
  './scripts/check_trillionnium_world_production_map_pack_public_evidence_collection.sh'
  './scripts/check_trillionnium_world_production_map_pack_public_evidence.sh'
  './scripts/check_trillionnium_world_cohort_commercial_evidence_collection.sh'
  './scripts/check_trillionnium_world_cohort_commercial_evidence.sh'
  './scripts/check_trillionnium_world_external_ops_evidence_collection.sh'
  './scripts/check_trillionnium_world_external_ops_evidence.sh'
  './scripts/check_trillionnium_world_bevy_action_coach.sh'
  './scripts/check_trillionnium_world_bevy_player_hud_debug_layer.sh'
  './scripts/check_trillionnium_world_bevy_player_ui_rescue.sh'
  './scripts/check_trillionnium_world_bevy_live_window_screenshot_sequence.sh'
  './scripts/check_trillionnium_world_bevy_sprite_texture_sampling.sh'
  './scripts/check_trillionnium_world_bevy_live_window_sampled_texture_correlation.sh'
  './scripts/check_trillionnium_world_bevy_render_asset_eligibility.sh'
  './scripts/check_trillionnium_world_cex_adapter_readiness.sh'
  './scripts/check_trillionnium_world_s5_device_evidence.sh --require-device'
  './scripts/check_trillionnium_world_s5_real_device_evidence.sh'
  './scripts/check_trillionnium_world_release_review_quickcheck.sh --require-ready'
  'acceptance/S6_public_launch/latest/release-review-quickcheck.json'
  'acceptance/S6_public_launch/latest/release-review-status.md'
  'acceptance/S6_public_launch/latest/release-review-convergence.json'
  'acceptance/S6_public_launch/latest/release-review-packet.json'
  'acceptance/S6_public_launch/latest/release-review-packet-integrity.json'
  'acceptance/S6_public_launch/latest/release-review-ci-gate.json'
  'acceptance/S6_public_launch/latest/release-review-checkpoint-manifest.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-next-execution-plan.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-slice-manifest.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-triage-queue.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-primary-owner-plan.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-release-owner-queue.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-runtime-owner-queue.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-residual-queue.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-execution-batches.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-public-boundary-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-release-native-handoff-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-runtime-boundary-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-runtime-core-semantics-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-runtime-adapter-online-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-openra-parity-claim-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-first-contact-rts-data-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-rts-evidence-crate-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-evidence-exposure-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-bevy-runtime-renderer-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-first-contact-player-surface-cues-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-review-docs-plan-truth-source-batch.json'
  'acceptance/S6_public_launch/latest/trillionnium-world-public-launch-blocker-execution-ledger.json'
  'acceptance/S6_public_launch/latest/public-launch-operator-handoff.json'
  'checksum-binding the six collection actions, templates, validator commands, bundle template, and negative fixtures'
  'grouping the current dirty working tree into review/commit slices without staging, committing, or claiming public-launch evidence'
  'Native/Bevy keyboard replay, classic animation preview/selector, classic player motion, action coach, player HUD/debug layer, player UI rescue, live-window screenshot and mouse hit-test evidence, sprite texture sampling, sampled texture live-window correlation, render asset eligibility, CEX adapter readiness'
  'It does not claim GPU upload, render-world extraction completion, Android S5 real-device readiness, or external public-launch readiness.'
  'packet artifact count now at `128`'
  'current packet at artifact count `128`'
  'whole-screen First Contact readability'
  'review-slice manifest'
  'review triage queue'
  'review primary-owner plan'
  'release-owner queue'
  'runtime-owner queue'
  'residual queue'
  'review execution batches'
  'public-boundary batch review'
  'release-native handoff batch review'
  'runtime-boundary batch review'
  'runtime-core semantics batch review'
  'runtime-adapter/online batch review'
  'OpenRA parity/claim batch review'
  'First Contact RTS data extraction batch review'
  'RTS evidence crate batch review'
  'Review evidence exposure batch note'
  'Bevy runtime renderer batch note'
  'First Contact player-surface cues batch note'
  'unblocks batch 4 `unclassified_generated_count_surface`'
  'Generated count surface batch note'
  'unblocks batch 5 `unclassified_docs_plan_truth_source`'
  'Docs/plan truth-source batch note'
  'unblocks batch 6 `unclassified_bot_executor_surface`'
  'blocker execution ledger'
  'public-launch blockers preserved'
)

for line in "${required_lines[@]}"; do
  if ! grep -Fq -- "$line" "$README"; then
    echo "[FAIL] README missing Trillionnium World release review quickcheck line: $line" >&2
    exit 1
  fi
done

echo "[PASS] README keeps Trillionnium World release review quickcheck/status/convergence/packet/integrity/ci-gate/checkpoint/next-plan commands, S5 collection+validation, strict mode, output files, and Android S5 boundary"
