[package]
name = "trnm-world-ui-fragments"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
trnm-world-command = { path = "../trnm-world-command" }
trnm-world-domain = { path = "../trnm-world-domain" }
trnm-world-projection = { path = "../trnm-world-projection" }

[dev-dependencies]
serde_json = "1"
