#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EVIDENCE_DIR="$ROOT/acceptance/S5_native_bevy_device/latest"
mkdir -p "$EVIDENCE_DIR"

SUMMARY="$EVIDENCE_DIR/bevy-first-playable.json"

(
  cd "$ROOT/trillionnium"
  cargo run -p trnm-world-bevy -- first-playable >"$SUMMARY"
)

jq -e '
  .contract_version == "trillionnium_world_bevy_first_playable_v1"
  and .rust_authority == "client_submits_intent_only_rust_world_command_layer_authoritative"
  and (.acceptance.status == "host_first_playable_loop_green")
  and (.acceptance.first_playable_green == true)
  and (.acceptance.native_bevy_engine_path == true)
  and (.acceptance.game_feedback_contract == "trillionnium_world_bevy_game_feedback_v1")
  and (.acceptance.game_feedback_green == true)
  and (.acceptance.tile_rpg_ui_contract == "trillionnium_world_bevy_tile_rpg_ui_v1")
  and (.acceptance.tile_rpg_ui_green == true)
  and (.acceptance.tile_rpg_reference_policy == "original_tile_rpg_layout_no_copied_assets_code_or_story_text")
  and (.acceptance.tile_rpg_surfaces | index("top_down_tilemap_viewport"))
  and (.acceptance.tile_rpg_surfaces | index("outdoor_town_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("indoor_room_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("stone_road_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("water_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("town_wall_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("building_roof_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("building_wall_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("door_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("roof_shadow_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("water_edge_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("furniture_props"))
  and (.acceptance.tile_rpg_surfaces | index("tree_props"))
  and (.acceptance.tile_rpg_surfaces | index("tree_canopy_tiles"))
  and (.acceptance.tile_rpg_surfaces | index("player_chibi_sprite"))
  and (.acceptance.tile_rpg_surfaces | index("player_chibi_head"))
  and (.acceptance.tile_rpg_surfaces | index("player_chibi_hair"))
  and (.acceptance.tile_rpg_surfaces | index("player_chibi_feet"))
  and (.acceptance.tile_rpg_surfaces | index("player_facing_frame"))
  and (.acceptance.tile_rpg_surfaces | index("npc_chibi_sprite"))
  and (.acceptance.tile_rpg_surfaces | index("npc_chibi_head"))
  and (.acceptance.tile_rpg_surfaces | index("npc_chibi_hair"))
  and (.acceptance.tile_rpg_surfaces | index("npc_facing_frame"))
  and (.acceptance.tile_rpg_surfaces | index("enemy_facing_frame"))
  and (.acceptance.tile_rpg_surfaces | index("sprite_shadow"))
  and (.acceptance.tile_rpg_surfaces | index("virtual_joystick"))
  and (.acceptance.tile_rpg_surfaces | index("right_action_buttons"))
  and (.acceptance.tile_rpg_surfaces | index("paper_skill_menu_overlay"))
  and (.acceptance.tile_rpg_surfaces | index("monochrome_stat_panel"))
  and (.acceptance.tile_rpg_interaction_contract == "trillionnium_world_bevy_tile_rpg_interaction_v1")
  and (.acceptance.tile_rpg_interaction_green == true)
  and (.acceptance.tile_rpg_interaction_surfaces | index("grid_step_animation_state"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("npc_dialogue_state"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("scene_transition_state"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("indoor_training_room_state"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("combat_enter_return_state"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("visible_dialogue_choice_panel"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("visible_scene_transition_panel"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("visible_combat_scene_panel"))
  and (.acceptance.tile_rpg_interaction_surfaces | index("visible_walk_animation_panel"))
  and (.acceptance.scene_transition_playability_contract == "trillionnium_world_bevy_scene_transition_playability_v1")
  and (.acceptance.scene_transition_playability_green == true)
  and (.acceptance.scene_transition_playability_surfaces | index("talk_dialogue_overlay"))
  and (.acceptance.scene_transition_playability_surfaces | index("train_indoor_training_room_tilemap"))
  and (.acceptance.scene_transition_playability_surfaces | index("move_tile_to_tile_interpolation"))
  and (.acceptance.scene_transition_playability_surfaces | index("fight_combat_overlay"))
  and (.acceptance.scene_transition_playability_surfaces | index("enemy_damage_feedback"))
  and (.acceptance.map_quality_contract == "trillionnium_world_bevy_tile_rpg_map_quality_v1")
  and (.acceptance.map_quality_green == true)
  and (.acceptance.map_quality_surfaces | index("layered_house_roof_wall_door"))
  and (.acceptance.map_quality_surfaces | index("stone_road_water_edge_tree_canopy"))
  and (.acceptance.map_quality_surfaces | index("player_facing_frame"))
  and (.acceptance.map_quality_surfaces | index("mentor_facing_frame"))
  and (.acceptance.map_quality_surfaces | index("enemy_facing_frame"))
  and (.acceptance.visual_feedback_surfaces | index("player_hp_bar"))
  and (.acceptance.visual_feedback_surfaces | index("enemy_hp_bar"))
  and (.acceptance.visual_feedback_surfaces | index("xp_bar"))
  and (.acceptance.visual_feedback_surfaces | index("combat_feedback_banner"))
  and (.acceptance.visual_feedback_surfaces | index("reward_toast"))
  and (.acceptance.android_s5_real_device_claimed == false)
  and (.current_room.node_id == "league-coliseum")
  and (.runtime.tutorial_step == "first_playable_loop_complete")
  and (.runtime.objective_status == "first_playable_loop_complete")
  and (.runtime.reward_claimed == true)
  and (.runtime.equipment_ready == true)
  and (.runtime.last_feedback == "Reward equipped: Route Guard Staff ready")
  and (.runtime.map_scene == "arena_outdoor")
  and (.runtime.npc_dialogue_state == "mentor_training_complete")
  and (.runtime.combat_scene_state == "combat_returned_to_map")
  and (.runtime.scene_transition == "combat_overlay_return_to_map")
  and (.runtime.last_tile_step == "step_north")
  and (.runtime.walk_cycle_frame >= 1)
  and (.runtime.active_scene_layer == "arena_outdoor_tilemap")
  and (.runtime.tilemap_variant == "arena_outdoor")
  and (.runtime.movement_lock_observed == true)
  and (.runtime.movement_input_locked == false)
  and (.runtime.tile_step_progress_percent == 100)
  and (.runtime.movement_from_tile == "mentor_room_exit_tile")
  and (.runtime.movement_to_tile == "arena_gate_tile")
  and (.runtime.tile_interpolation_samples | length) >= 3
  and (.runtime.npc_behavior_history | index("dialogue_choice_opened"))
  and (.runtime.npc_behavior_history | index("training_feedback_visible"))
  and (.runtime.enemy_behavior_history | index("enemy_visible_at_arena"))
  and (.runtime.enemy_behavior_history | index("enemy_damage_feedback_visible"))
  and (.runtime.enemy_behavior_history | index("enemy_hp_changed"))
  and (.runtime.feedback_events | length) >= 6
  and (.runtime.xp >= 40)
  and (.runtime.coins >= 10)
  and (.completed_loop | index("talk_to_mentor"))
  and (.completed_loop | index("train_basic_unarmed"))
  and (.completed_loop | index("arrive_at_first_objective"))
  and (.completed_loop | index("resolve_first_combat"))
  and (.completed_loop | index("complete_first_task"))
  and (.completed_loop | index("equip_route_guard_staff"))
  and (.completed_loop | index("npc_dialogue_opened"))
  and (.completed_loop | index("enter_training_room"))
  and (.completed_loop | index("walk_grid_step_recorded"))
  and (.completed_loop | index("exit_training_room_to_arena_route"))
  and (.completed_loop | index("combat_scene_entered"))
  and (.completed_loop | index("combat_scene_returned"))
  and (.character.skill_ids | index("basic_unarmed"))
  and (.character.equipment_slots.weapon != null)
  and (.persistence.round_trip_status == "save_restore_green")
' "$SUMMARY" >/dev/null

printf 'TRILLIONNIUM_WORLD_BEVY_FIRST_PLAYABLE_GREEN %s\n' "$SUMMARY"
