#!/usr/bin/env python3
"""Generate exact Rust and Go authority-boundary constants from one registry."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "trillionnium/contracts/trnm-world-rules-contract-v1/schema/authority-boundary-v1.json"
RUST_PATH = ROOT / "trillionnium/contracts/trnm-world-rules-contract-v1/src/boundary_generated.rs"
GO_PATH = ROOT / "tools/trnm-world-transition-https-v1/internal/fixture/boundary_generated.go"
KEY_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")


class GenerationError(ValueError):
    pass


def load_spec() -> tuple[int, str, list[str]]:
    try:
        document = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise GenerationError("authority boundary registry is unreadable") from error
    if not isinstance(document, dict) or set(document) != {
        "schema",
        "diagnostic_fallback",
        "diagnostic_max_utf8_bytes",
        "forbidden_authority_keys",
    }:
        raise GenerationError("authority boundary registry fields differ")
    if document["schema"] != "trnm.world.authority-boundary.v1":
        raise GenerationError("authority boundary registry schema differs")
    maximum = document["diagnostic_max_utf8_bytes"]
    fallback = document["diagnostic_fallback"]
    keys = document["forbidden_authority_keys"]
    if (
        not isinstance(maximum, int)
        or isinstance(maximum, bool)
        or maximum < 1
        or maximum > 4096
        or not isinstance(fallback, str)
        or not fallback
        or len(fallback.encode("utf-8")) > maximum
        or not isinstance(keys, list)
        or not keys
        or not all(isinstance(key, str) and KEY_PATTERN.fullmatch(key) for key in keys)
        or keys != sorted(keys)
        or len(keys) != len(set(keys))
    ):
        raise GenerationError("authority boundary registry values are invalid")
    return maximum, fallback, keys


def rust_source(maximum: int, fallback: str, keys: list[str]) -> str:
    entries = "".join(f'    "{key}",\n' for key in keys)
    return f'''// @generated by tools/generate-trnm-world-boundary.py; DO NOT EDIT.\n\npub const DIAGNOSTIC_MAX_UTF8_BYTES: usize = {maximum};\npub const DIAGNOSTIC_FALLBACK: &str = {json.dumps(fallback)};\npub const FORBIDDEN_AUTHORITY_KEYS: &[&str] = &[\n{entries}];\n\npub fn is_forbidden_authority_key(value: &str) -> bool {{\n    FORBIDDEN_AUTHORITY_KEYS\n        .iter()\n        .any(|candidate| candidate.eq_ignore_ascii_case(value))\n}}\n\npub fn bound_diagnostic_utf8(value: &str) -> String {{\n    let mut output = String::with_capacity(value.len().min(DIAGNOSTIC_MAX_UTF8_BYTES));\n    for character in value.chars() {{\n        let normalized = if character < '\\u{{20}}' || character == '\\u{{7f}}' {{\n            ' '\n        }} else {{\n            character\n        }};\n        if output.len() + normalized.len_utf8() > DIAGNOSTIC_MAX_UTF8_BYTES {{\n            break;\n        }}\n        output.push(normalized);\n    }}\n    let bounded = output.trim();\n    if bounded.is_empty() {{\n        DIAGNOSTIC_FALLBACK.to_owned()\n    }} else {{\n        bounded.to_owned()\n    }}\n}}\n'''


def go_source(maximum: int, fallback: str, keys: list[str]) -> str:
    entries = "".join(f'\t"{key}": {{}},\n' for key in keys)
    return f'''// Code generated by tools/generate-trnm-world-boundary.py; DO NOT EDIT.\n\npackage fixture\n\nconst (\n\tDiagnosticMaxUTF8Bytes = {maximum}\n\tDiagnosticFallback     = {json.dumps(fallback)}\n)\n\nvar generatedForbiddenAuthorityKeys = map[string]struct{{}}{{\n{entries}}}\n'''


def write_or_check(path: Path, expected: str, *, check: bool) -> None:
    if check:
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError as error:
            raise GenerationError(
                f"generated file is missing: {path.relative_to(ROOT)}"
            ) from error
        if actual != expected:
            raise GenerationError(
                f"generated file is stale: {path.relative_to(ROOT)}"
            )
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        maximum, fallback, keys = load_spec()
        write_or_check(
            RUST_PATH,
            rust_source(maximum, fallback, keys),
            check=args.check,
        )
        if GO_PATH.parent.is_dir():
            write_or_check(
                GO_PATH,
                go_source(maximum, fallback, keys),
                check=args.check,
            )
    except GenerationError as error:
        print(f"FAIL {error}")
        return 1
    print("PASS trnm World authority-boundary generated sources are exact")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
