use trnm_types::{CapabilityScope, IdentityRegistry, InteropIdentityError};

#[path = "i3_capability_issue_renew_revoke_competition/i3_capability_issue_renew_revoke_competition_race.rs"]
mod i3_capability_issue_renew_revoke_competition_race;

#[path = "i3_capability_issue_renew_revoke_competition/i3_capability_issue_renew_revoke_competition_verify.rs"]
mod i3_capability_issue_renew_revoke_competition_verify;

#[path = "i3_capability_issue_renew_revoke_competition/i3_capability_issue_renew_revoke_competition_did_boundary.rs"]
mod i3_capability_issue_renew_revoke_competition_did_boundary;
